version: v2beta1
name: ccip-v2-scripts

vars:
  LOCAL_TEMPLATES_DIR:
    source: env
    default: ./templates
  TMP_DIR:
    source: env
    default: "${DEVSPACE_TMPDIR}/ccip-v2"
  CHAINS_COUNT:
    source: env
    default: 2

pipelines:
  # deploy home chain contracts and return capability registry address
  deploy-home-chain-contracts: |-
    echo "running deploy scripts"

    tmp_dir="${TMP_DIR}"
    mkdir -p "$tmp_dir"
    task ccip-v2-scripts:build
    ccip-v2-scripts deploy-home-chain --deploy-home-out "$TMP_DIR"

  deploy-ccip: |-
    echo "deploy on chain contracts (tokens, lanes, token pools, price registry, router)"
    ccip-v2-scripts deploy-ccip \
      --deploy-ccip-in "$TMP_DIR" \
      --deploy-ccip-out "$TMP_DIR"
