version: v2beta1

pipelines:
  deploy:
    run: |-
      create_deployments postgres

deployments:
  postgres:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: oci://registry-1.docker.io/bitnamicharts/postgresql
        version: 16.4.5
      values:
        architecture: standalone
        fullnameOverride: postgres
        auth:
          enablePostgresUser: true
          postgresPassword: postgres
          username: chainlink
          password: JGVgp7M2Emcg7Av8KKVUgMZb
          database: chainlink
          existingSecret: ''
        image:
          registry: docker.io
          repository: bitnami/postgresql
        tls:
          enabled: false
        containerPorts:
          postgresql: 5432
        primary:
          persistence:
            enabled: false
            size: 5Gi
            storageClass: gp3
        networkPolicy:
          enabled: false
        volumePermissions:
          enabled: false
        metrics:
          enabled: false

hooks:
  - wait:
      running: true
      terminatedWithCode: 0
      timeout: 600
    container:
      labelSelector:
        app.kubernetes.io/instance: "postgres"
    events: ["after:deploy:postgres"]

profiles:
  - name: job-distributor-size-medium
    merge:
      deployments:
        postgres:
          helm:
            values:
              primary:
                resources:
                  requests:
                    cpu: 500m
                    memory: 256Mi
                    ephemeral-storage: 50Mi
                  limits:
                    cpu: 2000m
                    memory: 512Mi
                    ephemeral-storage: 2Gi

  - name: aws-main-stage-cluster
    activation:
      - vars:
          CRIB_EKS_CLUSTER_NAME: "main-stage-cluster"
          PROVIDER: "aws"
    merge:
      deployments:
        postgres:
          helm:
            values:
              primary:
                nodeSelector:
                  node-role: crib
                tolerations:
                  - key: "node-role"
                    operator: "Equal"
                    value: "crib"
                    effect: "NoSchedule"
