// Code generated by operations-gen. DO NOT EDIT.

package token_pool

import (
	"github.com/Masterminds/semver/v3"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"

	gobindings "github.com/smartcontractkit/chainlink-ccip/chains/evm/gobindings/generated/v1_6_1/token_pool"
	cldf_evm "github.com/smartcontractkit/chainlink-deployments-framework/chain/evm"
	"github.com/smartcontractkit/chainlink-deployments-framework/chain/evm/operations2/contract"
	cldf_deployment "github.com/smartcontractkit/chainlink-deployments-framework/deployment"
	cld_ops "github.com/smartcontractkit/chainlink-deployments-framework/operations"
)

var ContractType cldf_deployment.ContractType = "TokenPool"
var Version = semver.MustParse("1.6.1")
var TypeAndVersion = cldf_deployment.NewTypeAndVersion(ContractType, *Version)

type ApplyChainUpdatesArgs struct {
	RemoteChainSelectorsToRemove []uint64                          `json:"remoteChainSelectorsToRemove"`
	ChainsToAdd                  []gobindings.TokenPoolChainUpdate `json:"chainsToAdd"`
}

type SetChainRateLimiterConfigsArgs struct {
	RemoteChainSelectors []uint64                       `json:"remoteChainSelectors"`
	OutboundConfigs      []gobindings.RateLimiterConfig `json:"outboundConfigs"`
	InboundConfigs       []gobindings.RateLimiterConfig `json:"inboundConfigs"`
}

type SetChainRateLimiterConfigArgs struct {
	RemoteChainSelector uint64                       `json:"remoteChainSelector"`
	OutboundConfig      gobindings.RateLimiterConfig `json:"outboundConfig"`
	InboundConfig       gobindings.RateLimiterConfig `json:"inboundConfig"`
}

type ApplyAllowListUpdatesArgs struct {
	Removes []common.Address `json:"removes"`
	Adds    []common.Address `json:"adds"`
}

type AddRemotePoolArgs struct {
	RemoteChainSelector uint64 `json:"remoteChainSelector"`
	RemotePoolAddress   []byte `json:"remotePoolAddress"`
}

type RemoveRemotePoolArgs struct {
	RemoteChainSelector uint64 `json:"remoteChainSelector"`
	RemotePoolAddress   []byte `json:"remotePoolAddress"`
}

func NewWriteApplyChainUpdates(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[ApplyChainUpdatesArgs], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[ApplyChainUpdatesArgs, gobindings.TokenPoolInterface]{
		Name:         "token-pool:apply-chain-updates",
		Version:      Version,
		Description:  "Calls applyChainUpdates on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.TokenPoolMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, caller common.Address, args ApplyChainUpdatesArgs) (bool, error) {
			return contract.OnlyOwner(c, opts, caller, args)
		},
		CallContract: func(
			c gobindings.TokenPoolInterface,
			opts *bind.TransactOpts,
			args ApplyChainUpdatesArgs,
		) (*types.Transaction, error) {
			return c.ApplyChainUpdates(opts, args.RemoteChainSelectorsToRemove, args.ChainsToAdd)
		},
	})
}

func NewWriteSetRateLimitAdmin(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[common.Address], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[common.Address, gobindings.TokenPoolInterface]{
		Name:         "token-pool:set-rate-limit-admin",
		Version:      Version,
		Description:  "Calls setRateLimitAdmin on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.TokenPoolMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, caller common.Address, args common.Address) (bool, error) {
			return contract.OnlyOwner(c, opts, caller, args)
		},
		CallContract: func(
			c gobindings.TokenPoolInterface,
			opts *bind.TransactOpts,
			args common.Address,
		) (*types.Transaction, error) {
			return c.SetRateLimitAdmin(opts, args)
		},
	})
}

func NewReadGetRateLimitAdmin(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[struct{}], common.Address, cldf_evm.Chain] {
	return contract.NewRead(contract.ReadParams[struct{}, common.Address, gobindings.TokenPoolInterface]{
		Name:         "token-pool:get-rate-limit-admin",
		Version:      Version,
		Description:  "Calls getRateLimitAdmin on the contract",
		ContractType: ContractType,
		Contract:     c,
		CallContract: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, args struct{}) (common.Address, error) {
			return c.GetRateLimitAdmin(opts)
		},
	})
}

func NewWriteTransferOwnership(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[common.Address], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[common.Address, gobindings.TokenPoolInterface]{
		Name:         "token-pool:transfer-ownership",
		Version:      Version,
		Description:  "Calls transferOwnership on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.TokenPoolMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, caller common.Address, args common.Address) (bool, error) {
			return contract.OnlyOwner(c, opts, caller, args)
		},
		CallContract: func(
			c gobindings.TokenPoolInterface,
			opts *bind.TransactOpts,
			args common.Address,
		) (*types.Transaction, error) {
			return c.TransferOwnership(opts, args)
		},
	})
}

func NewWriteSetChainRateLimiterConfigs(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[SetChainRateLimiterConfigsArgs], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[SetChainRateLimiterConfigsArgs, gobindings.TokenPoolInterface]{
		Name:         "token-pool:set-chain-rate-limiter-configs",
		Version:      Version,
		Description:  "Calls setChainRateLimiterConfigs on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.TokenPoolMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, caller common.Address, args SetChainRateLimiterConfigsArgs) (bool, error) {
			return contract.OnlyOwner(c, opts, caller, args)
		},
		CallContract: func(
			c gobindings.TokenPoolInterface,
			opts *bind.TransactOpts,
			args SetChainRateLimiterConfigsArgs,
		) (*types.Transaction, error) {
			return c.SetChainRateLimiterConfigs(opts, args.RemoteChainSelectors, args.OutboundConfigs, args.InboundConfigs)
		},
	})
}

func NewWriteSetChainRateLimiterConfig(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[SetChainRateLimiterConfigArgs], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[SetChainRateLimiterConfigArgs, gobindings.TokenPoolInterface]{
		Name:         "token-pool:set-chain-rate-limiter-config",
		Version:      Version,
		Description:  "Calls setChainRateLimiterConfig on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.TokenPoolMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, caller common.Address, args SetChainRateLimiterConfigArgs) (bool, error) {
			return contract.OnlyOwner(c, opts, caller, args)
		},
		CallContract: func(
			c gobindings.TokenPoolInterface,
			opts *bind.TransactOpts,
			args SetChainRateLimiterConfigArgs,
		) (*types.Transaction, error) {
			return c.SetChainRateLimiterConfig(opts, args.RemoteChainSelector, args.OutboundConfig, args.InboundConfig)
		},
	})
}

func NewReadGetToken(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[struct{}], common.Address, cldf_evm.Chain] {
	return contract.NewRead(contract.ReadParams[struct{}, common.Address, gobindings.TokenPoolInterface]{
		Name:         "token-pool:get-token",
		Version:      Version,
		Description:  "Calls getToken on the contract",
		ContractType: ContractType,
		Contract:     c,
		CallContract: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, args struct{}) (common.Address, error) {
			return c.GetToken(opts)
		},
	})
}

func NewReadGetTokenDecimals(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[struct{}], uint8, cldf_evm.Chain] {
	return contract.NewRead(contract.ReadParams[struct{}, uint8, gobindings.TokenPoolInterface]{
		Name:         "token-pool:get-token-decimals",
		Version:      Version,
		Description:  "Calls getTokenDecimals on the contract",
		ContractType: ContractType,
		Contract:     c,
		CallContract: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, args struct{}) (uint8, error) {
			return c.GetTokenDecimals(opts)
		},
	})
}

func NewReadIsSupportedToken(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[common.Address], bool, cldf_evm.Chain] {
	return contract.NewRead(contract.ReadParams[common.Address, bool, gobindings.TokenPoolInterface]{
		Name:         "token-pool:is-supported-token",
		Version:      Version,
		Description:  "Calls isSupportedToken on the contract",
		ContractType: ContractType,
		Contract:     c,
		CallContract: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, args common.Address) (bool, error) {
			return c.IsSupportedToken(opts, args)
		},
	})
}

func NewReadGetAllowListEnabled(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[struct{}], bool, cldf_evm.Chain] {
	return contract.NewRead(contract.ReadParams[struct{}, bool, gobindings.TokenPoolInterface]{
		Name:         "token-pool:get-allow-list-enabled",
		Version:      Version,
		Description:  "Calls getAllowListEnabled on the contract",
		ContractType: ContractType,
		Contract:     c,
		CallContract: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, args struct{}) (bool, error) {
			return c.GetAllowListEnabled(opts)
		},
	})
}

func NewReadGetAllowList(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[struct{}], []common.Address, cldf_evm.Chain] {
	return contract.NewRead(contract.ReadParams[struct{}, []common.Address, gobindings.TokenPoolInterface]{
		Name:         "token-pool:get-allow-list",
		Version:      Version,
		Description:  "Calls getAllowList on the contract",
		ContractType: ContractType,
		Contract:     c,
		CallContract: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, args struct{}) ([]common.Address, error) {
			return c.GetAllowList(opts)
		},
	})
}

func NewWriteApplyAllowListUpdates(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[ApplyAllowListUpdatesArgs], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[ApplyAllowListUpdatesArgs, gobindings.TokenPoolInterface]{
		Name:         "token-pool:apply-allow-list-updates",
		Version:      Version,
		Description:  "Calls applyAllowListUpdates on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.TokenPoolMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, caller common.Address, args ApplyAllowListUpdatesArgs) (bool, error) {
			return contract.OnlyOwner(c, opts, caller, args)
		},
		CallContract: func(
			c gobindings.TokenPoolInterface,
			opts *bind.TransactOpts,
			args ApplyAllowListUpdatesArgs,
		) (*types.Transaction, error) {
			return c.ApplyAllowListUpdates(opts, args.Removes, args.Adds)
		},
	})
}

func NewReadGetRouter(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[struct{}], common.Address, cldf_evm.Chain] {
	return contract.NewRead(contract.ReadParams[struct{}, common.Address, gobindings.TokenPoolInterface]{
		Name:         "token-pool:get-router",
		Version:      Version,
		Description:  "Calls getRouter on the contract",
		ContractType: ContractType,
		Contract:     c,
		CallContract: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, args struct{}) (common.Address, error) {
			return c.GetRouter(opts)
		},
	})
}

func NewWriteSetRouter(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[common.Address], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[common.Address, gobindings.TokenPoolInterface]{
		Name:         "token-pool:set-router",
		Version:      Version,
		Description:  "Calls setRouter on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.TokenPoolMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, caller common.Address, args common.Address) (bool, error) {
			return contract.OnlyOwner(c, opts, caller, args)
		},
		CallContract: func(
			c gobindings.TokenPoolInterface,
			opts *bind.TransactOpts,
			args common.Address,
		) (*types.Transaction, error) {
			return c.SetRouter(opts, args)
		},
	})
}

func NewReadGetSupportedChains(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[struct{}], []uint64, cldf_evm.Chain] {
	return contract.NewRead(contract.ReadParams[struct{}, []uint64, gobindings.TokenPoolInterface]{
		Name:         "token-pool:get-supported-chains",
		Version:      Version,
		Description:  "Calls getSupportedChains on the contract",
		ContractType: ContractType,
		Contract:     c,
		CallContract: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, args struct{}) ([]uint64, error) {
			return c.GetSupportedChains(opts)
		},
	})
}

func NewReadGetRemoteToken(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[uint64], []byte, cldf_evm.Chain] {
	return contract.NewRead(contract.ReadParams[uint64, []byte, gobindings.TokenPoolInterface]{
		Name:         "token-pool:get-remote-token",
		Version:      Version,
		Description:  "Calls getRemoteToken on the contract",
		ContractType: ContractType,
		Contract:     c,
		CallContract: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, args uint64) ([]byte, error) {
			return c.GetRemoteToken(opts, args)
		},
	})
}

func NewReadGetRemotePools(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[uint64], [][]byte, cldf_evm.Chain] {
	return contract.NewRead(contract.ReadParams[uint64, [][]byte, gobindings.TokenPoolInterface]{
		Name:         "token-pool:get-remote-pools",
		Version:      Version,
		Description:  "Calls getRemotePools on the contract",
		ContractType: ContractType,
		Contract:     c,
		CallContract: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, args uint64) ([][]byte, error) {
			return c.GetRemotePools(opts, args)
		},
	})
}

func NewWriteAddRemotePool(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[AddRemotePoolArgs], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[AddRemotePoolArgs, gobindings.TokenPoolInterface]{
		Name:         "token-pool:add-remote-pool",
		Version:      Version,
		Description:  "Calls addRemotePool on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.TokenPoolMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, caller common.Address, args AddRemotePoolArgs) (bool, error) {
			return contract.OnlyOwner(c, opts, caller, args)
		},
		CallContract: func(
			c gobindings.TokenPoolInterface,
			opts *bind.TransactOpts,
			args AddRemotePoolArgs,
		) (*types.Transaction, error) {
			return c.AddRemotePool(opts, args.RemoteChainSelector, args.RemotePoolAddress)
		},
	})
}

func NewWriteRemoveRemotePool(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[RemoveRemotePoolArgs], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[RemoveRemotePoolArgs, gobindings.TokenPoolInterface]{
		Name:         "token-pool:remove-remote-pool",
		Version:      Version,
		Description:  "Calls removeRemotePool on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.TokenPoolMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, caller common.Address, args RemoveRemotePoolArgs) (bool, error) {
			return contract.OnlyOwner(c, opts, caller, args)
		},
		CallContract: func(
			c gobindings.TokenPoolInterface,
			opts *bind.TransactOpts,
			args RemoveRemotePoolArgs,
		) (*types.Transaction, error) {
			return c.RemoveRemotePool(opts, args.RemoteChainSelector, args.RemotePoolAddress)
		},
	})
}

func NewReadGetCurrentInboundRateLimiterState(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[uint64], gobindings.RateLimiterTokenBucket, cldf_evm.Chain] {
	return contract.NewRead(contract.ReadParams[uint64, gobindings.RateLimiterTokenBucket, gobindings.TokenPoolInterface]{
		Name:         "token-pool:get-current-inbound-rate-limiter-state",
		Version:      Version,
		Description:  "Calls getCurrentInboundRateLimiterState on the contract",
		ContractType: ContractType,
		Contract:     c,
		CallContract: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, args uint64) (gobindings.RateLimiterTokenBucket, error) {
			return c.GetCurrentInboundRateLimiterState(opts, args)
		},
	})
}

func NewReadGetCurrentOutboundRateLimiterState(c gobindings.TokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[uint64], gobindings.RateLimiterTokenBucket, cldf_evm.Chain] {
	return contract.NewRead(contract.ReadParams[uint64, gobindings.RateLimiterTokenBucket, gobindings.TokenPoolInterface]{
		Name:         "token-pool:get-current-outbound-rate-limiter-state",
		Version:      Version,
		Description:  "Calls getCurrentOutboundRateLimiterState on the contract",
		ContractType: ContractType,
		Contract:     c,
		CallContract: func(c gobindings.TokenPoolInterface, opts *bind.CallOpts, args uint64) (gobindings.RateLimiterTokenBucket, error) {
			return c.GetCurrentOutboundRateLimiterState(opts, args)
		},
	})
}
