# Run go mod tidy
tidy:
    go mod tidy

clean:
    rm -rf compose/ blockscout/

# Remove all the chaos experiments
rm-chaos:
    kubectl delete networkchaos --all -A
    kubectl delete podchaos --all -A
    kubectl delete iochaos --all -A
    kubectl delete timechaos --all -A
    kubectl delete stresschaos --all -A
    kubectl delete dnschaos --all -A
    kubectl delete kernelchaos --all -A

# Format all go files
fmt:
    golangci-lint fmt --config=.golangci.yaml

# Run golangci-lint
lint:
    golangci-lint run --whole-files --output.text.path stdout --max-same-issues=0 --config=.golangci.yaml

# Install pre-commit hooks
pre-commit:
    pre-commit install

# Builds and installs new version of CLI locally
cli:
    go install cmd/ccip.go

# Build all the services (hot-reload dev mode)
build-all-docker-dev:
    cd fakes && docker build -t ccip-fakes:latest . || cd -
    cd indexer && docker build -f Dockerfile.dev -t indexer:dev . || cd -

# Build Indexer dev image
build-indexer-docker-dev:
    cd indexer && docker build -f Dockerfile.dev -t indexer:dev . || cd -

# Build Indexer production image
build-indexer-docker-prod:
    cd indexer && docker build -f Dockerfile -t indexer:dev . || cd -