{
 "title": "Beholder Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Available Metrics",
   "type": "table",
   "description": "These are all of the custom metrics added to the Beholder demo application. If a new one is added, it will appear here.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (__name__) ({exported_job=~\".*beholder.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "description": "These are custom logs coming from the Beholder demo app. Additional logs using the Beholder client logger should show up here.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=~\".*beholder.*\"} | beholder_data_type=~\".*zap.*\""
    }
   ]
  },
  { "title": "Metrics Created via OTel ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Custom Gauge",
   "type": "timeseries",
   "description": "This is a custom OTel gauge being sent from the Beholder demo app. Its values are randomly ranging from 0 to 100.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "active_connections", "legendFormat": "{{ __name__}}" }
   ]
  },
  {
   "title": "Custom Counter",
   "type": "timeseries",
   "description": "This is a custom OTel counter coming from the Beholder demo app. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "successful_requests_count_total",
     "legendFormat": "{{ __name__}}"
    }
   ]
  },
  { "title": "Metrics Created via Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Test Prom Counter",
   "type": "timeseries",
   "description": "A test counter. This is being set via Prometheus and scraped via the OTel collector.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    { "expr": "test_vector_counter_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Test Prom Gauge",
   "type": "timeseries",
   "description": "A test gauge. This is being set via Prometheus and scraped via the OTel collector.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    { "expr": "test_vector_gauge{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Test Prom Histogram",
   "type": "heatmap",
   "description": "A test histogram. This is being set via Prometheus and scraped via the OTel collector.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(test_vector_histogram_bucket{}[1m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tracing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Traces",
   "type": "table",
   "description": "The traces coming from the Beholder demo application.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "filters": [
      { "id": "be1ea03b", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{resource.service.name=~\".*beholderdemo\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}