apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  datasources.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://beholder-prometheus:9090
      - name: Loki
        type: loki
        access: proxy
        url: http://beholder-loki:3100
