with-expecter: true
filename: "{{.InterfaceName | snakecase}}.go"
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
resolve-type-alias: false
packages:
    github.com/smartcontractkit/chainlink-ccip/ocr3/commit/merkleroot:
        interfaces:
            Observer:
    github.com/smartcontractkit/chainlink-ccip/ocr3/internal/reader:
        interfaces:
            HomeChain:
    github.com/smartcontractkit/chainlink-ccip/ocr3/internal/plugincommon:
        interfaces:
            ChainSupport:
            PluginProcessor:
    github.com/smartcontractkit/chainlink-ccip/ocr3/commit/merkleroot/rmn:
        interfaces:
            Controller:
            Stream:
    github.com/smartcontractkit/chainlink-ccip/ocr3/pkg/reader:
        interfaces:
            CCIPReader:
            PriceReader:
            RMNHome:
    github.com/smartcontractkit/chainlink-ccip/ocr3/execute/internal/cache:
        interfaces:
            TimeProvider:
    github.com/smartcontractkit/chainlink-ccip/ocr3/pkg/ocrtypecodec/v1:
        interfaces:
            ExecCodec:
    github.com/smartcontractkit/chainlink-ccip/ocr3/pkg/contractreader:
        interfaces:
            Extended:
            ContractReaderFacade:
    github.com/smartcontractkit/chainlink-ccip/ocr3/pkg/types/ccipocr3:
        interfaces:
            ExecutePluginCodec:
            EstimateProvider:
            AddressCodec:
            CommitPluginCodec:
    github.com/smartcontractkit/chainlink-common/pkg/types:
        interfaces:
            ContractWriter:
                config:
                    dir: ocr3/mocks/chainlink_common/types/
    github.com/smartcontractkit/chainlink-common/pkg/types/ccipocr3:
        config:
            dir: ocr3/mocks/chainlink_common/ccipocr3/
        interfaces:
            ExecutePluginCodec:
            EstimateProvider:
            AddressCodec:
            CommitPluginCodec:
            ChainAccessor:
    github.com/smartcontractkit/libocr/networking:
        interfaces:
            PeerGroupFactory:
                config:
                    dir: ocr3/mocks/libocr_networking/
            PeerGroup:
                config:
                    dir: ocr3/mocks/libocr_networking/
