with-expecter: true
filename: "{{.InterfaceName | snakecase}}.go"
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
packages:
    github.com/smartcontractkit/chainlink-ccip/commit/merkleroot:
        interfaces:
            Observer:
    github.com/smartcontractkit/chainlink-ccip/internal/reader:
        interfaces:
            HomeChain:
            RMNRemote:
            CCIP:
    github.com/smartcontractkit/chainlink-ccip/internal/plugincommon:
        interfaces:
            ChainSupport:
            PluginProcessor:
    github.com/smartcontractkit/chainlink-ccip/commit/merkleroot/rmn:
        interfaces:
            Controller:
            Stream:
    github.com/smartcontractkit/chainlink-ccip/execute/internal/gas:
        interfaces:
            EstimateProvider:
    github.com/smartcontractkit/chainlink-ccip/pkg/reader:
        interfaces:
            CCIPReader:
            PriceReader:
            RMNHome:
    github.com/smartcontractkit/chainlink-ccip/pkg/contractreader:
        interfaces:
            Extended:
            ContractReaderFacade:
    github.com/smartcontractkit/chainlink-ccip/pkg/contractwriter:
        interfaces:
            ContractWriterFacade:
    github.com/smartcontractkit/chainlink-ccip/pkg/types/ccipocr3:
        interfaces:
            ExecutePluginCodec:
    github.com/smartcontractkit/libocr/networking:
        interfaces:
            PeerGroupFactory:
                config:
                    dir: mocks/libocr_networking/
            PeerGroup:
                config:
                    dir: mocks/libocr_networking/
