with-expecter: true
filename: "{{.InterfaceName | snakecase}}.go"
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
packages:
    github.com/smartcontractkit/chainlink-ccip/execute/types:
        interfaces:
            TokenDataReader:
    github.com/smartcontractkit/chainlink-ccip/execute/internal/gen:
        interfaces:
            ExecutePluginCodec:
    github.com/smartcontractkit/chainlink-ccip/internal/reader:
        interfaces:
            HomeChain:
