with-expecter: true
filename: "{{.InterfaceName | snakecase}}.go"
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
packages:
    github.com/smartcontractkit/chainlink-ccip/execute/exectypes:
        interfaces:
            TokenDataReader:
    github.com/smartcontractkit/chainlink-ccip/execute/internal/gen:
        interfaces:
            ExecutePluginCodec:
    github.com/smartcontractkit/chainlink-ccip/commit:
        interfaces:
            Observer:
            ChainSupport:
    github.com/smartcontractkit/chainlink-ccip/internal/reader:
        interfaces:
            HomeChain:
            CCIP:
            TokenPrices:
