with-expecter: true
filename: "{{.InterfaceName | snakecase}}.go"
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
packages:
    github.com/smartcontractkit/chainlink-ccip/execute/exectypes:
        interfaces:
            TokenDataReader:
    github.com/smartcontractkit/chainlink-ccip/execute/internal/gen:
        interfaces:
            ExecutePluginCodec:
    github.com/smartcontractkit/chainlink-ccip/commit/merkleroot:
        interfaces:
            Observer:
    github.com/smartcontractkit/chainlink-ccip/internal/reader:
        interfaces:
            HomeChain:
            RMNHome:
            RMNRemote:
            CCIP:
            PriceReader:
    github.com/smartcontractkit/chainlink-ccip/internal/reader/contractreader:
        interfaces:
            ContractReaderFacade:
    github.com/smartcontractkit/chainlink-ccip/internal/plugincommon:
        interfaces:
            ChainSupport:
            PluginProcessor:
    github.com/smartcontractkit/chainlink-ccip/commit/merkleroot/rmn:
        interfaces:
            Controller:
    github.com/smartcontractkit/chainlink-ccip/pkg/reader:
        interfaces:
            CCIPReader:
    github.com/smartcontractkit/chainlink-ccip/pkg/contractreader:
        interfaces:
            Extended:
