repos:
  - repo: local
    hooks:
      - id: solana-checks
        name: Run Solana checks
        entry: make -C ./chains/solana solana-checks
        language: system
        stages: [pre-commit]
        files: ^chains/solana/
        verbose: true
