---
extends: default
rules:
  new-line-at-end-of-file:
    level: warning
  line-length:
    max: 120
    level: warning
ignore:
  - 'templates'
  - 'node_modules'
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
  - '*.yaml.example'
