---
extends: default

ignore: |
  .tmp/
  node_modules/
  ./pnpm-lock.yaml
  templates

rules:
  new-line-at-end-of-file:
    level: warning
  line-length:
    max: 160
    level: warning
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
  - '*.yaml.example'
