---
version: '3'

tasks:
  lint:
    desc: Runs The same lint commands as in CI, doesn't fix errors
    deps: [lint-yaml, shfmt, shellcheck]
  fix-lint-errors:
    desc: Fixes lint errors, so far it supports shfmt fixes only
    deps: [fix-shfmt-errors]
  lint-yaml:
    cmd: yamllint -c .yamllint.yml .
  # todo: Add script for auto fixing lint errors
  shfmt:
    cmd: shfmt -s -d .
  shellcheck:
    cmd: git ls-files -- '*.sh' | xargs shellcheck -e SC1004
  fix-shfmt-errors:
    vars:
      SHELLCHECK_OPTS: -e SC1004
    cmd: find . -type f -name "*.sh" -exec shfmt -w {} \;

  build:
    desc: Builds the crib CLI
    env:
      GOPATH:
        sh: go env GOPATH
      GOBIN:
        sh: echo ${GOBIN:-$(go env GOPATH)/bin}
    cmd: go build -o $GOBIN/crib ./cli/.

  setup:
    desc: Sets up the crib CLI in the current environment
    deps: [build]
    vars:
      REPO_ROOT:
        sh: git rev-parse --show-toplevel
    cmd: crib init --write-config
