---
version: '3'

tasks:
  lint:
    desc: Runs The same lint commands as in CI, doesn't fix errors
    deps: [lint-yaml, shfmt, shellcheck]
  fix-lint-errors:
    desc: Fixes lint errors, so far it supports shfmt fixes only
    deps: [fix-shfmt-errors]
  lint-yaml:
    cmd: yamllint -c .yamllint.yml .
  # todo: Add script for auto fixing lint errors
  shfmt:
    cmd: shfmt -s -d .
  shellcheck:
    cmd: git ls-files -- '*.sh' | xargs shellcheck -e SC1004
  fix-shfmt-errors:
    vars:
      SHELLCHECK_OPTS: -e SC1004
    cmd: find . -type f -name "*.sh" -exec shfmt -w {} \;

  build:
    desc: Builds the crib CLI
    env:
      GOPATH:
        sh: go env GOPATH
      GOBIN:
        sh: echo ${GOBIN:-$(go env GOPATH)/bin}
    cmd: go build -o $GOBIN/crib ./cli/.

  fetch-cli:
    desc: Downloads the crib binary from the corresponding tag-based release in GitHub when applicable, otherwise uses latest
    env:
      GOPATH:
        sh: go env GOPATH
      GOBIN:
        sh: echo ${GOBIN:-$(go env GOPATH)/bin}
    cmd: |
      # if on a tagged ref, uses the corresponding release instead of latest
      CLI_RELEASE=$(git tag --points-at HEAD | tail -n 1)

      if [ -n "$CLI_RELEASE" ]; then
        echo "Fetching crib CLI binary from release $CLI_RELEASE"
      else
        echo "Fetching crib CLI binary from latest release"
      fi

      checksums=$(mktemp)
      gh release download $CLI_RELEASE --repo smartcontractkit/crib --pattern "checksums.txt" --clobber -O $checksums

      if [ -f $GOBIN/crib ]; then
        expected_checksum=$(grep "crib-{{OS}}-{{ARCH}}" "$checksums" | cut -d ' ' -f 1)
        actual_checksum=$(sha256sum $GOBIN/crib | cut -d ' ' -f 1)
        if [ "$expected_checksum" = "$actual_checksum" ]; then
          chmod +x $GOBIN/crib
          echo "Current crib binary is up to date"
          rm -f $checksums
          exit 0
        fi
      fi

      gh release download $CLI_RELEASE --repo smartcontractkit/crib --pattern "crib-{{OS}}-{{ARCH}}" --clobber -O $GOBIN/crib
      chmod +x $GOBIN/crib
      rm -f $checksums

  setup:
    desc: Sets up the crib CLI in the current environment
    dir: '{{.USER_WORKING_DIR}}'
    vars:
      REPO_ROOT:
        sh: git rev-parse --show-toplevel
    cmd: crib init --write-config
