build:
    docker build -f Dockerfile -t aggregator:latest .

build-dev:
    docker build -f Dockerfile.dev -t aggregator:dev .

clean:
    docker rmi aggregator:latest

clean-dev:
    docker rmi aggregator:dev
