// Code generated by https://github.com/Unheilbar/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package test_ccip_invalid_receiver

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("FmyF3oW69MSAhyPSiZ69C4RKBdCPv5vAFTScisV7Me2j")
