apiVersion: batch/v1
kind: Job
metadata:
  name: register-schema-job
  labels:
    app: redpanda
spec:
  template:
    spec:
      containers:
        - name: schema-registrar
          image: curlimages/curl:latest
          command: ["sh", "-c", "--"]
          args:
            - |
              SCHEMA_CONTENT=$(cat /schemas/example.proto) && \
              curl -X POST http://redpanda:8081/subjects/beholder__beholderdemo__messages___TestCustomMessage/versions \
                   -H "Content-Type: application/vnd.schemaregistry.v1+json" \
                   -d "{\"schema\": $SCHEMA_CONTENT, \"schemaType\": \"PROTOBUF\"}"
              curl -X POST http://redpanda:8081/subjects/beholder__test_domain__messages___test_entity/versions \
                   -H "Content-Type: application/vnd.schemaregistry.v1+json" \
                   -d "{\"schema\": $SCHEMA_CONTENT, \"schemaType\": \"PROTOBUF\"}"
              curl -X POST http://redpanda:8081/subjects/beholder__load_test__messages___load_test/versions \
                   -H "Content-Type: application/vnd.schemaregistry.v1+json" \
                   -d "{\"schema\": $SCHEMA_CONTENT, \"schemaType\": \"PROTOBUF\"}"

          volumeMounts:
            - name: schema-volume
              mountPath: /schemas
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
      restartPolicy: Never
      volumes:
        - name: schema-volume
          configMap:
            name: schema-config
  backoffLimit: 4
