// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package ccip_common

// Account discriminators
var ()

// Event discriminators
var ()

// Instruction discriminators
var ()
