---
version: v2beta1
name: chainlink-don

require:
  devspace: '>= 6.0'

vars:
  # helm
  CHAINLINK_HELM_REGISTRY_URI:
    source: env
    default: "oci://804282218731.dkr.ecr.us-west-2.amazonaws.com/infra-charts"
  # local
  LOCAL_CHARTS_DIR:
    source: env
    default: "${CHAINLINK_CODE_DIR}/infra-charts"
  LOCAL_TEMPLATES_DIR:
    source: env
    default: ./templates
  LOCAL_VALUES_DIR:
    source: env
    default: ./values
  LOCAL_SCRIPTS_DIR:
    source: env
    default: ./scripts
  # Infrastructure Provider, either kind or aws
  PROVIDER:
    source: env
    default: ""
  # Version of CCIP tooling
  CCIP_TOOLING_VERSION:
    source: env
    default: ""
  # Dir where CRIB will save env details, persisted between devspace pipeline reruns
  TMP_DIR:
    source: env
  SCRIPTS_DIR:
    source: env
  # don
  DON_TYPE:
    source: env
    default: dev
  DON_VERSION:
    source: env
    default: latest
  DON_BOOT_NODE_COUNT:
    source: env
    default: 0
  DON_NODE_COUNT:
    source: env
    default: 1
  # chains
  # Option to generate variable number of networks to be configured in Node config
  ADDITIONAL_CHAINS_COUNT:
    source: env
    default: 0
  # switch
  ENABLE_DON_BASE:
    source: env
    default: "true"

pipelines:
  deploy:
    flags:
      # Determine if it should deply infra-only without onchain deployment
      - name: infraOnly
        type: bool
        default: false
    run: |-
      if [[ "$PROVIDER" == "kind" ]]; then
       ensure_pull_secrets --all
      fi

      create_deployments --all

      if [[ "$CCIP_TOOLING_VERSION" == "v2" ]]; then
        echo "Deploying dependencies for CCIP v2 Tooling"

        run_dependency_pipelines job-distributor

        if [ $(get_flag "infraOnly") == "false" ]; then
          # deploy-home-chain-contracts pipeline write 2 files to temp dir
          #   - ccip-v2-scripts-node-overrides.toml
          #   - ccip-v2-scripts-address-book.json
          run_dependency_pipelines ccip-v2-scripts-deploy-home-chain

          NODE_TOML_OVERRIDES=$(cat ${TMP_DIR}/ccip-v2-scripts-node-overrides.toml) \
            gomplate --config ${LOCAL_TEMPLATES_DIR}/ccip-v2-scripts-overrides.yaml > ${TMP_DIR}/ccip-v2-node-overrides.yaml
          create_deployments chainlink-don --from-file="${TMP_DIR}/ccip-v2-node-overrides.yaml"

          # deploy on chain contracts (tokens, lanes, token pools, price registry, router)
          run_dependency_pipelines ccip-v2-scripts-deploy-ccip
        else
          echo "infraOnly=true, skipping on chain deployments and node orchestration"
        fi
      fi
deployments:
  chainlink-don:
    updateImageTags: false
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      displayOutput: true
      chart:
        name: ${CHAINLINK_HELM_REGISTRY_URI}/chainlink-cluster
        version: "2.4.4"
      valuesFiles: []
      values: {}
hooks:
  # This hook will ensure that every time the deployment
  # chainlink-don is deployed that DevSpace will wait until
  # all pods and containers that match the labelSelector
  # app.kubernetes.io/name: chainlink-don are running
  # https://www.devspace.sh/docs/configuration/hooks/#wait-for-a-pod-to-be-running
  - wait:
      running: true
      # This can be needed for init containers
      # that terminate instead of become running.
      terminatedWithCode: 0
    container:
      labelSelector:
        "app.kubernetes.io/name": "chainlink-don"
    name: "wait-for-chainlink-don-pods"
    events: ["after:deploy:chainlink-don"]
  - name: Wait for ingress hosts
    events: ["after:deploy:chainlink-don"]
    command: crib
    args: ["devspace", "ingress-check"]
profiles:
  # charts
  - name: local-charts
    merge:
      deployments:
        chainlink-don:
          helm:
            chart:
              name: chainlink-cluster
              path: ${LOCAL_CHARTS_DIR}/chainlink-cluster
              version: null
  # base
  - name: don-base-tmpl
    activation: &enableDonBase
      - vars:
          ENABLE_DON_BASE: "true"
    merge: |-
      $(
        DON_NODE_COUNT=${DON_NODE_COUNT} \
        DON_BOOT_NODE_COUNT=${DON_BOOT_NODE_COUNT} \
        PROVIDER=${PROVIDER} \
        gomplate \
          --config ${LOCAL_TEMPLATES_DIR}/chainlink-don.base.yaml
      )
  - name: don-base-type
    activation: *enableDonBase
    patches:
      - op: add
        path: deployments.chainlink-don.helm.valuesFiles
        value: ${LOCAL_VALUES_DIR}/chainlink-cluster/type.${DON_TYPE}.yaml
  - name: don-base-version
    activation: *enableDonBase
    patches:
      - op: add
        path: deployments.chainlink-don.helm.valuesFiles
        value: ${LOCAL_VALUES_DIR}/chainlink-cluster/version.${DON_VERSION}.yaml
  # networks
  - name: network-arbitrum-sepolia
    patches:
      - op: add
        path: deployments.chainlink-don.helm.valuesFiles
        value: ${LOCAL_VALUES_DIR}/chainlink-cluster/network.arbitrum-sepolia.yaml
  - name: network-ethereum-sepolia
    patches:
      - op: add
        path: deployments.chainlink-don.helm.valuesFiles
        value: ${LOCAL_VALUES_DIR}/chainlink-cluster/network.ethereum-sepolia.yaml
  - name: network-geth-chain-1337
    patches:
      - op: add
        path: deployments.chainlink-don.helm.valuesFiles
        value: ${LOCAL_VALUES_DIR}/chainlink-cluster/network.geth-chain-1337.yaml
  - name: network-geth-chain-2337
    patches:
      - op: add
        path: deployments.chainlink-don.helm.valuesFiles
        value: ${LOCAL_VALUES_DIR}/chainlink-cluster/network.geth-chain-2337.yaml
  - name: network-besu-chain-alpha
    patches:
      - op: add
        path: deployments.chainlink-don.helm.valuesFiles
        value: ${LOCAL_VALUES_DIR}/chainlink-cluster/network.besu-chain-alpha.yaml
  - name: network-besu-chain-beta
    patches:
      - op: add
        path: deployments.chainlink-don.helm.valuesFiles
        value: ${LOCAL_VALUES_DIR}/chainlink-cluster/network.besu-chain-beta.yaml
  - name: network-ava-spruce-calm
    patches:
      - op: add
        path: deployments.chainlink-don.helm.valuesFiles
        value: ${LOCAL_VALUES_DIR}/chainlink-cluster/network.ava-spruce-calm.yaml
  # to support load testing scenarios, the profile generate variable number of chain configs
  - name: network-additional-geth-chains
    merge: |-
      $(
        ADDITIONAL_CHAINS_COUNT=${ADDITIONAL_CHAINS_COUNT} \
        gomplate \
          --config ${LOCAL_TEMPLATES_DIR}/network.geth-n-chains.yaml
      )
  - name: network-generated
    merge: |-
      $(
        SCRIPT_DIR=./scripts/ccip_load_tests_config \
        go run ./scripts/ccip_load_tests_config/main.go
      )
  # versions
  - name: version-latest
    patches:
      - op: add
        path: deployments.chainlink-don.helm.valuesFiles
        value: ${LOCAL_VALUES_DIR}/chainlink-cluster/version.latest.yaml
  - name: version-local
    patches:
      - op: add
        path: deployments.chainlink-don.helm.valuesFiles
        value: ${LOCAL_VALUES_DIR}/chainlink-cluster/version.k3d-local.yaml
  - name: version-from-env
    merge:
      deployments:
        chainlink-don:
          helm:
            values:
              common:
                image:
                  repository: ${DEVSPACE_IMAGE}
                  tag: ${DEVSPACE_IMAGE_TAG}
                  pullPolicy: Always
  # overrides
  - name: overrides
    patches:
      - op: add
        path: deployments.chainlink-don.helm.valuesFiles
        value: ${LOCAL_VALUES_DIR}/chainlink-cluster/overrides.yaml
  - name: crib-staging
    activation:
      - vars:
          PROVIDER: "aws"
    merge: |-
      $(
        DEVSPACE_NAMESPACE=${DEVSPACE_NAMESPACE} \
        gomplate \
          --config ${LOCAL_TEMPLATES_DIR}/chainlink-don.env.crib-staging.yaml
      )
  - name: crib-kind
    activation:
      - vars:
          PROVIDER: "kind"
    merge: |-
      $(
        DEVSPACE_NAMESPACE=${DEVSPACE_NAMESPACE} \
        gomplate \
          --config ${LOCAL_TEMPLATES_DIR}/chainlink-don.env.crib-kind.yaml
      )
  - name: ccip-v2-scripts
    activation:
      - vars:
          CCIP_TOOLING_VERSION: "v2"
    patches:
      - op: add
        path: dependencies
        value:
          ccip-v2-scripts-deploy-home-chain:
            path: ${DEPENDENCIES_DIR}/ccip-v2-scripts/devspace.yaml
            overwriteVars: true
            pipeline: deploy-home-chain-contracts
            namespace: ${DEVSPACE_NAMESPACE}
          ccip-v2-scripts-deploy-ccip:
            path: ${DEPENDENCIES_DIR}/ccip-v2-scripts/devspace.yaml
            overwriteVars: true
            pipeline: deploy-ccip
            namespace: ${DEVSPACE_NAMESPACE}
          job-distributor:
            path: ${DEPENDENCIES_DIR}/job-distributor
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
  - name: git-charts
    merge:
      deployments:
        chainlink-don:
          helm:
            chart:
              git: https://github.com/smartcontractkit/infra-charts
              subPath: chainlink-cluster
              revision: a1928889c2b94f5e8e0849dee7727480d6b49cce
