---
version: v2beta1

vars:
  # Image URI required for deploying CCIP UI
  DEVSPACE_CCIP_UI_IMAGE_REPOSITORY:
    source: env
    default: "804282218731.dkr.ecr.us-west-2.amazonaws.com/ccip-ui"
  DEVSPACE_CCIP_UI_IMAGE_TAG:
    source: env
    default: crib

dependencies:
  atlas:
    path: ${IMPORTS_DIR}/atlas/atlas.yaml
    pipeline: atlas
    namespace: ${DEVSPACE_NAMESPACE}

pipelines:
  ccip-ui:
    run: |-
      create_deployments ccip-ui-infra

deployments:
  ccip-ui-infra:
    updateImageTags: false
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      upgradeArgs: ["--timeout", "10m"]
      displayOutput: true
      chart:
        name: ${CHAINLINK_HELM_REGISTRY_URI}/generic-app
        version: "1.1.26"
      values:
        name: ccip-ui
        replicas: 1
        image:
          repository: ${DEVSPACE_CCIP_UI_IMAGE_REPOSITORY}
          tag: ${DEVSPACE_CCIP_UI_IMAGE_TAG}
          pullPolicy: Always
        args: []
        envVars:
          NEXT_PUBLIC_CCIP_LOCAL_NETWORK_1_NAME: ${NETWORK_1}
          NEXT_PUBLIC_CCIP_LOCAL_NETWORK_1_CHAIN_ID: "${NETWORK_1_CHAINID}"
          NEXT_PUBLIC_CCIP_LOCAL_NETWORK_1_RPC_URL: ${NETWORK_1_RPC}
          NEXT_PUBLIC_CCIP_LOCAL_NETWORK_1_CHAIN_SELECTOR: "3379446385462418246" # from https://github.com/smartcontractkit/chain-selectors/blob/e25527c097e7d7be17791c814704b3c0894c17bf/selectors.yml#L73-L75
          NEXT_PUBLIC_CCIP_LOCAL_NETWORK_2_NAME: ${NETWORK_2}
          NEXT_PUBLIC_CCIP_LOCAL_NETWORK_2_CHAIN_ID: "${NETWORK_2_CHAINID}"
          NEXT_PUBLIC_CCIP_LOCAL_NETWORK_2_RPC_URL: ${NETWORK_2_RPC}
          NEXT_PUBLIC_CCIP_LOCAL_NETWORK_2_CHAIN_SELECTOR: "12922642891491394802" # from https://github.com/smartcontractkit/chain-selectors/blob/e25527c097e7d7be17791c814704b3c0894c17bf/test_selectors.yml#L5-L7
          NEXT_PRIVATE_CL_ONCHAIN_DATA_V2_URL: http://atlas-postgraphile.${DEVSPACE_NAMESPACE}.svc.cluster.local:5000/graphql
          NEXT_PUBLIC_CL_ONCHAIN_DATA_V2_URL: http://atlas-postgraphile.${DEVSPACE_NAMESPACE}.svc.cluster.local:5000/graphql
          NEXT_PUBLIC_CL_NODE_ENV: crib
          NEXT_PRIVATE_CL_SUPABASE_URL: ""
          NEXT_PRIVATE_CL_SUPABASE_KEY: ""
          NEXT_PUBLIC_CL_WALLET_CONNECT_PROJECT_ID: ""
          NEXT_PRIVATE_CL_ONCHAIN_DATA_V2_API_KEY: ""
        podSecurityContext:
          runAsUser: 1001
          runAsGroup: 1001
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1001
        service:
          port: 3000
        startupProbe:
          httpGet:
            path: /api/health
            port: http
          failureThreshold: 5
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          failureThreshold: 3
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          failureThreshold: 2
          periodSeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi

profiles:
  - name: ccip-ui-ingress
    activation:
      - vars:
          CCIP_UI_ENABLED: true
    patches:
      - op: add
        path: deployments.app.helm.values.crib-chainlink-cluster.ingress.hosts
        value:
          host: ${DEVSPACE_NAMESPACE}-ccip-ui.${DEVSPACE_INGRESS_BASE_DOMAIN}
          http:
            paths:
              - path: /
                backend:
                  service:
                    name: ccip-ui
                    port:
                      number: 3000
