---
version: v2beta1
name: geth

vars:
  LOCAL_TEMPLATES_DIR:
    source: env
    default: ./templates
  LOCAL_VALUES_DIR:
    source: env
    default: ./values
  # Product can be chainlink or ccip. Based on the chosen profile it will activate specific mutations
  CHAINLINK_PRODUCT:
    source: env
    default: "chainlink"
  # Use this to activate patches specific to your use case, for example ccip-load-tests
  USE_CASE:
    source: env
    default: "default"
  # This is just a hack to always enable the profile
  ENABLE_BASE_PROFILE:
    source: env
    default: true
  # Use chain overrides to override configuration for individual chains
  # Useful for load testing
  CHAIN_OVERRIDES_FILENAME:
    source: env
    default: default.yaml
  # How many blockchain networks should it deploy
  # By default it will create beta (1337) and alpha (2337) chains, the minimum number is 1
  CHAINS_COUNT:
    source: env
    default: 2
  CHAIN_ID:
    source: env
    default: 1337
  BLOCK_TIME:
    source: env
    default: 2
  GENSIS_BALANCE:
    source: env
    default: 115792089237316195423570985008687907853269984665640564039457584007913129639935

pipelines:
  maybe-kind:
    run: |-
      if [ "$PROVIDER" == "kind" ]; then
        ensure_pull_secrets --all
      fi
  deploy:
    run: |-
      run_pipelines maybe-kind
      create_deployments --all
hooks:
  - wait:
      running: true
      terminatedWithCode: 0
      timeout: 600
    container:
      labelSelector:
        # vars don't work here, = releaseName
        release: "geth"
    events: ["after:deploy:geth"]

# The list of deployments is generated from the template
profiles:
  - name: base
    activation:
      - vars:
          ENABLE_BASE_PROFILE: "true"
    merge: |-
      $(
        pushd ./scripts/generate_values > /dev/null
        go run main.go \
          -chain-overrides-file="${CHAIN_OVERRIDES_FILENAME}" \
          -chains-count="${CHAINS_COUNT}" -provider="${PROVIDER}" \
          -product="${CHAINLINK_PRODUCT}" -use-case="${USE_CASE}"
      )
  - name: local-charts
    merge: |-
      $(
        if [ "${CHAINS_COUNT}" -gt 0 ]; then
          pushd ./scripts/generate_values > /dev/null
          go run main.go -chains-count="${CHAINS_COUNT}" -provider="${PROVIDER}" \
            -template="local-charts.yaml.tmpl"
        else
          echo "deployments:"
        fi
      )
  - name: custom-chain
    activation:
      - vars:
          ENABLE_CUSTOM_CHAIN: "true"
    merge: |-
      $(
        DEVSPACE_NAMESPACE=${DEVSPACE_NAMESPACE} \
        DEVSPACE_INGRESS_BASE_DOMAIN=${DEVSPACE_INGRESS_BASE_DOMAIN} \
        CHAINLINK_HELM_REGISTRY_URI=${CHAINLINK_HELM_REGISTRY_URI} \
        gomplate \
          --config ${LOCAL_TEMPLATES_DIR}/minimal.yaml.tmpl \
          --context 'Chains=[{\"NetworkId\":\"your_network_id\"}]'
      )