---
version: v2beta1
name: chainlink-daas
require:
  devspace: ">= 6.0"
vars:
  DEVSPACE_ENV_FILE:
    source: env
    default: .env
  CHAINLINK_HELM_REGISTRY_URI:
    source: env
    default: "oci://804282218731.dkr.ecr.us-west-2.amazonaws.com/infra-charts"
pullSecrets:
  regcred-prod:
    registry: 804282218731.dkr.ecr.us-west-2.amazonaws.com
    secret: regcred-prod
pipelines:
  deploy:
    run: |-
      create_deployments chainlink-daas-operator
      # create_deployments chainlink-daas-api
  purge:
    run: |-
      # purge_deployments chainlink-daas-api
      purge_deployments chainlink-daas-operator
deployments:
  chainlink-daas-operator:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: ${CHAINLINK_HELM_REGISTRY_URI}/daas-operator
        version: 0.1.0
      values:
        image: {}
        imagePullSecrets: []
  chainlink-daas-api:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: ${CHAINLINK_HELM_REGISTRY_URI}/daas-operator-resources
        version: 0.0.1
      values:
        dapi:
          enabled: true
profiles:
  - name: use-prod-registry
    patches:
      - op: replace
        path: deployments.chainlink-daas-operator.helm.values.imagePullSecrets
        value:
          - name: regcred-prod
      - op: replace
        path: deployments.chainlink-daas-operator.helm.values.image
        value:
          repository: 804282218731.dkr.ecr.us-west-2.amazonaws.com/daas
          pullPolicy: Always
          tag: 0.0.6
  - name: use-local-registry
    patches:
      - op: replace
        path: deployments.chainlink-daas-operator.helm.values.image
        value:
          repository: localhost:5001/daas
          pullPolicy: Always
          tag: local
