---
version: v2beta1
name: chainlink-daas-operator

require:
  devspace: ">= 6.0"

vars:
  # default
  DEVSPACE_ENV_FILE:
    source: env
    default: .env
  # switches / activation
  ENV: # options=[local|stage|prod]
    source: env
    default: prod
  PROVIDER: # options=[kind|aws]
    source: all
    default: aws
  REGISTRY: # options=[localhost|aws]
    source: env
    default: prod
  # specific
  CHAINLINK_HELM_REGISTRY_URI:
    source: env
    default: "oci://804282218731.dkr.ecr.us-west-2.amazonaws.com/infra-charts"

pullSecrets:
  regcred-prod:
    registry: 804282218731.dkr.ecr.us-west-2.amazonaws.com
    secret: regcred-prod

pipelines:
  deploy:
    run: |-
      create_deployments daas-operator
  purge:
    run: |-
      purge_deployments daas-operator

deployments:
  daas-operator:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: ${CHAINLINK_HELM_REGISTRY_URI}/daas-operator
        version: 0.1.1
      values:
        image: {}
        imagePullSecrets: []

profiles:
  ###########################
  ## image registry options
  ###########################

  - name: use-aws-registry
    activation: # match all
      - vars:
          PROVIDER: aws
          REGISTRY: aws
    patches:
      - op: replace
        path: deployments.daas-operator.helm.values.image
        value:
          repository: 804282218731.dkr.ecr.us-west-2.amazonaws.com/daas
          pullPolicy: Always
          tag: 0.0.7

  - name: use-aws-registry-on-local
    activation: # match all
      - vars:
          ENV: local
          REGISTRY: aws
    patches:
      - op: replace
        path: deployments.daas-operator.helm.values.imagePullSecrets
        value:
          - name: regcred-prod
      - op: replace
        path: deployments.daas-operator.helm.values.image
        value:
          repository: 804282218731.dkr.ecr.us-west-2.amazonaws.com/daas
          pullPolicy: Always
          tag: 0.0.7

  - name: use-localhost-registry
    activation: # match all
      - vars:
          ENV: local
          REGISTRY: localhost
    patches:
      - op: replace
        path: deployments.daas-operator.helm.values.image
        value:
          repository: localhost:5001/daas
          pullPolicy: Always
          tag: local

hooks:
  - wait:
      running: true
      terminatedWithCode: 0
      timeout: 600
    container:
      labelSelector:
        app.kubernetes.io/instance: daas-operator
        app.kubernetes.io/name: daas-operator
    events: ["after:deploy:daas-operator"]
