---
version: v2beta1
name: chainlink-daas-operator-resources

require:
  devspace: ">= 6.0"

vars:
  # default
  DEVSPACE_ENV_FILE:
    source: env
    default: .env
  # switches / activation
  ENV: # options=[local|stage|prod]
    source: env
    default: prod
  PROVIDER: # options=[kind|aws]
    source: all
    default: aws
  REGISTRY: # options=[localhost|aws]
    source: env
    default: prod
  # specific
  CHAINLINK_HELM_REGISTRY_URI:
    source: env
    default: "oci://804282218731.dkr.ecr.us-west-2.amazonaws.com/infra-charts"
  HOST_NAME:
    source: env
    default: main.stage.cldev.sh
  AWS_ACM_CERT_ARN:
    source: env
    default: ""

pullSecrets:
  regcred-prod:
    registry: 804282218731.dkr.ecr.us-west-2.amazonaws.com
    secret: regcred-prod

pipelines:
  deploy:
    run: |-
      create_deployments daas-operator-resources
  purge:
    run: |-
      purge_deployments daas-operator-resources

deployments:
  daas-operator-resources:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: ${CHAINLINK_HELM_REGISTRY_URI}/daas-operator-resources
        version: 0.0.2
      values:
        dapi:
          enabled: true
          image: {}
          imagePullSecrets: []
        extraManifests: []
      upgradeArgs: ["--no-hooks"]
      templateArgs: ["--no-hooks"]

profiles:
  ###########################
  ## image registry options
  ###########################

  - name: use-aws-registry
    activation: # match all
      - vars:
          PROVIDER: aws
          REGISTRY: aws
    patches:
      - op: replace
        path: deployments.daas-operator-resources.helm.values.dapi.image
        value:
          repository: 804282218731.dkr.ecr.us-west-2.amazonaws.com/daas
          pullPolicy: Always
          tag: 0.0.7

  - name: use-aws-registry-on-local
    activation: # match all
      - vars:
          ENV: local
          REGISTRY: aws
    patches:
      - op: replace
        path: deployments.daas-operator-resources.helm.values.dapi.imagePullSecrets
        value:
          - name: regcred-prod
      - op: replace
        path: deployments.daas-operator-resources.helm.values.dapi.image
        value:
          repository: 804282218731.dkr.ecr.us-west-2.amazonaws.com/daas
          pullPolicy: Always
          tag: 0.0.7

  - name: use-localhost-registry
    activation: # match all
      - vars:
          ENV: local
          REGISTRY: localhost
    patches:
      - op: replace
        path: deployments.daas-operator-resources.helm.values.dapi.image
        value:
          repository: localhost:5001/daas
          pullPolicy: Always
          tag: local

  ###########################
  ## ingress options
  ###########################

  - name: ingress-local
    activation:
      - vars:
          ENV: local
    patches:
      - op: add
        path: deployments.daas-operator-resources.helm.values.extraManifests
        value:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: dapi
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: HTTP
              nginx.ingress.kubernetes.io/use-regex: "true"
          spec:
            ingressClassName: nginx
            rules:
              - host: dapi.${HOST_NAME}
                http:
                  paths:
                    - backend:
                        service:
                          name: daas-operator-resources-dapi
                          port:
                            number: 8888
                      path: /
                      pathType: Prefix
