---
# charts: https://github.com/minio/operator/tree/master/helm
version: v2beta1
name: cluster-services-minio-operator

require:
  devspace: ">= 6.0"

vars:
  DEVSPACE_ENV_FILE:
    source: env
    default: .env
  NAMESPACE:
    source: env
    default: ${DEVSPACE_NAMESPACE}

pipelines:
  deploy:
    run: |-
      create_deployments minio-operator
  purge:
    run: |-
      purge_deployments minio-operator

deployments:
  minio-operator:
    namespace: ${NAMESPACE}
    helm:
      chart:
        name: operator
        repo: https://operator.min.io
        version: 7.0.0
      values:
        crds:
          enabled: true

profiles: []

hooks:
  - wait:
      running: true
      terminatedWithCode: 0
      timeout: 600
    container:
      labelSelector:
        app.kubernetes.io/instance: minio-operator
        app.kubernetes.io/name: operator
    events: ["after:deploy:minio-operator"]
