---
# charts: https://github.com/ajgrande924/registry/tree/main/console
version: v2beta1
name: cluster-services-console

require:
  devspace: ">= 6.0"

vars:
  # default
  DEVSPACE_ENV_FILE:
    source: env
    default: .env
  # switches / activation
  ENV: # options=[local|stage|prod]
    source: env
    default: prod
  PROVIDER: # options=[kind|aws]
    source: all
    default: aws
  # specific
  HOST_NAME:
    source: env
    default: main.stage.cldev.sh
  AWS_ACM_CERT_ARN:
    source: env
    default: ""

pipelines:
  deploy:
    run: |-
      create_deployments console
  purge:
    run: |-
      purge_deployments console

deployments:
  console:
    helm:
      chart:
        name: oci://ghcr.io/ajgrande924/registry/console
        version: 0.1.0
      values:
        image:
          repository: quay.io/openshift/origin-console
          tag: latest
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
        ingress:
          enabled: true
          className: nginx-internal
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: HTTP
            external-dns.alpha.kubernetes.io/ttl: "120"
          hosts:
            - host: ${DEVSPACE_NAMESPACE}-console.${HOST_NAME}
              paths:
                - path: /
                  pathType: Prefix

profiles: []
