---
# chart: https://github.com/loft-sh/vcluster/tree/main/chart
version: v2beta1
name: vcluster-daas
require:
  devspace: ">= 6.0"
vars:
  DEVSPACE_ENV_FILE:
    source: env
    default: .env
pipelines:
  deploy:
    run: |-
      create_deployments vcluster-daas
  purge:
    run: |-
      purge_deployments vcluster-daas
      kubectl delete pvc data-vcluster-daas-0 --ignore-not-found
deployments:
  vcluster-daas:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: vcluster
        repo: https://charts.loft.sh
      values:
        controlPlane:
          distro:
            k8s:
              enabled: true
              securityContext:
                runAsUser: 12345
                runAsNonRoot: true
          statefulSet:
            security:
              podSecurityContext:
                fsGroup: 12345
              containerSecurityContext:
                runAsUser: 12345
                runAsNonRoot: true
          advanced:
            serviceAccount:
              enabled: true
        rbac:
          role:
            enabled: true
        sync:
          toHost:
            configMaps:
              enabled: true
            pods:
              enabled: true
            secrets:
              enabled: true
            services:
              enabled: true
            serviceAccounts:
              enabled: false
        experimental:
          deploy:
            vcluster:
              helm:
                - bundle: H4sIFAAAAAAA/ykAK2FIUjBjSE02THk5NWIzVjBkUzVpWlM5Nk9WVjZNV2xqYW5keVRRbz1IZWxtAOxde5PbOHLfv/kpejW5OtsJqcc8o8pdauJxLs6uvVOejbdSvi0bIlsS1iBAA6DG8sj57CkAfEscyTOy/DjhjzEFgN2NRqPxw6PpiBDliwQl0UJ2H0+J1MGcxOyHLaZer9c7OTqy//Z6vea/vcHg6If+0elx73hwfHx6+EOvf3h6dPwD9LYpRFtKlSbyh969eTUb940kktCXKBUVfAizgUeSpPjZC/pBz4tQhZIm2madw38hiyE0ZgJjIUFPES4IuYJfMhMCweGndISSo0blcRLjEGpG5ul5gkMgScJoSAxdb1Zn+aV18o+U6uN/RliKatsOYM347w+OBo3xfzToHe3H/y6S7/ueRDsUH4uU6yH0PY/GZIJDD0BiIhTVQs6HcNY7GpwNBv2z08N+EL2VAYYySJV/jUr7g4DE5IPg5FoFoYi7xqw8gCRl7FIwGs6H8HT8XOhLiQq59gA0mQyBp4xl7C5Txq4wlKjVEF79bj3HLzOUkkY4hE7HG6eMLWV6CuWMhngehlZ6DyCUSDQOQcsUPQDCudDWzagh3Hz0AA4A36qGvFIw9InkQ+j8W/781w4cgMR3KZUYWW9HrhUoFXsAzq8ZARIRnTdYmLwrDFNJ9fyx4Brfa5evGplGPMbE9aWkM8pwgk9USBhxvnZMmDINkCk/V88FfyGELlplM/9HoRzCyfHx4SDP+psUaVLmhSQhI8qopqgMN4BIisQ9AfiGu+dJVCKVoavBaEx1VjdM0iH0e73Y/ooxtnbQH5w9o9Y23qWoNqnrIZ+9JNL1q8dFhFfIMNRCOrVowYz/cfozVch4TDnVc1v8pUfI953q/l9jnDCiUXVfT5ElKFWgk3tPBWv8/+HRSdP/nxwene79/y7SzU33kffkfUJ4ZMGccWwgxvbZwrzAe9T9+NG7ufEhwjHlCJ2azQTmjQ74ZR2SMg2BW0o8N+SClw5WVL03LIwr4yGcHNpHGl+l4zF9Dx2/Axkt5JF59KyMj61bB1JwMPPBHN6lhNExxcgASit94P2Gjratrw0H0xIFIwxJqhCUiLECUl2bxxRZpIBIdD4QI9AC9JQqeDCaO6D7/MrUpXwCKsHwYeA9HYNEhkRligsF14RylSFkm0c1XFPGYISQKiOnAmKFz6Rdo9582itVTMeFRptzYq651vJNtM5UQeefbAuGf9m8W0sZC104IsELpyj3bi5nLfMThUsk5XoMnT8p/0+q06DlmG5uZKsfa6ZX6VMzWrJFi+lP26+ZkbhajIyQre1bW7fs2GaDqrp2z9naDBYGmTESInT+uQOd151PH04ijgV3cqp1crpaTtApsjhQ066VfQg3N0B5yNKorXGBY99WS2VI4OeMRVCxoKzR58Wa1JSRJAneFmM3oKJbrB5vbla8soB3qdDYUMIylZhwMsHIH80dodyarhzAXKnEHMZsqMZmW/2Vgjho2a4x5wyC1a2gXGnCQ6y3oTrkVll20/FnoBqIQ9XGEaYK1zevCsWft/mserXAwXVoTB8PWhpfesPgYRtFXm1txV/ktDvZQ2cjAks+4UvP2NtNbfgvwoSJeYx8C9uBa/Df0WHvpIH/Tnsne/y3k1Td/yNJorqzvveW8mgIF4UFeDFqEhFNhsXKt909VUaoGS2Q+Ua3SrSuYPV7rJgAFsApj5BrODIUDNTK9iIYDYlyri0budWtC8cud7KOYUx0OP25IsGtMixPRqUsJ458PkIy8hXF5LSvqZ4W8tV3BxwJk6q7ElmWe1uL/yUxq3E+K1+ruCGXwWpNu3PjCha5slc2prlPU4qxtINznzYtzyO32duqWSeoElvaclkWrOysxrbNaokzZIuy0k6/HBhV3Fa8c6ssLfKoVmH6gzplt2EHncrIsFlBuYEHHz8Ol4o1mcCiCe5reKvT5HJZ2dJbolfu99XlO4BQxDHh0bCWadTWrR8OlMVETlRdRT6sqGayjQvXjTzfZ0gilL41e6+u6JpZZ7tTdYmRz9r755aeWLJmk2o7bLd2eVHzFhaMzpCjUpdSjLBOcap18jdsWBZAQvR0CN0pEqanH5qFwuD4s95Zv1ZAOdWUsAtkZH6FoeCRGkL/uFYnQUntmHGlg16tzSSidxLTvDm/j5S3CtmvCjkTLI3xmfEcqimND7HJv3RC6ThplOdTYVniqK1wCvWXMU70/ILKbDsaVtlkdZO07P3a1ul9XOwSv3zHtTJD5XuwW+VT2eota1X3f+/G7UujqG83teF/OSJhUPWgVPC7rgTW4P9B7+S4jv9NTn+P/3eRNl2cV9cJ1jZIqqdC0g923AZvz9xWTL54eCEYftKyoQ3G+Q0b9KWhLFPm/KwPJKH20EuVp1odB1qWZl3fILcxncQkUTZrhnJUKZ2gLp4ZVeWPa7OKKIlYpRQ/0ySq/kxqdSNkaAtXChoKISPKqypsk9xu5HwdUrerF2fI9UohG9wdO9/372JX/0F5RPnk85nXKGNgnl/g2B7TZmq4RUgPoGL727Z4lY7+wNCgFD9jc1V7/x4Ms1dVQlbtG9rs73oL7B863Tr/b+ke0Jr5//hwcNrY/zs+GQz28/8u0qbz/x189WOWKo1ye1CgOvU3Zibfbl56jVnJzGT5JqYpLCalyoRUm+3cXFrMo5VpMp9Ol/ja2bDBtQYzfFBuUyx7to3bpTQZy+wwZydimA4NwimhPGCUv13RLyShd2OeI5XtidEdU04Y/YCyIVHG4K5klSY6bZDMm7PUijswEfxr0KDgn0OBhupn1t8fYhRRpSUdpVo0Jf8SqmwItH2tNhl8ZgULSUJ2RxezVcVmgmxfoTnh+ynythVFg2FldaKKjO1ruDHXFzN6Y8mxjUl9CweEK7YZGzCGNI/glo7fWnYbK/Szpc/9cNBWl65bWKpWIdp9gdl+hfotpvr6L5gii+mEC4lb5LEu/uv48LgZ/9E/3t//2Ek6gEuiNUquQAtwXQ/XU+QwSikzvgUSEr4lE1SBdwC/TqkClSaJkFqBmiJjMGFi5C5aUD75F5DIiKYztMd5lXzCI+8AOE6sJ4IHicQxfY+R89w/PgzgF87mILh904gECUpglGPgBRdXr6+0kOgdQHZ18eXjK4ioVF4wobpr/zrxvWD0QXbt3zxjOumaP/lPNePdktCIhG/TBMbUTKWPAnWdeI+CEXnrPQp0bJ6FpBPv0f95B/CSSCpSBU8vnigvSKQwHs8LaISk66pL8YcXzFQoIux+C16oPv5fPDm/ePYkiKOt8lh3/2tw3Lz/dXjY7+3H/y7SQSM40/vxVT0A9PcHU60TNex2aTwJ1NRekzf4ZkSiCXazyr6t61M+FjK2A5ywf1d6zvAvY0a0r96lROJD+PHVr83ozzUMTH2/Un0THufNKNY1PMr6G7bD8z45EtY7OIALnCETib1T5/nAREgY2Cu7zEV9ed6bN2/U1DsAiTxCaW9bF3fO6l0FAfzd87nNNE9jyKI3I5zZnVv4u/dXiHCUTooszzvI+TnS2Y8lyjndZaqGRMprRIqfDTIZEdMm01xb100mZlp5oFFp8yA4mz/MW06uFWAozXrFZ2JCuZ8Qpa6FjMD3JU7M1FEEHYLvJ1IYxw2JFBEsPHBcTEWl5RwsCfD9VKG013rPf7syb2U0faUjyj8ttJHysSS+7XjleZVGIfgp+FExX0KQF6dqCp08u37hyRlcoCcfOiBCOux27y6M1fOBmaVMj3neAn7COSzADCFYwEV2zcs8FTHdsPAWvknub/5P7cn+8hbFlRBYgLBYHxbw5ubjG1iAIQP5RaqFXWWawle/F4UrQlGUlqb/F/Cm0ynqLV0kq9WrBpE236ncdau988mBq03C7pZchaLts0at6r3IlQrYpPG1az8tWm5cKW2vtXyXcWXN2hXaBVD7902/Up5tQQQuNjQIk7Quf7/Xizvt9V0waOOVwdkzuuqdPKp0cy7FGxvwadyoDNqib2EBIyGYIWHDcFsJVANsg0iK5FXv97oEhLF2/mXMbql5G7t7+xtZNHBFSi3TdiGLYOF2Jq3bJS1Gs/qcqFWe5fCKlgFQvR+2YhR9abT0/aUW/B9MhI7vH/nr0hr83z85auL/o5P+/v7XTtLNTQkvOy7gd2rvn5SRe83yCBOJDoz/RiSnfJLVXVXZAmx15a6y3FKv8pmZvNYeMO8B8w4A86oRIGJMyAR/phxvsdmY0DwQZL2BZ3BlfUVnPvV6n2/81/1/KCOn7sqx12t7mn2fu0Br93+Wvv91enq83//ZSWqeZ5GE4nuN3PxSy0dZqdIifpFh7wu060HjhqsHWkuHa6HgWgrGUPoT5DZi2W4uo6yFb896Qf806BfnRM7umoeweYTaxJ1xLZ/R2pMixzgLZCQJtT8NnPypyPo5vyubsFQSNizupAAoyicpI9LleQAqFAkOoThtityRqyrbmId6zPqEJVOSR6mocIoxKaMaRIL8/PLpy8OrRgFA7UNrRkCgyu4quarFJpMVE84vn1beTaQZwuVXfvJU6dlG9EqN28Jfim0xQmZBYC7a28mSNRqjrGUuYpwqs4p0q3K3fhJjIDxbOgRLxK9QGkKgpiJlkbGPGUoNEkMx4fRDQV25T3Ag2DuJ2ixezKzE3BTrjhSatGMyB4l2yZLyCsVsVl6q/0xIBMrHYgj5HuGE6tzyQxHHKad63rVGnN+ciAwu6So68YkMp1RjqFOJXZJQ3zaGW+sP4uigWKc2GLuP4Lk1UK3I2uwndpYxamMtJF9U2caWfWKyjBpfPLn6tVg5u37LVndF1RUaynvLaJbyMUr35liK2FJFHiXCrCvt5y8YRa5BpSOz9i8+EgVaLBN+bD2F/TCKvYIQLVd5yuExiZE9Jgp33nemj5RvOmTj3msGBNdfcMquFVUDbld2t/EEVwmGtWEYobIfJVPaAAcxLn1cmdp8AhTxokvZDdZ/DoLgzysq3UbZlpchoivLN2QDtyk6T5Uv1H12XppMPjeTVju5zYTs7aP1RmSr1cxIjJQZ27fbUQvfFdmOWPGNOiebkDY0uZqXjlYExGat2H/xbbdpE/xv3OF9QgHW4P/D4+N+E/+f9Pff/91J+prxv5FgC/Bf8Cb6F3wZ/Lvb1DXsb1/cPfQXvA35C74H/nvgX0l74P8dA3/BN8D9mXMr023gfCzEWtD/n0JYi+KA70mcsOzLmBmzAJ5EVBtP9NoqKZgIM1QlxmKG3VpQ8UZquyesFXwzVLukpT2ozdIG+K8RNvLpUHAd/js97TW+/zDo9/b4byfpK8Z/Tbu7PxT8bzG6KCk2UGG9cAkgLoeLVbFivfRLwMa6+C0IstGIPZjcg8ky7cHk9wsm695hPa5c4SnL9BkhZp1vhjbrXutrAJ4NdW6CQW/V6JeDoxvgvyzK9e5bgOvjPwbN738d9vb3v3aSvmL8l9vd/XHfL5ZSA++5zCWcV0atV/GdyCnsHNc5MVvwXCbsHsftcVyZ9jju+8Vxzhusx28Vj1em/Y2AbfP6dm8EZIa0CXJdaUv7DdTvI638/z/zq+tb4rEG//f6J4fN+I/Tk/33/3aSDP7/LP/d5zm7JnOV/0efakr86PRfz/rjs/1A3qd92qd9+hrS/wcAAP//veaXmwCAAAA=
                  chart:
                    name: daas-operator
                    version: 0.1.0
                  values: |-
                    image:
                      repository: 804282218731.dkr.ecr.us-west-2.amazonaws.com/daas
                      pullPolicy: Always
                      tag: 0.0.6
                  release:
                    name: daas
                    namespace: daas
                - bundle: H4sIFAAAAAAA/ykAK2FIUjBjSE02THk5NWIzVjBkUzVpWlM5Nk9WVjZNV2xqYW5keVRRbz1IZWxtAOwaf2/burF/61NclT2gzSpKtuOk8FAMWVNsb29rH5q3PgxF0UdJZ4sNRbIkZdeNs88+kJIdW3GenaRI1873hy2Rx+PdkfeLYk6piaRCTa3UkUYjK52hiZ8XVFsypSV/cGdIkiQ5PDjw/0mStP+TbqfzoHNw1E/63X7/qPcg6fSP+p0HkNx96s1QGUv1g+TOc7WF+0aAKvYGtWFSDGDcDahSi9eEJKQT5GgyzZT1TcfwN+QlZG5zwFBq+KlKUQu0aAJBSxzANfspsFOFA6BKcZZRRywYr87ztRXxfwrX2f+Y8grNl3EAm+3/oGX/h91Od2f/9wFRFAU5VWwQAKCgKcd8AFZXGACwko7QdQBoVNIwK/V0AE+Tg+7Tbrfz9KjXIfmZJphpUplogsZGXUJL+lkKOjEkk2Xs9penYOloAJxaNNa/q4rznyVn2XQAx3xCp2bnAr4CXGf/FkvlVyt+XyBXqA2x6pauYIP99w67h6v23016h7v4fy9wfh7vBy8+KSpysAWCi+Igh/7Zh3kS7McXF8H5eQQ5DplACK/ZM8SNDSG6xKYVt0DqVPKlI0ze1GHFYb4ao9YsR5g5fyMyOOz5R1aeVsMh+wRhFEJDC0XuHgPP7XON1CLQxQzDivMpfKwoZ0OGucsyvBwk+BVr2h7fuhmcTAZSzGhlEIwscSmHqaUfMuS5AaoROCuZxRysBFswA4/SqdfMyctTh8vECIzC7DEJfhyCRo7UNCrMpLCUCdPkSr6NWZgwziFFqIzj0wD1zDfcbq1oN2ZV2Wy40O28c6HfBuXa/m30z82Czh+8LINn2y/wJY8LrdREyOtaZfXYOZ8rjTdkTmkm7BDCH0z0gwlbtOpJt99u6x9XNuHS6joLanJat7J+hZvtUmNxmiK/wSr7UZdL3BZtWev1c5O5w8yFa04zhPCPIYTvw5ubmCxLKWqOzfYc1/g1ywXykpgi9lIM4PwcmMh4lW8WmNQsbcY3yDGzUv+jmZYs7bRGJceLesb1UaXI2cLaCZPxogg5P18zZAYfK2mxpaKrVEoq6AjzKJ3WhOa77hT1mGXt8bWKTxvmb6zkttTRWpbqamwbLdaOhKyXjAljqchwVa5lc11nFe1AYho90CyTlbDOnVYGbyKyH39cD395nedbRSNZzUwrHD3aqJBL70oeX0dbLGtgyf/MZwmbh3ArAld8zP3F/835n6sO7lYHbqr/+p1+q/47Ouzt6r97gZYJ+cVu6kBvYq4+XD4jcvvFOWomCGfiLB53KFcF7QRnTOQDOKGKBSVamlNLXem4vR9aMju4uIgcJwE03rEuQj2vm8jwRTCYgWAiR2HhwNmUS9QcHUdlwmyxKrOvdR3avOx1PFv5b1ryq6RqIl/TbL8YbLb/DzIlSmPkQwHnt3AFG+y/mxwkrfqvc9Tp7ez/PqBt3ym1WRGP5/b8d5muMedwTTJwuYkmlNmwwTWKZusG+Ha4uAhbJk6VarCX0tsajQohrT86bnDDeYpZSHkWDmBpk17tjybIRoUNBxAm4ZruHDlajJQ/kQoH4BtNlWWIOeZP/OuQMo75wpHMTaTmZllLDpal2iAZwJxkfdTmdqSdn429xDHqputqHrTNWkSGhgsCWaWZnT6XwuIne8mdrsSx+ZdBPYBOt3fQX+34q5aVWtvzUorXUtrFkaGDpshDvSR91OycFcYWvQufmzLryurYJaGZ5YOl88I57bKkIh8sNTniccpEbIpWa5S1GmYr7wB78Ctl9YcMl6bOmYMcFZfTEutUNUXQSPNpa3AlLOPQcApaci4rC8ZSW5klCv4ENFpxsxAJH0chiiwrUVb2Wd/8CXLZmgEAs0JC6JhkYnSVzyXmCCHhleGGIyrot9pzKTBYN8+rOV1mGqLhtxjSdnAD2Bz/dUqzuyUAm+L/wWGvFf+7ye78936gHf8Xkf90JdbcKgloAs//ah4Qde6YCLR15y2FVraQmn32HJKzp/Ux01yrryXH2+lSS47ftTZ1xdHzEAFVzKccZgBvQ6qUCd81XyEb9+TaL0PsvHuMOvVdI7ThEwg5M/5/4nLa8N1t1+svTORMjG6/bGlN4LtePVOlHzCzzQKudSGO/g1dx7YKc1p+jUM3+ZKd3cK65jvvdzbH95USXRf/idsIbCSkxjvPsfH8r9c+/zvsHB7t4v99wB78TK1FLYyrJuoFh0mBAtKKcee2QNHsjI7QkGAPfimYAVMpJbU1YArkHEZcplA6H8vE6Alo5NSyMYKitlhqpyIP9kDgyBsTPFIah+wT5vVh3MPHBF4JPgUp/EjHEijUwJlAEpCT0/enVmoM9qD5OPXm+SnkTJuAjJiN/W/NfkDSzzr2v/OGYhS7n/mrGYv4klBKs7NKwZBxNME+MRMV7JOUngX7xJbuWWo2Cvb/E+zBG6qZrAz8ePLCBERp6XxeQFiONK7RtfwQkLHJZI7xt+AprrP/1y+OT/75gpT5F5hjg/13uknSvv/ZS3bn//cCe9fe2Awevl29CvruUWGtMoM4ZuWImMJfk3DZUkrzEcYNcuRxIyaGUpfe1Cn/s7FTjs+GnNrIfKyoxsfw8O0v7SuhGyZw+NES+jZzHLfvs26Y4xJ/SzmC4PfuxAZ7zmfwyj3O4CecwgycGDCDk+ZLoXta3LCFWTCLHNS/87+VJ/8WzGDlU80MUik5zOA3qyv8DWYAsyCIbgTBcWXlCIXbCZjDUMu5VPPMFyrjAsJblxtEucwMjDuk0yXJpVZHzBZV6q/+CaknUuYf4gV63FyRMXEz7vG34CJ3sIMd7OC7hP8GAAD//4rVlxQANAAA
                  chart:
                    name: daas-operator-resources
                    version: 0.0.1
                  values: |-
                    dapi:
                      enabled: true
                  release:
                    name: dapi
                    namespace: daas
profiles:
  - name: deploy-crib-aws
    patches:
      - op: add
        path: deployments.vcluster-daas.helm.values.controlPlane.advanced.serviceAccount.name
        value: vc-daas
      - op: replace
        path: deployments.vcluster-daas.helm.values.rbac.role.enabled
        value: false
  - name: deploy-anvil
    patches:
      - op: add
        path: deployments.vcluster-daas.helm.values.experimental.deploy.vcluster.helm
        value:
          chart:
            name: component-chart
            repo: https://charts.devspace.sh
            version: 0.9.1
          values: |-
            containers:
              - image: ghcr.io/foundry-rs/foundry:latest
                command: [anvil]
                args:
                  - --host
                  - "0.0.0.0"
                  - --port
                  - "8545"
                  - --chain-id
                  - "31337"
                  - --block-time
                  - "10"
                  - --dump-state
                  - /data/anvil/anvil_state.json
            service:
              name: anvil
              type: ClusterIP
              ports:
                - port: 8545
            podSecurityContext:
              fsGroup: 1000
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
          release:
            name: anvil
            namespace: daas
  - name: sync-sa
    patches:
      - op: replace
        path: deployments.vcluster-daas.helm.values.sync.toHost.serviceAccounts.enabled
        value: true
