---
# chart: https://github.com/loft-sh/vcluster/tree/main/chart
version: v2beta1
name: vcluster-daas

require:
  devspace: ">= 6.0"

vars:
  DEVSPACE_ENV_FILE:
    source: env
    default: .env
  # specific
  HOST_NAME:
    source: env
    default: main.stage.cldev.sh

pipelines:
  deploy:
    run: |-
      create_deployments vcluster-daas
  purge:
    run: |-
      purge_deployments vcluster-daas
      kubectl delete pvc data-vcluster-daas-0 --ignore-not-found

deployments:
  vcluster-daas:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: vcluster
        repo: https://charts.loft.sh
      values:
        controlPlane:
          distro:
            k8s:
              enabled: true
              securityContext:
                runAsUser: 12345
                runAsNonRoot: true
          statefulSet:
            security:
              podSecurityContext:
                fsGroup: 12345
              containerSecurityContext:
                runAsUser: 12345
                runAsNonRoot: true
          advanced:
            serviceAccount:
              enabled: true
        rbac:
          role:
            enabled: true
        sync:
          toHost:
            configMaps:
              enabled: true
            ingresses:
              enabled: true
            pods:
              enabled: true
            secrets:
              enabled: true
            services:
              enabled: true
            serviceAccounts:
              enabled: false
        experimental:
          deploy:
            vcluster:
              helm: []

profiles:
  ###########################
  ## vcluster options
  ###########################

  - name: vcluster-crib-aws
    patches:
      - op: add
        path: deployments.vcluster-daas.helm.values.controlPlane.advanced.serviceAccount.name
        value: vc-daas
      - op: replace
        path: deployments.vcluster-daas.helm.values.rbac.role.enabled
        value: false

  - name: vcluster-sync-sa
    patches:
      - op: replace
        path: deployments.vcluster-daas.helm.values.sync.toHost.serviceAccounts.enabled
        value: true

  ###########################
  ## component options
  ###########################

  - name: deploy-cluster-services-console
    patches:
      - op: add
        path: deployments.vcluster-daas.helm.values.experimental.deploy.vcluster.helm
        value:
          chart:
            name: console
            repo: oci://ghcr.io/ajgrande924/registry
            version: 0.1.0
          release:
            name: console
            namespace: daas
          values: |-
            image:
              repository: quay.io/openshift/origin-console
              tag: latest
            securityContext:
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1001
            ingress:
              enabled: true
              className: nginx-internal
              annotations:
                nginx.ingress.kubernetes.io/backend-protocol: HTTP
                external-dns.alpha.kubernetes.io/ttl: "120"
              hosts:
                - host: ${DEVSPACE_NAMESPACE}-console.${HOST_NAME}
                  paths:
                    - path: /
                      pathType: Prefix

  - name: deploy-cluster-services-olm
    patches:
      - op: add
        path: deployments.vcluster-daas.helm.values.experimental.deploy.vcluster.helm
        value:
          chart:
            name: olm
            repo: oci://ghcr.io/ajgrande924/registry
            version: 0.31.0
          release:
            name: olm
            namespace: daas
          values: |-
            extraManifests:
              - apiVersion: operators.coreos.com/v1alpha1
                kind: CatalogSource
                metadata:
                  name: daas-catalog
                  namespace: olm
                spec:
                  sourceType: grpc
                  image: 804282218731.dkr.ecr.us-west-2.amazonaws.com/daas-operator-catalog@sha256:8c372224e14ad4bdce354ffc6b7308ddae568dd940f2d5faaead38dd3ffc9d84 # v0.0.8

  - name: deploy-blockchain-anvil
    patches:
      - op: add
        path: deployments.vcluster-daas.helm.values.experimental.deploy.vcluster.helm
        value:
          chart:
            name: component-chart
            repo: https://charts.devspace.sh
            version: 0.9.1
          release:
            name: anvil
            namespace: daas
          values: |-
            containers:
              - image: ghcr.io/foundry-rs/foundry:latest
                command: [anvil]
                args:
                  - --host
                  - "0.0.0.0"
                  - --port
                  - "8545"
                  - --chain-id
                  - "31337"
                  - --block-time
                  - "10"
                  - --dump-state
                  - /data/anvil/anvil_state.json
            podSecurityContext:
              fsGroup: 1000
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
            service:
              name: anvil
              type: ClusterIP
              ports:
                - port: 8545
            ingress:
              enabled: true
              name: anvil
              ingressClassName: nginx-internal
              annotations:
                nginx.ingress.kubernetes.io/backend-protocol: HTTP
                external-dns.alpha.kubernetes.io/ttl: "120"
              rules:
                - host: ${DEVSPACE_NAMESPACE}-anvil.${HOST_NAME}
                  path: /
                  pathType: Prefix

  - name: deploy-chainlink-daas-operator
    patches:
      - op: add
        path: deployments.vcluster-daas.helm.values.experimental.deploy.vcluster.helm
        value:
          bundle: H4sIFAAAAAAA/ykAK2FIUjBjSE02THk5NWIzVjBkUzVpWlM5Nk9WVjZNV2xqYW5keVRRbz1IZWxtAOw9a5PbNpL5zF/Rq7mtTbxL6jEvl+p2r+ZsX9a3ju3y7Dl1lU3FENmSEIMAA4AayzO+334FgG+RkuwZy4+wP4wpoNHdeDUaDTQcEaJ8kaAkWsjhgyWROliTmH1zhzAajUZnJyf239Fo1Px3NJmcfDM+OT87Pjsen5yMvhmNj89PRt/A6C6F6IJUaSK/Gd2aV7NyXwiQhL5EqajgU1hNPJIkxc9RMA5GXoQqlDTRNukC/o4shtAME5gLCXqJ8JCQS3iWDSEQHP6RzlBy1Kg8TmKcQm2QeXqd4BRIkjAaEkPXW1VZHnufuk1+T1Cf/yvCUlR3rQB2zP/x5GTSmP8n4/Pzfv4fAnzf9yTaqfhApFxPYex5NCYLnHoAEhOhqBZyPYX7o5PJ/clkfP/8eBxEr2WAoQxS5V+h0v4kIDF5Kzi5UkEo4qEZVh5AkjL2XDAarqfweP5U6OcSFXLtAWiymAJPGcvYPU8Zu8RQolZT+OlnqzmerVBKGuEUBgNvnjK2kegplCsa4kUYWuk9gFAi0TgFLVP0AAjnQls1o6Zw/c4DOAJ8rRrySsHQJ5JPYfDv+fffBnAEEn9LqcTIajtypUCp2ANwes0IkIjoosHCpF1imEqq1w8E1/hGu3TVSDTiMSaunku6ogwX+EiFhBGna+eEKVMBmfIL9VTwF0LoolY28X8UyimcnZ4eT/Kk76VIkzItJAmZUUY1RWW4AURSJO4LwDfcPU+iEqkMHQajMdUZbpikUxiPRrH9FWNsx8F4cv8HasfGbymqfXA95KuXRLp+9biI8BIZhlpI1yxaMKN/XPsZFDKfU0712mZ/6hnydUNd/2uME0Y0quEvS2QJShXo5NZLwQ79f3xy1tT/Z8cnk17/HwKur4f3vEdvEsIja8wZxQZibr+tmRd494bv3nnX1z5EOKccYVAbM4EpMQC/xCEp0xC4rcRTQy546cyKqvaGG6PKeAhnx/aTxpfpfE7fwMAfQEYLeWQ+PSvjA6vWgRQczHqwht9SwuicYmQMSit94P2IjrbF14aDqYmCGYYkVQhKxFgxUl2d5xRZpIBIdDoQI9AC9JIq+Ha2dobu00uDS/kCVILhd4H3eA4SGRKVNVwouCaUq8xCtmlUwxVlDGYIqTJyKiBW+EzaHc2bL3tlE9N50aLNNTFvuc78fVqdqYLOv9kaTP+6f7eWMhZt4YgEL1xDubK5nLXE9xQukZTrOQz+qPw/qkGDlmO6/yBr/6wNvUqfmtmSbVpMf9p+zQaJw2Jkhmxn31rcsmObFaq2tfvO9mZwYywzRkKEwZ8HMPhl8P7TScSx4E5OtUtOh+UEXSKLA7UcWtmncH0NlIcsjboqFzj2XVgqswSeZCyCygjKKn1R7ElNHkmS4HUxdwMqhsXu8fq6pcgN/JYKjY1G2KQSE04WGPmztSOUj6ZLZ2C2NmJuxuzZjM26+q2CONOyu8WcMgjaa0G50oSHWK9Ddcq1jeym4s+MaiDOqjaKMFW4u3pVU/xpl86qowXOXIfG8vFtR+VLbRh810WRV2tb0Rc57UH2MdiLwIZO+NQr9t1Cl/0XYcLEOkZ+B+7AHfbfyfHorGH/nY/OevvvIFD1/5EkUcPV2HtNeTSFh8UI8GLUJCKaTIudb7d6qsxQM1sg041ul2hVQXs5ViwAN8Apj5BrODEUjKmV+SIYDYlyqi2buVXXhWOXK1nHMCY6XD6pSLBVhs3FqJTlzJHPZ0hGvtIwOe0rqpeFfHXvgCNhoOqVyJJcaS3+l8Ssxvl+WayihlwCq1XtgytXsMgbu7UyTT9NKcaGB+c2ddpcR7aNt7ZVJ6gS23C5bApWdlbDbdMucWbZoqzU0y8nRtVuK8pslaVDHtUpzHhSp+wcdjCozAybFJQOPHj3brqRrckCbprGfc3eGjS5PK+49Dbolf6+unxHEIo4Jjya1hJNsw3rhwNlNpELVW8iH1rQTLJR4bqR5vsMSYTSt8Peqzd0bVhn3qm6xMhX3f2zpSc2RrOBmodta5cXmFtYMLpCjko9l2KGdYpLrZPvsTGyABKil1MYLpEwvXzbzBTGjr8/uj+uZVBONSXsITKyvsRQ8EhNYXxaw0lQUjtnXO5kVKsziegHiWlKrm8j5VYhx1UhV4KlMf5gNIdqSuNDbNKfO6F0nDTy86WwzHHUWpRCvTDGiV4/pDJzR0PbmKw6Scver7lOb6NiN/jlHtfKCpX7YO+UT8XVW2JV/b8fxu1TW1FfLnTZ/3JGwqCqQangH7oT2GH/T0Znp3X7f2LRe/v/ALDv5ry6T7Bjg6R6KSR9a+dt8Pq+c8Xkm4cXguF7bRu6zDi/MQZ9aSjLlDk96wNJqD30UuWp1sAZLRurrm8stzldxCRRNmmFclbJXaAuvhlV5Y8rs4soidhGKX6mSVT9mdRwI2RoM1sFDYWQEeXVJuyS3DpyPg+pu5sXV8h1q5AN7o6d7/sfMq7+k/KI8sXHG16zjIH5foFze0ybNcMWIT2Ayti/6xGv0tmvGBorxc/YXNbK34JhVlQlpM1vaJO/ahfY7xq2rv93dA9op/9v4/7f6dl43K//h4B91/8P0NUPWKo0yrszBe5y6bduA+esqvy2jLNTj430fRa2YuXcsTY3lt98qW6tE0kymVtqVbrpP5V0pu+CcEkoDxjlrzsFJQktWzQSvPzxq5hFVGlJZ6kWskwXkoTsTlu9buV8rFoO55QTRt+irFe4Lb1R9zaUrBmaWY0WKSpze/GVJjptiN5Ia4rdyM5FriRvMVo7eqW1Ihz1lZCvKV/ssJcpX0hUHSbzAabFNjOxVeCK4alqiQeeAE1FX6jzhr15Fxr9Dk6HWnxMjTWMNM9fNs5eOlxNFfqZ3Xu7RfBO9y13sE+prs+3XZX77ckXCnX7P1gii+mCC4l3yGNX/M/p8enG/f/T/vz/IHAEz4nWKLkCLcB1PVwtkcMspcyoF0hI+JosUAXeEfxzSRWoNEmE1ArUEhmDBRMzd9BO+eIvIJERTVdoj3Mq6YRH3hFwXFhlBN8mEuf0DUZOef/huwCecbYGwW1JIxIkKIFRjoEXPLz85VILid4RZFfXXj64hIhK5QULqof2rxPfC2Zv5dD+zROWi6H5k/9UKz4sCc1I+DpNYE7NWnsvUFeJdy+YkdfevUDH5ltIuvDu/Z93BC+JpCJV8PjhI+UFiRRG6XkBjZAMHboUv3rBSoUiwuGXoIga8X9/v3j6/aMnz74P4ujueOya/5PxeTP+72xy1s//Q8ARPFgSvkAmFp53dAQrF4Ln5dYhhDJSZc6kkQN/tjZqiTDuLDoyOdl5bSWCsH78/6mb43cH9fn/4tHFwx8e3enk38P/Nzltxn8cT/r4v8PAUWMCen/4qRYAfPzzt0utEzUdDmm8CNTShkmYLc6MRAscZsi+xfUpnwsZ2wWesP9Qes3wr3NGtK9+S4nE7+APP/2zGf27g4HB9yvo+/C4aEYx7+BR4tt6jHby8Lz3joQ2evAhrpCJxN6p9HxgIiQM7JVt5qL+PO/Vq1dq6R2BRB6htLftizuH9a6CAP7l+dwmmq85ZNG7Ea6s5x7+5f0NIpyliyLJ845yfo509mODck53k6ohkfIakeJng0xGxNTJVNfiOmPSmJXfalTafAjO1t/lNSdXCjCUsEDtM7Gg3E+IUldCRuD7EhfGdCyCTsH3EymM4QaJFBHceOC4GESl5RosCfD9VKG017ovfrw0pTKavtIR5e8X2kr5XBLfdrzyvEqlEPwU/KiwlyHIs1O1hEGeXL/w5gZcoBdvByBCOh0OP1wY285Hxko1PeZ5N/APXMMNmCkEN/Awu+ZnvoqYfrjxbnwD7m/+T+3L/vJuiitBcAPCbvfhBl5dv3sFN2DIQH6R7sY6nUzmTz8XmS2hSEpL0/838GowKPA2LhLW8KpBxM0ylbuOtTLvHbjcJOxuSZYUOWV1jOqd2NbK71Px2pWvjhZuXCfuxtq8x9qKWbs+fQPU/n01ruRnfsrAxQUHYZLW5R+PRvGgG98FAjeKTO7/QNvK5BHF+3MpSuzBp3GbNuiKvIYbmAnBDAkbgt1JoBpcHURSJD+Nfq5LQBjr5l/Ga5ctb+O2t5fIIsErUmqZdgtZBIp3M+n0lnYMmvYzwk55NkNrOiZA9W5gyyz61JbS1wkd9n+wEDq+feS3gx32//jspBn/c3I26u//HQSur0vzcuACvpf2/lEZudnMjzCR6IzxH4nklC8y3DZka2CrS3eVaQte5ZmhHKs3mHuD+QAGc9sMEDEmZIFPKMctYzYmNA8E2j3AM5NlN6IbPnW8jzf/6/o/lJFr7splgV/srYDb3AXbrv/Ho8lx0/97ft7f/z4MNI+0SULxjUZufqnN0+xUaRG/yOzvh2j3g0YNV8+0N87XQ8G1FIyh9BfIbcS6PVxCWQvfX42C8XkwLo6K3bhrXl3JIxQX7ph782aLPSx2jLNAVpJQ+9OYlP8okp7kFyMSlkrCppUrSoryRcqIdGkegApFglMoDpwjD/L3HzJWeajPakxYsiR5lJIKlxiTMqpFJMgvnj9+eXzZyACoPbRnBASqrFfJoRZOJismXDx/XCmbSDOFy1eecqj0bC29we3Gb+SCoZ8HAbpofydLVmmMspq5FwOoMjtJtyt3eygxB8Kz7UOwQfwSpSEEailSFpnxsUKpQWIoFpy+Lagr9wQLgr2Tqs0GxqxKzC2x7kixSTsma5Boty0pr1DMVuUN/B+ERKB8LqaQ+wgXVOcjPxRxnHKq10M7iPP7TpGxS4aKLnwiwyXVGOpU4pAk1LeV4Xb0B3F0VOxVG4zdI4huH1TLsmP2PTvLDGozWki+sbKVLfvEJJlmfPHo8p/F7tn1W7bDK1BbWijvLdOylM9RupJzKWJLFXmUCLO3tM+fMIpcg0pnZv9fPBIGWmwSfmA1hX0Yxx4YRZsojzk8IDGyB0ThwfvO9JHyTYfs3XvNgPB6AdfYtaxqwHVrdxtNcJlgWJuGESr7KJ3SxnAQ81LHldClE6CIF95IbrD+UxAEf2pB2kbZ5pchwq35e7KBbQ2dQ+WFwo/OS5PFx2bSOU5ga5T9ewpCNcYdfbdL1Th4YjZiz6yUL3COEnlYefwKuUgXS6gcohg9zlDDWqR2E+fenOkgLnOKUa6dKFc0cs/UKLMnKe6DbaoE2GN8ZgZGRx7k8fDT/Db5h7eTgaeVh3WyqrUsiSXYKzb2NTKj0nE+NzuBFbJ18RblX2CWaohSNM06I+HrKyIjBaGIE6KpdUmugTZ1VhWs79O9cDZDF5AcwOPs7SBVLOpmNLrrOYQ7rGxlWaJEILKrBx2LWCgNIUozKNgarqTgi20Vb9Hm9ceNIhEqo8tDTLQaihXKFcWrYXYh2DeC+m7EKPuKkhoe2X86ee6e8dumo4E3fimiH5PEzx431iKmYef8JlKS9eb0dleWP5pabn1zpIESRdQdej7fOYf2aL731otbWho5mTHcMI0+kNFMCIaEt+Ishdp4muAD2Wxpm6y3HzCi1NMt6ujuONrnFQ7CxZ7xf8qVMjt1+GhTSX/aCnZbkzbgYrc9adFqFqWYmTbbYVJ28G1JdsSK54qdbELaV2qqaems5W2UrBb9478HgH38f2Y7dJtQ0B3nP8enp+Om/+9s3P//DweBz9n/ZyS4A/ef4E3vn+Cbzr88IrHi+7MFD+/6E7zL8yd47/jrHX8V6B1/X7HjT/A9/H6iuYfZZrrOhdhpEv+XEHZEccA3JE5Y9jJ6xiyARxHVRhP9YhspWAgzVSXGYoXDWkDpXs12S1tW8P1M2Y1W6i3ZDPaw/xrB3u9vCu46/z0ZN9//mozO+/i/g8BnbP81x93tTcH/FrOHJcWGVVjP3DAQ216pKG3Feu6nMBvr4ndYkI1K9MZkb0yW0BuTX68xWdcOu+3KFk1ZQn+yfNe8+pPlHPqT5f5kuT9Z7k+W+5Pl/mS5hUt/svz5niw3bMx9HHNbzczeR3cA2MP/l73m+OFHwDvjPzbf/5+cn/b+v0PAZ+z/y8fd7f1+zyylhr/PJW74+aqvzpb+PZFTOLhfz4nZ4c/LhO39eL0fr4Tej/f1+vGcNtjtv6tovBJ6v91d8+r9djn0frveb9f77Xq/Xe+36/12LVx6v93n67fLbMp9/HWtZmXvp/uCoe7/y7bF9p2lu/rfv3a//z3eeP/7dHLex38cBHzf94q9X2Xr5N7asgvf6Wg0tk5hr7aRgwt2RdYm0eyCHH4/M3vooYcevhT4/wAAAP//YOdkMACcAAA=
          chart:
            name: daas-operator
            version: 0.1.3
          release:
            name: daas
            namespace: daas
          values: |-
            image:
              repository: 804282218731.dkr.ecr.us-west-2.amazonaws.com/daas
              pullPolicy: Always
              tag: 0.0.9
            imagePullSecrets: []

  - name: deploy-chainlink-daas-api
    patches:
      - op: add
        path: deployments.vcluster-daas.helm.values.experimental.deploy.vcluster.helm
        value:
          bundle: H4sIFAAAAAAA/ykAK2FIUjBjSE02THk5NWIzVjBkUzVpWlM5Nk9WVjZNV2xqYW5keVRRbz1IZWxtAOw7bXPbNtL5zF+xpZ/OJHlKSpRkO6Obzo0vzvQ9ycS9dG4ymQYkVyRsEGABUI5q5X77DcAXUbQUyS9Vm1T7QSKBxWKxwC52F0RMiPJEjpJoIT2JShQyQtV7mhKp/RnJ2IM7Q7/f7x+NRva/3+93//uDIHgQjI6PhkfDYDTqP+gHh8ej0QPo373rzVAoTeSD/p376g7uEwGS09coFRV8DNOBQ/K8ee37fT9wYlSRpLm2RSfwLbIMIrM4YCIk/FCEKDlqVA4nGY5hzXpy9CzHMZA8ZzQihpgzbfczcv5sQfxNYZ3+TwkrUN2PAdik/8fDQUf/jwbBYK//uwDP85yY5HTsACAnIcN4DFoW6ADQjCRoKgAk5kJRLeRsDE/6o8GTwSB4cjwM/PhC+hhJv1DeJSrtDXySkd8FJ5fKj0TWM+vLUtAkGQMjGpW273nB2EvBaDQbwwm7JDNV9/iyYOwMI4lajeHNWwdAoZzSqGKltCRPWaE0yu9emlY8kahUWd0MYkKYQsc5j/+ooZ2L0Iup0pKGhRbyTx0lvteS/EQ4naCqCG43/+v0X2OW23H0fk2R5SiVr/NbmoIN+j88Ghwt6/+gPzzc7/87gaur3mPn2fuc8Bh0imB2cRAT+2y3ed953Pvwwbm68iDGCeUI7po145u2LngLbFIwDX7pSj43hP3X5bZiMF9MUUoaI8yNUvIIjob2kWZnxWRC34PruVDRQh6bR8dy+1Qi0Qik6WFSMDaD3wrC6IRibLwMOw7f+QVL2hZfmx7MmBSEGJFCISiRYcuHKUc/ochiBUQiMJpRjTFoATqlCh6GMyuZ0+dnBpfyBFSO0SPf+W4CEhkSVYkwElwTylXlK9kyquGSMgYhQqEMnwqIZb7idmtBmzbLwqaTRrZ1ZSPfCmVt/TbyZ6qh8392LOOvt5/gBY+NVEoi/qtSZGXbms+lwhsyl0vK9QTcL5X3pXI7tMpOt19uqx+XFmFrdo0GVT6tmVk7w9VyKbEYCZHdYJZtq8UUd4fWlnr5XHnuMDd7GiMRgvv/Lri/ujdXMZFlgpccq+05LvFLllNkma/Snh3FGK6ugPKIFfHmAfslS5vxFTKMtJA/Vt36rZVWieSkiWdMHclz/6LRdp+KXhOEXF2taDKH3wqhsSOi61QywkmCsRfOSkL1qjsrd/SVIj6rmL+xkLuj9layVEZj20ixNCT+6pFRrjThES6Pq62uq7Siu5FUng2QKBIF18acFgpvMmTb/qRs/nyd5VtG86OSmc529HCjQBbW1X+0jjZvS6Blf+pe3OrB3YrANRuzu/1/s/9nooO7xYEb/L8gGHXzP8dHg2Dv/+0COipkJ7sKLqyKmfiwnSMy68UYasp9RvlFbxoQlqckcC4oj8dwSnLqZKhJTDQxocr2dqildvDhg2c4caCyjmXQY3ndRIY1m8EcOOUxcg0jo1PGUTN0DJVLqtPlMduYzKDVsaHhWYv/kIxdJ1USqXT1oxRbUV6L+FLsd9d+1GKTWcSQd+e+jDYrpqvQc2uqf4op28MtYLP9X04t3GYn2JT/C447+b9BcNzfx/87gY79X57sWpUl4Ql+BMdsEqtNQ/+v4OPsYT1s1v9zEfq5RM+GAozdwgBs0P9Bf9S/rv9He/3fBXT9u5DoKO1Na3/uexGucOfcFcHgYhFdEqrdClflJFrVwJbDhw9ux8UjeV5ht9IbJRrhXGh7dFjhunWKIRXiwh1Da5Fer/cukSapdsfg9t0V1TEy1OjlNlfvjsEWqiKKEGOMv7KvE0IZxo0jWatIyU1bSgbao9owMoCaZHkeYVakrk8NnuMUZVV1PQ7eZi48RdyGQFRIqmdPBdf4Xi+4kwU/Uf9WKMcQDIajw+WKb6Qo8pU1zwV/JYRuzlUMVEk+lK3Re9XKWWKsqW187pBqTjLauyhCjDQbt05SatpZRng8bhUZ4r2Q8p5KO6Ve1CmYL70DHMAvhJYH2TrFhjmIMWdilmGZqggRJJJ41mlccE0ZVJyCFIyJQoPSRBeqRcGegHlLZhY8buMo8DxNMxSF/vpQ/QNi0ekBAKNUgGuYpDy5zmeLOd/33WvNFUPM4bBTHguOzqp+XtR0qaqIuvtd+jOHrfb/1innH+D/B8Hw+Nr+f7jf/3cCHf//PL5L9ud7EZ62DsTvJQ90Hu8mC3Qe328OqKb3x2aAzuP7z/8YzvfZn78JbLb/MiTR3QLATfHf6GjYsf+D/v77j91A18I3kd/ZUqxxqyCwCjz+qnGgF9wxEOzKzmoKKXQqJP3dcuhfPCmPmWupvhIMbydLKRh+1tKUBUPLgwckpzbkVGN445I8V+7b6lO9yjyZ8kWIVVdPUYa2KkHtfgUuo8r+XxIdpe7b287XvyiPKU9uP21hSeCznj1VhOcY6WoCV5oQQ/+GpmNbgRkpv8KJ6bylZ7fQrnrlfWRxfF4+zbr93zcLgSZcSLxzH5vOfw6Hh93vv4Oj/fffO4EDeEm0RskVaAHlhMNlihzCgjJjtiAn0QVJUPnOAfycUgWqyHMhtQKVImOQMBFCZmws5clXIJERTacIOdFpq5zw2DkAjolVJniYS5zQ9xiXwccXj3x4wdkMBLctDUuQowRGOfqOf3r265kWEp0DqD5Oe/30DGIqleMnVPfsb8m+44e/y579rQvSpGd+6lc15b0FoZBEF0UOE8pQOY99dZk7j/2QXDiPfZ2ZZyFp4jz+r3MAr4mkolDw3ekz5fi5FMbmOT6NkfRKdCnOHX+qIhFj71OwFGvvf3178vybZz+++MbP4rv2sVH/B139Pzwa9ff6vws4gKcp4QkykTjOwQFMy9tYjgckjmtNt5nnd8vZnXcL9OFK9FOS03fNp3+9Oo1gzzoWbQer2i6fMK8n3k2lLMgGhizlVFPCWtfV1t1O89qOknVzjDW8rA8HViXcHa85AGqzJDibfQp6X8M6/X/17OT0p2f3oPxbxP+Hg2FX/4f789/dwMFanXC+eLN0FXT09mGqda7GvR7NEl+l9pqEiZZCEifYq5A9i+tRPhEys1s9Yf9Uesbw6wkj2lO/FUTiI/jizc/dK6EbOjD4Xgt9mz5OuvdZN/SxwLfjCDb24TgfuxNr7FGZVXWcOfyAM5iDGQbM4bT6Utg8NTdsYe7MPQPlb/239GTfnDksfao5h1AIBnN4p2WB72AO0OBYK+kvbqLBHIwV54lBd8tbae6qJoubcctNbnwBcCV1TZJlsuVh7yrcdg59DiasNw3evO2glhvMCpnYS3LLyNW+5OtyNlpsNHfuFpx0vnhayULr5GTNZNQnAltPRdPgXiaic11xRTcbZ2TVmcY6YWw7G4sTjG3mwvFuBM5JoUWC3Bg3jGEiRa2odTIHCmU6e2PCXS8WkYJp4Acjf7AwFAnVaRFaGXIhL4WIz3sNeq+69aV6VbtHn9Luv4c97OHvDP8LAAD///xPjZMARgAA
          chart:
            name: daas-operator-resources
            version: 0.0.4
          release:
            name: dapi
            namespace: daas
          values: |-
            dapi:
              enabled: true
              image:
                repository: 804282218731.dkr.ecr.us-west-2.amazonaws.com/daas
                pullPolicy: Always
                tag: 0.0.9
              imagePullSecrets: []
              service:
                type: ClusterIP
              ingress:
                enabled: true
                annotations:
                  nginx.ingress.kubernetes.io/backend-protocol: HTTP
                  external-dns.alpha.kubernetes.io/ttl: "120"
                ingressClassName: nginx-internal
                host: ${DEVSPACE_NAMESPACE}-dapi.${HOST_NAME}
                path: /
                pathType: Prefix
