---
# chart: https://github.com/loft-sh/vcluster/tree/main/chart
version: v2beta1
name: vcluster-daas
require:
  devspace: ">= 6.0"
vars:
  DEVSPACE_ENV_FILE:
    source: env
    default: .env
pipelines:
  deploy:
    run: |-
      create_deployments vcluster-daas
  purge:
    run: |-
      purge_deployments vcluster-daas
      kubectl delete pvc data-vcluster-daas-0 --ignore-not-found
deployments:
  vcluster-daas:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: vcluster
        repo: https://charts.loft.sh
      values:
        controlPlane:
          distro:
            k8s:
              enabled: true
              securityContext:
                runAsUser: 12345
                runAsNonRoot: true
          statefulSet:
            security:
              podSecurityContext:
                fsGroup: 12345
              containerSecurityContext:
                runAsUser: 12345
                runAsNonRoot: true
          advanced:
            serviceAccount:
              enabled: true
        rbac:
          role:
            enabled: true
        sync:
          toHost:
            configMaps:
              enabled: true
            pods:
              enabled: true
            secrets:
              enabled: true
            services:
              enabled: true
            serviceAccounts:
              enabled: false
        experimental:
          deploy:
            vcluster:
              helm:
                - bundle: H4sIFAAAAAAA/ykAK2FIUjBjSE02THk5NWIzVjBkUzVpWlM5Nk9WVjZNV2xqYW5keVRRbz1IZWxtAOxde5PbNpLP3/wUvZrb2sS3pB7zPNXtXs15fFlfHNvlyTl1lU3FENmikAEBBgA1lmd8n/0KAN8SJXlGHjuO+o8xBYDdjVfj1yAajghRvkhREi1k//GMSB0sSMK+2iENBoPBydGR/XcwGLT/HYxGR18Nj06Pj0+Ho6PDwVeD4eHp0eArGOxSiS7KlCbyq8G9ZbUr9zshktLXKBUVfAzzkUfStPw5CIbBwItQhZKm2iadwz+QJRCaYQJTIUHPEC4IuYQX+RACweG7bIKSo0blcZLgGBqDzNOLFMdA0pTRkBi+3rwucuh96jb5I1Fz/s8Jy1Dt2gBsmP/D0dGoNf+Phqen+/n/EOT7vifRTsXHIuN6DEPPowmJcewBSEyFolrIxRjOBkejs9FoeHZ6OAyiKxlgKINM+deotD8KSELeCU6uVRCKpG+GlQeQZoy9FIyGizE8nT4X+qVEhVx7AJrEY+AZY7m4lxljlxhK1GoMP/1sLceLOUpJIxxDr+dNM8aWEj2Fck5DPA9Dq70HEEokGsegZYYeAOFcaGtm1Bhu3nsAB4BXqqWvFAx9IvkYev9ePP+9Bwcg8beMSoystSPXCpRKPABn14wCqYjOWyJM2iWGmaR68VhwjW+1S1etRKMeY+L6paRzyjDGJyokjDhbOyVMmQrIjJ+r54K/EkKXtbKJ/6NQjuHk+PhwVCR9K0WWVmkhScmEMqopKiMNIJIidU8AvpHueRKVyGToSjCaUJ2XDdNsDMPBILG/EkzsOBiOzr6ndmz8lqHapqyHfP6aSNevHhcRXiLDUAvpmkULZuyPaz9ThEynlFO9sNmfeoZ82dS0/xqTlBGNqv/LDFmKUgU6vfdSsMH+Hx6dtO3/yeHRaG//H4JubvqPvCdvU8IjC+aMYQMxtc8W5gXeo/77997NjQ8RTilH6DXGTGDe6IFflSEZ0xA4V+K5YRe8drCibr3h1pgyHsLJoX2kyWU2ndK30PN7kPNCHplHz+r42Jp1IKUEsx4s4LeMMDqlGBlAabUPvB/R8bbltZFgaqJggiHJFIISCdZAqqvzlCKLFBCJzgZiBFqAnlEFX08WDug+vzRlKY9BpRh+E3hPpyCRIVF5w4WCa0K5yhGyTaMariljMEHIlNFTAbHK59puaN5i2auamE7LFm2viUXLdeZv0+pMlXz+xdZg/Lftu7XSsWwLxyR45RrKvVvo2Uj8QOVSSbmeQu/Pyv+z6rV4OaHbD7LVj42hV+tTM1typ8X0p+3XfJC4UoxMkG3sW1u26th2hept7Z5z3wxuDTJjJETo/WsPer/0Pnw6iSQR3OmpNunpSjlFZ8iSQM36Vvcx3NwA5SHLoq7KBU58VymVI4FnuYigNoLySp+XPqnJI2kaXJVzN6CiX3qPNzcrXrmF3zKhsdUIy1wSwkmMkT9ZOEbFaLp0AHNlIxYwZstmbNfVX6mIg5bdLeaMQbC6FpQrTXiIzTrUp9yqkd02/DmoBuJQtTGEmcLN1atD8eddNqtZLHBwHVrLx9cdla+sYfBNF0der23NXhS8e/lDbysGSzbhU6/Yu6Uu/BdhysQiQb6D7cAN+O/ocHDSwn+ng5M9/nsQqu//kTRV/fnQu6I8GsNFOQK8BDWJiCbj0vPtNk+1GWpmC+S20XmJ1hSsfo+VC8AtcMoj5BqODAcDtfK9CEZDopxpy2dufevCiSuMrBOYEB3OntU0WKvD8mJU6XLi2BczJGdfa5iC9zXVs1K/5u6AY2GoviuRJ7m3tfhfkrCG5LPqtZoZcgmsUbU7V64UUTT2ysq092kqNZZ2cO5Tp+V1ZN14W7XqBHVmS1suy4pVndXatlmtcY5sUdbq6VcTo47bynfW6tKhj+pUZjhqcnYbdtCrzQybFFQbePD+/XgpW5MYbtvgvoG3em0pL2tbekv8qv2+pn4HEIokITwaNxJNs/WbHweqbCJj1WwiH1YUM8nGhOtWmu8zJBFK3w57r9nQjWGd7041NUY+7+6fNT2xNJoNNXbY1nZ5WXKNCEbnyFGpl1JMsMlxpnX6LbZGFkBK9GwM/RkSpmfv2pnC4PizwdmwkUE51ZSwC2RkcYmh4JEaw/C4USZFSe2ccbmjQaPOJKJ3UtO8ubiPlmuVHNaVnAuWJfi9sRyqrY0PiUl/6ZTSSdrKL5bCKsdxW2EUmi9jkurFBZX5djSsGpP1TdKq9xtbp/cxsUvyih3X2gpV7MHuVE5tq7cqVd//vZu0T42ifr/Uhf/lhIRB3YJSwe/qCWzA/6PByXET/49s8T3+fwDa1jmv+wl2bJBMz4Sk7+y8Da7O3FZM4Ty8Egw/yG3ognF+awz60nCWGXN21geSUvvRS1VftXoOtCytur5BblMaJyRVNmmOclLLjVGXz4yq6se18SIqJrZRyp9ZGtV/po2yETK0mSsVDYWQEeX1JuzS3G7kfB5adzcvzpHrlUq2pDtxvu/fZVz9J+UR5fHHG16TXIB5foVT+5k2b4Y1SnoAtbG/6xGvssmvGBqU4udiLhvv30Ng/qpKyap9Q5v8RW+B/aFp7fq/o3NAG9b/48PRaWv/7/hkeLxf/x+Ctl3/72CrH7NMaZS7gwL1pb+1Mvl289JrrUpmJSs2MU1muSjVFqTGaufW0nIdrS2TxXK6JNeuhi2pDZjhg3KbYvmzrdxDapOLzD/mPIgapkODcEYoDxjlVyv6haT0bsILpLI7NfpTygmj71C2NMoF3JWt0kRnLZZFdZZqcQchgn8OLSj4x2hAw/Ujt9+vYhJRpSWdZFq0Nf8UTdlSaPet2hbwkRtYSBKyO5qYnTZsrsjuG7RgfL+GXOdRtATWvBNVJuy+hVtrfbmit1yOXSzqO/hAuGKbsQVjSPsT3NLnt47dxhr/3PW5Hw7aqeu6A1e1DtHuC8z2HurvkZr+XzBDltCYC4k7lLEp/uv48Hgp/uN4f/7jQegAXhKtUXIFWoDrerieIYdJRpmxLZCS8IrEqALvAH6YUQUqS1MhtQI1Q8YgZmLiDlpQHv8VJDKi6Rzt57xaOuGRdwAcY2uJ4OtU4pS+xchZ7j99E8ALzhYguH3TqAQpSmCUY+AFF5e/XGoh0TuA/Oji68eXEFGpvCCmum//OvW9YPJO9u3fImEW982f4qea837FaELCqyyFKTVL6aNAXafeo2BCrrxHgU7Ms5A09h79n3cAr4mkIlPw9OKJ8oJUCmPxvIBGSPquuBS/esFchSLC/u/BCrXiP/9x/vzbJ89efBsk0e5kbJr/g9P2+f/Dk9F+/+dB6AAezwiPkYnY8w4OYO6iPj2/+LReC/ZsntT41JrvaRfUnP+vnpxffP9kp5N/i/Ofo+Ol+T/ax38+DB20ZrX3p58aAeDDn7+eaZ2qcb9PkzhQMxsmY/ybCYli7OeFfVvWp3wqZGIXeML+Q+kFw79NGdG++i0jEr+BP/30Qzv6e4MAU96vFd9Gxnk7in2DjKq8rcdgowzP++BIeGNcL3COTKT2TK3nAxMhYWCP7DMX9el5b968UTPvACTyCKWNtijPnDa7CgL4p+dzm2ieppBHb0c4t19u4J/e3yHCSRaXSZ53UMhzrPMfS5wLvstcDYuMN5iUP1tsciamTqa6tqwDkwZWfq1RafMgOFt8U9ScXCvAUEKM2mciptxPiVLXQkbg+xJjAx3LoGPw/VQKA9wglSKCWw+cFFNQabkAywJ8P1Mo7bH+8x8vzVs5T1/piPIPC22mfCqJbzteeV6tUgh+Bn5U4mUIiuxMzaBXJDcPPLoBF+j4XQ9ESMf9/t2Vse18YFCq6THPu4XvcAG3YKYQ3MJFfszTPJV3OsCtd+sbcn+LfxpP9pd3Wx4Jg1sQ1teHW3hz8/4N3IJhA8VBylu7y2Qyf/q5zFwRiqa0NP1/C296vbLc0kHSRrl6EHn7ndpZ18Y7Hxy43mbsTslWHDllzRL1M9ErK79NxRtH/jpauHWcvLvU8jnmlSUbx+dvgdq/b4a1/Hz7MXBx4UGYZk39h4NB0usu7wLBW6+Mzr6nq94pIsq3l1K+sYWc1mnqoCvyHm5hIgQzLGwIfieDenB9EEmR/jT4uakBYaxbfhWvX7W8jdtf/0Z+E0BNSy2zbiXLiwK6hXRulXYMmtXfiDv1WQ6t6pgA9bOhK2bRp0ZKXyZ14P8gFjq5f+S/ow34f3hy1I7/OjoZ7M9/Pgjd3FTwsucC/mf2/FkVudvOjzCV6MD4j0RyyuO87KrCFmCrS3eUbU252jVTRak9YN4D5gcAzKtmgEgwJTE+oxzXjNmE0CIQbPMAzyHL5oJu+DTLfbz537T/oYxcc9c+e/9iT7Pc5yzgBvt/Mjw5bMf/nh7t938ehNrfs0lK8a1Gbn6p5U/ZmdIieZXj7wu0/qAxw/UP2ksf10PBtRSMofRj5PbGAvtxCWXj+ob5IBieBsPyO7Ebd+1DGEWEauy+cS+f0bBfip3gPJCZpNT+NJDyuzLpWXFWPmWZJGxcnkkDUJTHGSPSpXkAKhQpjqH82hy5IxeqqmMR6jUfEpbOSBGlpsIZJqSKahIp8vOXT18fXrYyABoXLRoFgSq7q+SKlptMVk04f/m09m4qzRSubvkqqNazrei1hrRbfym2zSiZB4G62x6cLnmlMcpr5m6MoMp4ks4rdz6UmALhufsQLDG/RGkYgZqJjEVmfMxRapAYipjTdyV35a7gQbBnkrVxYMyqxNwS6z4ptnknZAESrduS8RrHfFVeKv+9kAiUT8UYij3CmOpi5IciSTJO9aJvB3FxcioyuKSvaOwTGc6oxlBnEvskpb6tDLejP0iig9JXbQl2l2A6P6iRZcfsB3aWGdRmtJDCsbKVrfrEJJlmfPXk8ofSe3b9lnt4ZdEVLVT0lmlZyqco3ZtTKRLLFXmUCuNb2utvGEWuQWUT4/+Xl8SBFsuMH1tLYS9GskeQouUiTzk8Jgmyx0Thg/ed6SPlmw7ZuvfaFwI0X3CN3ciqB9yv7G5jCS5TDBvTMEJlLyVU2gAHMa1sXEVdNgHKePGl5JbovwRB8JcVhdZxtvlViPjK/C3FwLqGLqh2Q+VHl6VJ/LGFdI4TWHvLwgcqQjUmHX23ydQ4emYcsRdWy1c4RYk8rF1+hlxk8QxqH1GMHWeoYSEy68S5O4c6mMuCY1RYJ8oVjdw1Rcr4JOVhsGWTAFuMzxxgdORBcR/CuIh0u3s7GXpeu1gpr9qKJbEie8TG3kZnTDpOp8YTmCNblHeR/hUmmYYoQ9OsExJeXRMZKQhFkhJN7ZbkAmjbZtXJ7n26G+4m6ALSA3ia3x2lykXdjEZ3PIdwVypfWWYoEYjs6kEnIhFKQ4jSDAq2gGspeLyu4iusefNyq0iEytjyEFOt+mKOck7xun8t5BXlsW8U9d2IUfYWLdU/sP90ytw849dNR0Nv/UpFPyGpn19urUVCw875TaQki61XCHu4ePMaYYs1VgkxUWbpXr9MdMhdkeyYlVfQOt2EtDeP1NOyyYr7LvJa7C90/cxoG//fwKH7hAJu8P8Pj4+Hbf//ZLi///9B6HP2/40GO3D/BW97/4IvO/8umqrh+9sXH971F7zL8xd87/jvHf8a7R3/L9jxF3wLvz83bhWtc36mQmz0Gf9LCDuiOOBbkqQsvxk7FxbAk4hqY4l+sY0UxMJMVYmJmGO/canIVs12T9wr+Hawd6mV9qg3py3wXyts9MOh4Cb8d3o6aN3/NBoO9vjvQegzxn/tcXd/KPjfYnJRcWyhwmbmEkBcDhevY8Vm7qeAjU31OxBkqxJ7MLkHkxXtweSXCyab1mEzrlxhKSv6iBCzKTdHm02r9TkAz1ZzboNB17bop4OjW+C//JaLu28Bbjr/MxoO2/d/jk6He/z3EPQZ479i3N0f972wnFp4zyUu4bzq1po6vhMFhwfHdU7NDjyXK7vHcXscV9Eex325OM5Zg834rWbxKtqfCNq1rP2JoIL2J4L2J4L2J4I+mxNB+TqxjWO6cqnYfx/5g9DK//+/CF3bkYwN/v9gOf7H/Nj7/w9Bxv//KP/d/zm7JgtV/Ef/akb86PTfzobTs/1M39Oe9rSnz4H+PwAA//9fYTNqAIwAAA==
                  chart:
                    name: daas-operator
                    version: 0.1.1
                  values: |-
                    image:
                      repository: 804282218731.dkr.ecr.us-west-2.amazonaws.com/daas
                      pullPolicy: Always
                      tag: 0.0.7
                    imagePullSecrets: []
                  release:
                    name: daas
                    namespace: daas
                - bundle: H4sIFAAAAAAA/ykAK2FIUjBjSE02THk5NWIzVjBkUzVpWlM5Nk9WVjZNV2xqYW5keVRRbz1IZWxtAOwb7XLbNjK/8RRb+jqT5EpSX5Yzuunc+OJM22ubdOJeOjeeTAOSKwoxCLAAKEW1fM9+A5CUKFqKZLvntjntD4kEFovFAvsFgAml2pc5Kmqk8hVqWagYdfh8QpUJ5jTjj+4NnU6nMxwM3H+n02n/d3rd7qPu4OT4+KTbG/Q7jzrd45PB4BF07t/1bii0oepR5959tQf3JwGaszeoNJNiBNMeoXm+fO0EnaBLEtSxYrlxRafwNfIMYrs4YCwVfFtEqAQa1ETQDEewZT0RM89xBDTPOYupJUamzX565PcWxP8pbNP/KeUF6t/GAOzU/+FJS/+Hve7xQf8fAnzfJwnN2YgAoKARx2QERhVIAFhGU7QVAApzqZmRaj6CZ51B71mv13120u8GyaUKMFZBof0ZauP3AprRX6WgMx3EMgvt+nIUDE1HwKlBbdx7XnD+g+Qsno/glM/oXNc9/lBwfo6xQqNHcPGWEPxgFP2eCjZGXZX93mL7ZGCb/hvMcjdb4c8T5DkqHZj8jqZgh/73h73huv73Ov3jg/9/ELi6Cp+SFx9yKhIwEwTrxUGO3bNz8wF5Gl5fk6srHxIcM4HgbVkzgW3rgb/CpgU3EJSh5EtLOHhTuhWL+WqKSrEEYWHtjYhh2HePLDsvxmP2ATzfg4oWisQ+Esftc4XUINBlD+OC8zn8UlDOxgwTG2W4cQTkJyxpO3xje7Bj0hBhTAuNoGWGjRimHP2YIU80UIXAWcYMJmAkmAnT8DiaO8mcvTy3uEykoHOMnwTkmzEo5Eh1JcJYCkOZ0FWs5MqYgRnjHCKEQls+NVDHfMXt3oK2bdaFzcZL2daVS/lWKFvr95E/10s6f3FjGX25/wSveFxKpSQSvC5FVrat+VwrvCVzuWLCjMH7XPufa69Fq+x0/+W2+XFtETZm12pQFdPamXUzXC2XEovTCPktZtm1Wk1xe2hNqZfPVeQOC+uuOY0RvL964P3s3V7FZJZJUXKs9+e4xC9ZniDPAj0J3ShGcHUFTMS8SHYPOChZ2o2vkWNspPqu6jZorLRKJKfLfMbW0TwPLpfaHjAZLpOQq6sNTRbwSyENtkR0k0pGBU0x8aN5Sahedeeopixuty9FfF4xf2sht0ftb2SpzMb2kWJpSILNI2NCGypiXB9XU103aUXbkehKDjSOZSGMNaeFxtsM2bU/LZu/3Gb51tGCuGSm5Y4e7xTIyroGT7bRFk0JNOxP3YtXPXh7EbhhYx7O/++O/2x2cL88cFf+Nxwet/K/k2G/f4j/HgJaKuQmu8oDnYrZ/LC5R2TXizXUTAScictw2qU8n9AuuWQiGcEZzRnJ0NCEGmpTx/3tUEPt4Prat5wQqKxjmYQ6XneR4UtnsADBRILCwMDqlA3ULB1LZcbMZH3MLvO0aHXaa3k28t804zdJlUQqXf0oxUYu2yC+luHu28//xjzs1v/17PsulmCX/ndPeq38r3vSOeR/DwIt/V+f7HrZKSpS/AiONRKbl3Hnj+DjDrAdduv/exkFuULfhYKc38EA7ND/XmfQuan/w4P+PwS0/XtETTwJp7U//6eMNrhzb0MysFpEM8qMV+HqnMabGrhyuL72Wi6e5nmF3UhvSzQqhDTu6KjC9eoUcyLlpTeCxiK9We/PkKUT443A63gbqhPkaNDP3Y60NwJXqIs4Rkww+cK9jinjmCwDiVpFSm6aUrLQHNWOkQHUJMutdrsiTb03/hKnqKqqm3nQPnPha+otCcSFYmb+XAqDH8yKO1WIU/0vjWoE3V5/cLxe8ZWSRb6x5qUUr6U0yyMDC9UmD6rG6P1q5awxtqxdxlwRM4JmLLRJaGz4qHFeUNPOMiqSUaPIEg8jJkI9aZX6catgsfYOcAQ/UVYeZNo0tWYOEsy5nGdYpqoRgkKazFuNC2EYh4pTUJJzWRjQhppCNyi4ExB/zcyCL1wcDb5vWIayMF8e679BIls9AGA8keBZJplIb/LZYC4IAu9Gc80RczhulSdSINnUz6uaLtMVUe/gpT9x2O3/VUTj+wUAu/z/YNhv+f9e53D+8zDQ9v9Lz3++5mvuFARUjuePGgf43XsGAm3ZOU2hhZlIxX51HAaXz8pt5lqqryXHu8lSSY6ftDRVwdHx4APNmQs59AguPJrn2ntb3UKozJMtX7nYunqKKnJVKRrvC/A40+5/ZmNa7+1d5+sfTCRMpHeftqgk8EnPni6i9xibagI3mhBL/5amY1+BWSm/xrHtvKFnd9CueuV9ZHF8WiHRNv8f2IXAUiEV3ruPXft/x/32/v+wO+wd/P9DwBH8QI1BJbTNJsoJh9kEBUQF49ZsQU7jS5qiDsgR/DhhGnSR51IZDXqCnEPKZQSZtbFMpF+AQk4NmyLk1Ewa5VQk5AgEpk6Z4HGucMw+YFJunX/2JIBXgs9BCtfSsgQ5KuBMYECCs/Ofz41USI6gOpx+8/wcEqY0CVJmQvdbsk+C6FcVut+6YJKG9qd+1VMRrghFNL4schgzjpo8DfQsJ0+DiF6Sp4HJ7LNULCVP/0OO4A1VTBYavjl7oUmQK2ltHglYgjQs0ZV8T4KpjmWC4Z/BUmy9//316cuvXnz36qsgS+7bxy797x932ve/h/1D/P8gcATPJ1SkyGVKyNERTMvb2MQHmiS1prudh/Vt/w0ICc3ZjfOtFdGuJcoEM4zyxg3ybRfG/Wbs4iIPa6Bm9X7Npj0Q4i/35BzOuzOas3cgBZ//GVTxd4Ft+v/6xenZ9y9+A+Xfrf/dYXfQ1v/+Yf//YeBoqwKSzy7WPgXpvX08MSbXozBkWRroibsmabOliCYphhWy73B9JsZSZc7VU/53beYcvxxzanz9S0EVPoHPLn5sfxKyowOL7zfQ9+njtP09y44+VvhuHN2dfRDysW9irPErT00JWcC3OIcF2GHAAs6qm0L2afmFDSzIwrdQ/tZ/a0/ujSxg7arGAiIpOSzgnVEFvoMFwBLHmeRgdd8eFqCNspHdAt555d17b1OT1aX/9Sa3/gBgI3VD03Wy5Wb/JtzmLYoF2LTeNrh4u0RtHUlvwCH+rYCcFkamKKxWYAJjJesZrncBoNCW8QubJ/mJjDVMu0F30FSTlJlJETkpCKlmUibvwyV6WF0X1mHV7snBRx3gAAd4UPhvAAAA//+jMiLnADwAAA==
                  chart:
                    name: daas-operator-resources
                    version: 0.0.2
                  values: |-
                    dapi:
                      enabled: true
                      image:
                        repository: 804282218731.dkr.ecr.us-west-2.amazonaws.com/daas
                        pullPolicy: Always
                        tag: 0.0.7
                      imagePullSecrets: []
                    extraManifests: []
                  release:
                    name: dapi
                    namespace: daas
profiles:
  - name: deploy-crib-aws
    patches:
      - op: add
        path: deployments.vcluster-daas.helm.values.controlPlane.advanced.serviceAccount.name
        value: vc-daas
      - op: replace
        path: deployments.vcluster-daas.helm.values.rbac.role.enabled
        value: false
  - name: deploy-anvil
    patches:
      - op: add
        path: deployments.vcluster-daas.helm.values.experimental.deploy.vcluster.helm
        value:
          chart:
            name: component-chart
            repo: https://charts.devspace.sh
            version: 0.9.1
          values: |-
            containers:
              - image: ghcr.io/foundry-rs/foundry:latest
                command: [anvil]
                args:
                  - --host
                  - "0.0.0.0"
                  - --port
                  - "8545"
                  - --chain-id
                  - "31337"
                  - --block-time
                  - "10"
                  - --dump-state
                  - /data/anvil/anvil_state.json
            service:
              name: anvil
              type: ClusterIP
              ports:
                - port: 8545
            podSecurityContext:
              fsGroup: 1000
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
          release:
            name: anvil
            namespace: daas
  - name: sync-sa
    patches:
      - op: replace
        path: deployments.vcluster-daas.helm.values.sync.toHost.serviceAccounts.enabled
        value: true
