---
# chart: https://github.com/loft-sh/vcluster/tree/main/chart
version: v2beta1
name: vcluster-daas

require:
  devspace: ">= 6.0"

vars:
  DEVSPACE_ENV_FILE:
    source: env
    default: .env
  # specific
  HOST_NAME:
    source: env
    default: main.stage.cldev.sh

pipelines:
  deploy:
    run: |-
      create_deployments vcluster-daas
  purge:
    run: |-
      purge_deployments vcluster-daas
      kubectl delete pvc data-vcluster-daas-0 --ignore-not-found

deployments:
  vcluster-daas:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: vcluster
        repo: https://charts.loft.sh
      values:
        controlPlane:
          distro:
            k8s:
              enabled: true
              securityContext:
                runAsUser: 12345
                runAsNonRoot: true
          statefulSet:
            security:
              podSecurityContext:
                fsGroup: 12345
              containerSecurityContext:
                runAsUser: 12345
                runAsNonRoot: true
          advanced:
            serviceAccount:
              enabled: true
        rbac:
          role:
            enabled: true
        sync:
          toHost:
            configMaps:
              enabled: true
            ingresses:
              enabled: true
            pods:
              enabled: true
            secrets:
              enabled: true
            services:
              enabled: true
            serviceAccounts:
              enabled: false
        experimental:
          deploy:
            vcluster:
              helm: []

profiles:
  ###########################
  ## vcluster options
  ###########################

  - name: vcluster-crib-aws
    patches:
      - op: add
        path: deployments.vcluster-daas.helm.values.controlPlane.advanced.serviceAccount.name
        value: vc-daas
      - op: replace
        path: deployments.vcluster-daas.helm.values.rbac.role.enabled
        value: false

  - name: vcluster-sync-sa
    patches:
      - op: replace
        path: deployments.vcluster-daas.helm.values.sync.toHost.serviceAccounts.enabled
        value: true

  ###########################
  ## component options
  ###########################

  - name: deploy-cluster-services-console
    patches:
      - op: add
        path: deployments.vcluster-daas.helm.values.experimental.deploy.vcluster.helm
        value:
          chart:
            name: console
            repo: oci://ghcr.io/ajgrande924/registry
            version: 0.1.0
          release:
            name: console
            namespace: daas
          values: |-
            image:
              repository: quay.io/openshift/origin-console
              tag: latest
            securityContext:
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1001
            ingress:
              enabled: true
              className: nginx-internal
              annotations:
                nginx.ingress.kubernetes.io/backend-protocol: HTTP
                external-dns.alpha.kubernetes.io/ttl: "120"
              hosts:
                - host: ${DEVSPACE_NAMESPACE}-console.${HOST_NAME}
                  paths:
                    - path: /
                      pathType: Prefix

  - name: deploy-blockchain-anvil
    patches:
      - op: add
        path: deployments.vcluster-daas.helm.values.experimental.deploy.vcluster.helm
        value:
          chart:
            name: component-chart
            repo: https://charts.devspace.sh
            version: 0.9.1
          release:
            name: anvil
            namespace: daas
          values: |-
            containers:
              - image: ghcr.io/foundry-rs/foundry:latest
                command: [anvil]
                args:
                  - --host
                  - "0.0.0.0"
                  - --port
                  - "8545"
                  - --chain-id
                  - "31337"
                  - --block-time
                  - "10"
                  - --dump-state
                  - /data/anvil/anvil_state.json
            podSecurityContext:
              fsGroup: 1000
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
            service:
              name: anvil
              type: ClusterIP
              ports:
                - port: 8545
            ingress:
              enabled: true
              name: anvil
              ingressClassName: nginx-internal
              annotations:
                nginx.ingress.kubernetes.io/backend-protocol: HTTP
                external-dns.alpha.kubernetes.io/ttl: "120"
              rules:
                - host: ${DEVSPACE_NAMESPACE}-anvil.${HOST_NAME}
                  path: /
                  pathType: Prefix

  - name: deploy-chainlink-daas-operator
    patches:
      - op: add
        path: deployments.vcluster-daas.helm.values.experimental.deploy.vcluster.helm
        value:
          bundle: H4sIFAAAAAAA/ykAK2FIUjBjSE02THk5NWIzVjBkUzVpWlM5Nk9WVjZNV2xqYW5keVRRbz1IZWxtAOxde5PbNpLP3/wUvZrb2sS7pB7zcqlu92rO9mV969guT86pq2wqhsiWhBgEGADUWJ7xffYrAHyLlGTPWH4s8ceYAsHuxqvxQ6MbjghRvkhQEi3k8MGSSB2sScy+ucM0Go1GZycn9t/RaNT8dzSZnHwzPjk/PT8fH5+Y/PHx+cnoGxjdpRBdKVWayG9Gt+bVrNwXkkhCX6JUVPAprCYeSZLi5ygYByMvQhVKmmibdQF/RxZDaIYJzIUEvUR4SMglPMuGEAgO/0hnKDlqVB4nMU6hNsg8vU5wCiRJGA2Joeutqiwn3qduk3+lVJ//K8JSVHetAHbM//HkZNKY/yfj8/N+/h8i+b7vSbRT8YFIuZ7C2PNoTBY49QAkJkJRLeR6CvdHJ5P7k8n4/vnxOIheywBDGaTKv0Kl/UlAYvJWcHKlglDEQzOsPIAkZey5YDRcT+Hx/KnQzyUq5NoD0GQxBZ4ylrF7njJ2iaFErabw8y9WczxboZQ0wikMBt48ZWwj01MoVzTEizC00nsAoUSicQpapugBEM6FtmpGTeH6nQdwBPhaNeSVgqFPJJ/C4N/z578N4Agk/p5SiZHVduRKgVKxB+D0mhEgEdFFg4XJu8QwlVSvHwiu8Y12+aqRacRjTFw9l3RFGS7wkQoJI07XzglTpgIy5RfqqeAvhNBFrWzm/yiUUzg7PT2e5FnfS5EmZV5IEjKjjGqKynADiKRI3BOAb7h7nkQlUhm6EozGVGdlwySdwng0iu2vGGM7DsaT+z9QOzZ+T1HtU9ZDvnpJpOtXj4sIL5FhqIV0zaIFM/rHtZ8pQuZzyqle29efeoZ83amu/zXGCSMa1fDXJbIEpQp0cuulYIf+Pz45a+r/s+OTSa//D5Gur4f3vEdvEsIjC+aMYgMxt88W5gXeveG7d971tQ8RzilHGNTGTGC+GIBfliEp0xC4rcRTQy546WBFVXvDjVFlPISzY/tI48t0PqdvYOAPIKOFPDKPnpXxgVXrQAoOZj1Yw+8pYXROMTKA0kofeD+ho23La8PB1ETBDEOSKgQlYqyAVFfnOUUWKSASnQ7ECLQAvaQKvp2tHdB9emnKUr4AlWD4XeA9noNEhkRlDRcKrgnlKkPINo9quKKMwQwhVUZOBcQKn0m7o3nzZa9sYjovWrS5JuYt1/l+n1ZnqqDzb7YG07/u362ljEVbOCLBC9dQ7ttczlrmewqXSMr1HAZ/VP4f1aBByzHdf5C1P9aGXqVPzWzJNi2mP22/ZoPElWJkhmxn39qyZcc2K1Rta/ec7c3gxiAzRkKEwZ8HMPh18P7TScSx4E5OtUtOV8oJukQWB2o5tLJP4foaKA9ZGnVVLnDsu0qpDAk8yVgElRGUVfqi2JOadyRJgtfF3A2oGBa7x+vrlk9u4PdUaGw0wiaVmHCywMifrR2hfDRdOoDZ2og5jNmzGZt19VsFcdCyu8WcMgjaa0G50oSHWK9Ddcq1jeym4s9ANRCHqo0iTBXurl4Vij/t0ln1YoGD69BYPr7tqHypDYPvuijyam0r+iKnPcgeBnsR2NAJn3rFvtvUhf8iTJhYx8jvwBy4A/+dHI/OGvjvfHTW47+DpKr9jySJGq7G3mvKoyk8LEaAF6MmEdFkWux8u9VTZYaa2QKZbnS7RKsK2r9jxQJwA5zyCLmGE0PBQK3MFsFoSJRTbdnMrZouHLtcyTqGMdHh8klFgq0ybC5GpSxnjnw+QzLylYbJaV9RvSzkq1sHHAmTqlaJLMt9rcX/kpjVON8vP6uoIZfBalX74MoVLPLGbq1M005TirFhwblNnTbXkW3jrW3VCarENkwum4KVndUw27RLnCFblJV6+uXEqOK24putsnTIozqFGU/qlJ3BDgaVmWGzgtKAB+/eTTdea7KAmya4r+GtQZPL84pJb4Neae+ry3cEoYhjwqNpLdM027B+OFC+JnKh6k3kQ0sxk21UuG7k+T5DEqH07bD36g1dG9aZdaouMfJVd/9s6YmN0WxSzcK2tcuLkltYMLpCjko9l2KGdYpLrZPvsTGyABKil1MYLpEwvXzbfCkMjr8/uj+uvaCcakrYQ2RkfYmh4JGawvi0ViZBSe2ccW8no1qdSUQ/SEzz5fo2Um4VclwVciVYGuMPRnOopjQ+xCb/uRNKx0njfb4Ulm8ctRalUP8Y40SvH1KZmaOhbUxWjaRl79dMp7dRsRv8cotrZYXKbbB3yqdi6i1LVe2/H8btU6OoLzd14X85I2FQ1aBU8A/dCezA/5PR2Wkd/09s8R7/HyDtuzmv7hPs2CCpXgpJ39p5G7y+70wx+ebhhWD4XtuGLhjnN8agLw1lmTKnZ30gCbWHXqo81Ro40LKx6voGuc3pIiaJslkrlLPK2wXq4plRVf64MruIkohtlOJnmkTVn0mtbIQM7ctWQUMhZER5tQm7JLeGnM9D6u7mxRVy3Spkg7tj5/v+h4yr/6Q8onzx8YbXLGNgnl/g3B7TZs2wRUgPoDL273rEq3T2G4YGpfgZm8va97dgmH2qEtJmN7TZX7UJ7F86bV3/78gPaKf9b8P/7/RsPO7X/0Okfdf/D9DVD1iqNMq7gwJ3ufRbs4EzVlV+W8bZqcdG/j4LW7Fy7libG8tvvlS31okkmcwttSrN9J9KOtN3QbgklAeM8tedgpKEli0aCV7++E3MIqq0pLNUC1nmC0lCdqetXkc5H6uWwznlhNG3KOsVbstv1L2tSNYMzVeNFikqc3vxlSY6bYjeyGuK3Xidi1zJ3gJaO3qltSIc9ZWQrylf7MDLlC8kqg7IfIBpsQ0mtgpcAZ6qlnngCdBU9IU6b+DNu9Dod3A61GJjaqxhpHn+snH20mFqqtDPcO/tFsE73bfcwT6luj7fdlXutydfaKrj/2CJLKYLLiTeIY9d8T+nx6cb/v+n/fn/QdIRPCdao+QKtADX9XC1RA6zlDKjXiAh4WuyQBV4R/DjkipQaZIIqRWoJTIGCyZm7qCd8sVfQCIjmq7QHudU8gmPvCPguLDKCL5NJM7pG4yc8v7DdwE842wNgtsvjUiQoARGOQZe8PDy10stJHpHkLmuvXxwCRGVygsWVA/tXye+F8zeyqH9m2csF0PzJ/+pVnxYEpqR8HWawJyatfZeoK4S714wI6+9e4GOzbOQdOHd+z/vCF4SSUWq4PHDR8oLEimM0vMCGiEZuuJS/OYFKxWKCIdfgiJqxP/9/eLp94+ePPs+iKO747Fr/o+b9v/x8dlxH/93kHQED5aEL5CJhecdHcHKheB5OTqEUEYK/myRaFlg3ChQvhmZN9mpbCVOsH7I/6kr3aci1ef/i0cXD394dKeTfw/73+S0Gf9xPOnj/w6TjhpT0/vDz7UA4Mkv3y61TtR0OKTxIlBLGyZhtjgzEi1wmBX2bVmf8rmQsV3gCfsPpdcM/zpnRPvq95RI/A7+8POPzejfHQxMeb9SfB8eF80o5h08yvK2HqOdPDzvvSOhjYZ8iCtkIrE+lZ4PTISEgXXZZi7qz/NevXqllt4RSOQRSuttX/gc1rsKAvin53ObaZ7mkEXvRriylnv4p/c3iHCWLooszzvK+TnS2Y8NyjndTaqGRMprRIqfDTIZEVMnU11b1oFJAyu/1ai0eRCcrb/La06uFGAoYYHaZ2JBuZ8Qpa6EjMD3JS4MdCyCTsH3EykMcINEighuPHBcTEGl5RosCfD9VKG0bt0XP12arzKavtIR5e8X2kr5XBLfdrzyvEqlEPwU/KjAyxDkr1O1hEGeXXd4cwMu0Iu3AxAhnQ6HHy6Mbecjg1JNj3neDfwD13ADZgrBDTzM3PzMUxHTDzfejW+S+5v/U3uyv7ybwiUIbkDY7T7cwKvrd6/gBgwZyB3pbqzRybz8+ZfiZUsoktLS9P8NvBoMinIbjoS1ctUg4uY3FV/H2jfvHbjcJOy8JEuKnLJ6iapPbGvl96l4zeWro4Ub7sTdpTb9WFtL1tynb4Dav6/GlfeZnTJwccFBmKR1+cejUTzoLu8CgRufTO7/QNu+ySOK9+dSfLEHn4Y3bdAVeQ03MBOCGRI2BLuTQDW4OoikSH4e/VKXgDDWzb+M1y5b3sZtb/8iiwSvSKll2i1kESjezaTTWtoxaNrPCDvl2Qyt6ZgAVd/Alln0qZHS15k68H+wEDq+feS3Szvw//jspBn/c3I26v3/DpKur0t4OXAB30vrf1RGbjbfR5hIdGD8JyI55YusbFthC7DVpXNl2lKucs1QXqoHzD1gPgBgbpsBIsaELPAJ5bhlzMaE5oFAuwd4Bll2F3TDp17u483/uv4PZeSau+Is8Kv1CriNL9h2/T8eTY7Pm/Gf573/92FS80ibJBTfaOTml9o8zU6VFvGLDH8/RLsfNGq4eqa9cb4eCq6lYAylv0BuI9bt4RLKWvj+ahSMz4NxcVTsxl3TdSWPUFy4Y+5NzxZ7WOwYZ4GsJKH2p4GU/yiynuSOEQlLJWHTiouSonyRMiJdngegQpHgFIoD58iD/P6HjFUe6rMaE5YsSR6lpMIlxqSMahEJ8ovnj18eXzZeANQu2jMCAlXWquSKFkYmKyZcPH9c+TaRZgqXtzzlqdKztfwGtxu/8RYM/TwI0EX7O1mySmOU1czdGECV2Um6XbnbQ4k5EJ5tH4IN4pcoDSFQS5GyyIyPFUoNEkOx4PRtQV25K1gQrE+qNhsYsyoxt8S6I8Um7ZisQaLdtqS8QjFblTfK/yAkAuVzMYXcRrigOh/5oYjjlFO9HtpBnPs7RQaXDBVd+ESGS6ox1KnEIUmobyvD7egP4uio2Ks2GLtLEN0+qPbKjtn37CwzqM1oIfnGyla27BOTZZrxxaPLH4vds+u3bIdXFG1poby3TMtSPkfpvpxLEVuqyKNEmL2lvf6EUeQaVDoz+//ikjDQYpPwA6sp7MU49igp2izymMMDEiN7QBQevO9MHynfdMjevdcMCK9/4Bq79qoacN3a3UYTXCYY1qZhhMpeSqe0AQ5iXuq4MnXpBCjihTeyG6z/FATBn1oKbaNs35chwq3v92QD2xo6T5UbCj86L00WH5tJ5ziBrVH27ykI1Rh39N0uVePSE7MRe2alfIFzlMjDyuVXyEW6WELlEMXocYYa1iK1mzh350wHcZlTjHLtRLmikbumRpk9SeEPtqkSYI/xmQGMjneQx8NPc2/yD28nk55WLtbJqtayJJbJutjY28iMSsf53OwEVsjWxV2Uf4FZqiFK0TTrjISvr4iMFIQiToim1iS5BtrUWdVkbZ/uhrMZuoDkAB5ndwepYlE3o9G55xDuSmUryxIlApFdPehYxEJpCFGaQcHWcCUFX2yreIs2r19uFIlQGV0eYqLVUKxQriheDTOHYN8I6rsRo+wtSmp4ZP/p5Ll7xm+bjia98UsR/Zgkfna5sRYxDTvnN5GSrDent3NZ/mhqufXOkUaRKKLu0PP5zjm0R/O9t17c0tLIyYzhBjT6QEYzIRgS3lpmKdTG1QQfyGZL22S9/YARpZ5uUUd3x9Fer3AQLvaM/1OulNmpw0ebSvrTVrAbTdqAi9140harIUoxM222A1J28G3JdsSK64qdbELaW2qqeems5W6UrBb95b8HSPvY/8x26DahoDvOf45PT8dN+9/ZuPf/PEj6nO1/RoI7MP8J3rT+Cb5p/MsjEiu2P/vh4U1/gndZ/gTvDX+94a+SesPfV2z4E3wPu59o7mG2Qde5EDsh8X8JYUcUB3xD4oRlN6NnzAJ4FFFtNNGvtpGChTBTVWIsVjisBZTu1Wy3xLKC7wdlN1qpR7JZ2gP/NYK93x8K7sJ/5+ejxv1fk/Gox38HSZ8x/muOu9tDwf8Ws4clxQYqrL/cAIhtt1SUWLH+9lPAxrr4HQiyUYkeTPZgskw9mPx6wWRdO+zGlS2askwfEWLW+WZos661Pgfg2WjOfTDo1hb9dHB0D/yX3ebz4SbAnf5/m/e/Ts5Pe/x3iPQZ47983N0e9z2zlBp4z2Vu4LzqrWMlvhM5hYPjOidmB57LhO1xXI/jytTjuK8XxzltsBu/VTRemXqPwLvm1XsE5qn3COw9AnuPwN4jsPcI7D0CW7j0HoGfr0dghin3MWK1wsr+LPULTnX7X7YttnH2d/W/P+xx/+O4Gf97Ojnvz38Pknzf94q9X2Xr5O5asAvf6Wg0tkZhr7aRgwt2RdYm0+yCXPl+ZvapT33q05eS/j8AAP//LCDBYwCSAAA=
          chart:
            name: daas-operator
            version: 0.1.2
          release:
            name: daas
            namespace: daas
          values: |-
            image:
              repository: 804282218731.dkr.ecr.us-west-2.amazonaws.com/daas
              pullPolicy: Always
              tag: 0.0.8
            imagePullSecrets: []

  - name: deploy-chainlink-daas-api
    patches:
      - op: add
        path: deployments.vcluster-daas.helm.values.experimental.deploy.vcluster.helm
        value:
          bundle: H4sIFAAAAAAA/ykAK2FIUjBjSE02THk5NWIzVjBkUzVpWlM5Nk9WVjZNV2xqYW5keVRRbz1IZWxtAOw7e4/bNvL5m59iqv0VSPKrKL92N/ChOOxlg7bXNgmyvRSHIGgoaSwzS5EqSXnjrnOf/UBKsmWtHe+j2LY5zx+2JA6HwyHnxUfKmAlVgZpZpUONRpU6QRM9nTJt6Zzl4sGdodfr9Y5GI//f6/W6/71Bv/+gPzo+PD7uD0fue//weDR6AL27N70bSmOZftC7c1vdzv1FgBX8NWrDlRzDbEBYUSxfe7RH+yRFk2heWP/pBL5FkUPiJgdMlIbvyxi1RIuGSJbjGLbMJ2LnBY6BFYXgCXPEyKzdzpD80YL4H4Vt+j9jokTz+xiAXfo/PBp19P9o0B/u9f8+IAxDkrKCjwkAShYLTMdgdYkEgOcsQ1cAoLFQhlul52N40hsNngwG/SfHwz5NzzXFRNPShBdobDigLGe/KckuDE1UHrn55SlYlo1BMIvG+veiFOKlEjyZj+FEXLC5aVp8WQpxholGa8bw5i0BMKhnPKlZqSzJU1Eai/q7l66WzDQaUxUvOzFhwiAh+MFq9iOTfIKmJvhHy/zPBNv032Je+NGKfpmiKFAbaotbmoId+j88Ghyt6/+gNzzc+/97gcvL6DF59qFgMgU7RXBeHNTEP3s3T8nj6ONHcnkZQooTLhGCLXOGuroBhCtsVgoLtAolnzvC9HXlVhzmixlqzVOEhbM3MoGjoX/k+Vk5mfAPEIQB1LRQpu6ReG6famQWgS1bmJRCzOHXkgk+4Zi6KMP3g5KfsaLt8a1rwfXJQIwJKw2CUTm2Ypiq9xOOIjXANILgObeYglVgp9zAw3juJXP6/MzhcpmBKTB5RMl3E9AokJlahImSlnFp6ljJf+MWLrgQECOUxvFpgHnma26vLWhXZ13YfLKUbVO4lG+NsrX8OvIXZknn/3xfxl9ff4BXPC6lUhGhryqRVXUbPtc+3pC5QnNpJxB8acIvTdChVTV6/em2+XFtErZG12lQHdO6kfUjXE+XCkuwGMUNRtnXWg1xt2ttqVfPdeQOC+euBUsQgv8PIPgluLmKqTxXsuLYXJ/jCr9ieYoip2Ya+V6M4fISuExEme7uMK1Y2o1vUGBilf6hbpa2ZlotkpNlPuPKWFHQ86W2U66iZRJyebmhygJ+LZXFjoiuUsmZZBmmYTyvCDWz7qyKWzaK+Kxm/sZC7vY63MhSlY1dR4qVIaGbe8alsUwmuN6vtrpu0oquI6njN2BJokppnTktDd6ky77+SVX9+TbLt45Gk4qZjjt6uFMgK+tKH22jLdsSaNmfppWgfgiuReCKjbk//787/nPZwd3ywB3xX78/6q7/HB8N+vv47z6go0J+sOsUyquYyw/ba0RuvjhDzSUVXJ5Hsz4TxZT1yTmX6RhOWcFJjpalzDKXkF3fDrXUDj5+DB0nBGrrWKV2ntddZMTSGSxAcpmitDByOuUCNUfHUbngdrreZ595OrQm7XU8W/VvlourpCoita5+kmIrl20RX8tw79qOWTmZVaZ8d+6rnLpmuk6wr031DzFle7gF7Lb/6wsot/EEu9b/+seDTv7fP+7t8/97gY79Xx/sRpU1kxl+Asc5ic2mofdniHH2sB126/97FdNCY+hTASFuYQB26P+gN+pd1f+jvf7fB3Tju5jZZBrNmnjunyreEM4FG5LB1SS6YNwGNa4pWLKpgv8OHz8GnRCPFUWN3VreqNCYlMr6rcMaN2iWGKZKnQdjaE3Sq+XhBfJsaoMxBL1gQ3GKAi2Ghd+RCMbgP5oySRBTTL/yrxPGBabLQLJRkYqbtpQctHu1o2cADclqq8XNSNvsjTzHGeq66GoefJ2xCA0LlgSSUnM7f6qkxQ92xZ0u5Yn5l0E9hv5gODpcL/hGq7LYWPJcyVdK2eWWkYN6kQ91q/dhPXPWGFuWLmPumFvJch6dlzEmVoxb+0UN7TxnMh23PjniUcxlZKadr2HS+bBYewc4gJ8Zrzay7RSXzEGKhVDzHKulihhBI0vnncqltFxAzSloJYQqLRjLbGlaFPwOWLhmZiGUPo+CMLQ8R1Xarw/N3yBVnRYAMJkqCByTXGZX+WwxRykNrlQ3ArGAw873VEkkm9p50dDlpiYa7L30Zw67/b+OWXK3AGCX/x8dDTv+f9Db7//dD3T9/9Lzn635mlsFAbXj+bPGAWH/joFAV3ZeU1hpp0rz3zyH9PxJtc3QSPWVEng7WWol8LOWpi4Feh5CYAX3IYcZw5uAFYUJ3tanUGrz5L6vXGxTPEMd+6IMbfAVBIIb/3/hYtrg7W3H6x9cplxmtx+2uCLwWY+eKeP3mNh6ADeaEEf/hqbjugJzUn6FE9d4S89uoV3NzPvE5Pi8QqJt/p+6icAzqTTeuY1d63+Hw8Pu+b/+0WDv/+8DDuAlsxa1NC6bqAYcLqYoIS65cGYLCpacswwNJQfw05QbMGVRKG0NmCkKAZlQMeTOxnKZfQUaBbN8hlAwO219ZzIlByAx88oEDwuNE/4B02rz4YtHFF5IMQclfU3HEhSoQXCJlNDTs1/OrNJIDqA+nPD66RmkXBtCM24j/1uxT2j8m478b/NhmkXup3k1MxmtCMUsOS8LmHCBhjym5qIgj2nMzsljanP3rDTPyOP/kAN4zTRXpYHvTp8ZQgutnM0jlKfIogpdq/eEzkyiUoz+CpZi6/n/b0+ef/Pshxff0Dy9axu79H80GnTP/x8N9+t/9wIH8HTKZIZCZYQcHMCsOo1PQmBp2mi6X3lIWcGXJzmiZk/QL12tag421VzfMNhGurszuiLad0S55JYz0bp7sO2qQdiOenzM4kzbRbPSs2n1hITL1TyP8+6UFfwdKCnmfwUlvgNs0/9Xz05Of3z2Oyj/Nc5/HB8Ou/o/7O/9/73AwVY1Il+8WbsKNHz7cGptYcZRxPOMmqk/JuuypZilGUY1cuhxQy4nSufe1TPxd2PnAr+eCGZD82vJND6CL9781L0StKMBhx+20K/Txkn3PtOONlb4vh/9nW0Q8qk7Uc6EVbumhCzge5zDAlw3YAGn9Ukx97S8YQULsggdVL/N39qTfyMLWDuqs4BYKQELeGd1ie9gAbDE8YaVru5bwAKM1S6yW8C7oLp7EWyqsrr0sV7lxhdANlK3LFsnWy32b8Jtn6JZgEvrXYU3bzuolUfaIBN/FWQduXZk1Faj0WJjebNkxUlnx3sDCyS8EZCT0qoMpVM6TGGiVTOBmkUGKI1j6I1Lw8JUJQZmfdof0cFqAmfcTsvYC1kqfaFU+j5aokf1aXQT1fUefeaObA972MON4b8BAAD//+5mL9QAPgAA
          chart:
            name: daas-operator-resources
            version: 0.0.3
          release:
            name: dapi
            namespace: daas
          values: |-
            dapi:
              enabled: true
              image:
                repository: 804282218731.dkr.ecr.us-west-2.amazonaws.com/daas
                pullPolicy: Always
                tag: 0.0.8
              imagePullSecrets: []
              service:
                type: ClusterIP
              ingress:
                enabled: true
                annotations:
                  nginx.ingress.kubernetes.io/backend-protocol: HTTP
                  external-dns.alpha.kubernetes.io/ttl: "120"
                ingressClassName: nginx-internal
                host: ${DEVSPACE_NAMESPACE}-dapi.${HOST_NAME}
                path: /
                pathType: Prefix
