ccipScriptsDeployment:
  extraEnvs:
    - name: AWS_IAM_ENABLED
      value: "false"

crib-chainlink-cluster:
  chainlink:
    nodes:
      node1:
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
  db:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
    statefulSet:
      enabled: false
  geth:
    enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
    statefulSet:
      enabled: false
  ingress:
    ingressClassName: nginx
  mockserver:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
