// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package ccip_offramp

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Commits a report to the router, with price updates only.
//
// The method name needs to be commit with Anchor encoding.
//
// This function is called by the OffChain when committing one Report to the SVM Router,
// containing only price updates and no merkle root.
//
// # Arguments
//
// * `ctx` - The context containing the accounts required for the commit.
// * `report_context_byte_words` - consists of:
// * report_context_byte_words[0]: ConfigDigest
// * report_context_byte_words[1]: 24 byte padding, 8 byte sequence number
// * `raw_report` - The serialized commit input report containing the price updates,
// with no merkle root.
// * `rs` - slice of R components of signatures
// * `ss` - slice of S components of signatures
// * `raw_vs` - array of V components of signatures
type CommitPriceOnlyInstruction struct {
	ReportContextByteWords *[2][32]uint8
	RawReport              *[]byte
	Rs                     *[][32]uint8
	Ss                     *[][32]uint8
	RawVs                  *[32]uint8

	// [0] = [] config
	//
	// [1] = [] reference_addresses
	//
	// [2] = [WRITE, SIGNER] authority
	//
	// [3] = [] system_program
	//
	// [4] = [] sysvar_instructions
	//
	// [5] = [] fee_billing_signer
	//
	// [6] = [] fee_quoter
	//
	// [7] = [] fee_quoter_allowed_price_updater
	// ··········· so that it can authorize the call made by this offramp
	//
	// [8] = [] fee_quoter_config
	//
	// [9] = [] rmn_remote
	//
	// [10] = [] rmn_remote_curses
	//
	// [11] = [] rmn_remote_config
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewCommitPriceOnlyInstructionBuilder creates a new `CommitPriceOnlyInstruction` instruction builder.
func NewCommitPriceOnlyInstructionBuilder() *CommitPriceOnlyInstruction {
	nd := &CommitPriceOnlyInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 12),
	}
	return nd
}

// SetReportContextByteWords sets the "report_context_byte_words" parameter.
func (inst *CommitPriceOnlyInstruction) SetReportContextByteWords(report_context_byte_words [2][32]uint8) *CommitPriceOnlyInstruction {
	inst.ReportContextByteWords = &report_context_byte_words
	return inst
}

// SetRawReport sets the "raw_report" parameter.
func (inst *CommitPriceOnlyInstruction) SetRawReport(raw_report []byte) *CommitPriceOnlyInstruction {
	inst.RawReport = &raw_report
	return inst
}

// SetRs sets the "rs" parameter.
func (inst *CommitPriceOnlyInstruction) SetRs(rs [][32]uint8) *CommitPriceOnlyInstruction {
	inst.Rs = &rs
	return inst
}

// SetSs sets the "ss" parameter.
func (inst *CommitPriceOnlyInstruction) SetSs(ss [][32]uint8) *CommitPriceOnlyInstruction {
	inst.Ss = &ss
	return inst
}

// SetRawVs sets the "raw_vs" parameter.
func (inst *CommitPriceOnlyInstruction) SetRawVs(raw_vs [32]uint8) *CommitPriceOnlyInstruction {
	inst.RawVs = &raw_vs
	return inst
}

// SetConfigAccount sets the "config" account.
func (inst *CommitPriceOnlyInstruction) SetConfigAccount(config ag_solanago.PublicKey) *CommitPriceOnlyInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(config)
	return inst
}

// GetConfigAccount gets the "config" account.
func (inst *CommitPriceOnlyInstruction) GetConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetReferenceAddressesAccount sets the "reference_addresses" account.
func (inst *CommitPriceOnlyInstruction) SetReferenceAddressesAccount(referenceAddresses ag_solanago.PublicKey) *CommitPriceOnlyInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(referenceAddresses)
	return inst
}

// GetReferenceAddressesAccount gets the "reference_addresses" account.
func (inst *CommitPriceOnlyInstruction) GetReferenceAddressesAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *CommitPriceOnlyInstruction) SetAuthorityAccount(authority ag_solanago.PublicKey) *CommitPriceOnlyInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(authority).WRITE().SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *CommitPriceOnlyInstruction) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "system_program" account.
func (inst *CommitPriceOnlyInstruction) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *CommitPriceOnlyInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "system_program" account.
func (inst *CommitPriceOnlyInstruction) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetSysvarInstructionsAccount sets the "sysvar_instructions" account.
func (inst *CommitPriceOnlyInstruction) SetSysvarInstructionsAccount(sysvarInstructions ag_solanago.PublicKey) *CommitPriceOnlyInstruction {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(sysvarInstructions)
	return inst
}

// GetSysvarInstructionsAccount gets the "sysvar_instructions" account.
func (inst *CommitPriceOnlyInstruction) GetSysvarInstructionsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetFeeBillingSignerAccount sets the "fee_billing_signer" account.
func (inst *CommitPriceOnlyInstruction) SetFeeBillingSignerAccount(feeBillingSigner ag_solanago.PublicKey) *CommitPriceOnlyInstruction {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(feeBillingSigner)
	return inst
}

// GetFeeBillingSignerAccount gets the "fee_billing_signer" account.
func (inst *CommitPriceOnlyInstruction) GetFeeBillingSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetFeeQuoterAccount sets the "fee_quoter" account.
func (inst *CommitPriceOnlyInstruction) SetFeeQuoterAccount(feeQuoter ag_solanago.PublicKey) *CommitPriceOnlyInstruction {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(feeQuoter)
	return inst
}

// GetFeeQuoterAccount gets the "fee_quoter" account.
func (inst *CommitPriceOnlyInstruction) GetFeeQuoterAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetFeeQuoterAllowedPriceUpdaterAccount sets the "fee_quoter_allowed_price_updater" account.
// so that it can authorize the call made by this offramp
func (inst *CommitPriceOnlyInstruction) SetFeeQuoterAllowedPriceUpdaterAccount(feeQuoterAllowedPriceUpdater ag_solanago.PublicKey) *CommitPriceOnlyInstruction {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(feeQuoterAllowedPriceUpdater)
	return inst
}

// GetFeeQuoterAllowedPriceUpdaterAccount gets the "fee_quoter_allowed_price_updater" account.
// so that it can authorize the call made by this offramp
func (inst *CommitPriceOnlyInstruction) GetFeeQuoterAllowedPriceUpdaterAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetFeeQuoterConfigAccount sets the "fee_quoter_config" account.
func (inst *CommitPriceOnlyInstruction) SetFeeQuoterConfigAccount(feeQuoterConfig ag_solanago.PublicKey) *CommitPriceOnlyInstruction {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(feeQuoterConfig)
	return inst
}

// GetFeeQuoterConfigAccount gets the "fee_quoter_config" account.
func (inst *CommitPriceOnlyInstruction) GetFeeQuoterConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetRmnRemoteAccount sets the "rmn_remote" account.
func (inst *CommitPriceOnlyInstruction) SetRmnRemoteAccount(rmnRemote ag_solanago.PublicKey) *CommitPriceOnlyInstruction {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(rmnRemote)
	return inst
}

// GetRmnRemoteAccount gets the "rmn_remote" account.
func (inst *CommitPriceOnlyInstruction) GetRmnRemoteAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetRmnRemoteCursesAccount sets the "rmn_remote_curses" account.
func (inst *CommitPriceOnlyInstruction) SetRmnRemoteCursesAccount(rmnRemoteCurses ag_solanago.PublicKey) *CommitPriceOnlyInstruction {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(rmnRemoteCurses)
	return inst
}

// GetRmnRemoteCursesAccount gets the "rmn_remote_curses" account.
func (inst *CommitPriceOnlyInstruction) GetRmnRemoteCursesAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetRmnRemoteConfigAccount sets the "rmn_remote_config" account.
func (inst *CommitPriceOnlyInstruction) SetRmnRemoteConfigAccount(rmnRemoteConfig ag_solanago.PublicKey) *CommitPriceOnlyInstruction {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(rmnRemoteConfig)
	return inst
}

// GetRmnRemoteConfigAccount gets the "rmn_remote_config" account.
func (inst *CommitPriceOnlyInstruction) GetRmnRemoteConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

func (inst CommitPriceOnlyInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_CommitPriceOnly,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst CommitPriceOnlyInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *CommitPriceOnlyInstruction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.ReportContextByteWords == nil {
			return errors.New("ReportContextByteWords parameter is not set")
		}
		if inst.RawReport == nil {
			return errors.New("RawReport parameter is not set")
		}
		if inst.Rs == nil {
			return errors.New("Rs parameter is not set")
		}
		if inst.Ss == nil {
			return errors.New("Ss parameter is not set")
		}
		if inst.RawVs == nil {
			return errors.New("RawVs parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Config is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.ReferenceAddresses is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SysvarInstructions is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.FeeBillingSigner is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.FeeQuoter is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.FeeQuoterAllowedPriceUpdater is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.FeeQuoterConfig is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.RmnRemote is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.RmnRemoteCurses is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.RmnRemoteConfig is not set")
		}
	}
	return nil
}

func (inst *CommitPriceOnlyInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("CommitPriceOnly")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=5]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("   ReportContextByteWords", *inst.ReportContextByteWords))
						paramsBranch.Child(ag_format.Param("                RawReport", *inst.RawReport))
						paramsBranch.Child(ag_format.Param("                       Rs", *inst.Rs))
						paramsBranch.Child(ag_format.Param("                       Ss", *inst.Ss))
						paramsBranch.Child(ag_format.Param("                    RawVs", *inst.RawVs))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=12]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                          config", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("             reference_addresses", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("                       authority", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("                  system_program", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("             sysvar_instructions", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("              fee_billing_signer", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("                      fee_quoter", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("fee_quoter_allowed_price_updater", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("               fee_quoter_config", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("                      rmn_remote", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("               rmn_remote_curses", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("               rmn_remote_config", inst.AccountMetaSlice.Get(11)))
					})
				})
		})
}

func (obj CommitPriceOnlyInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `ReportContextByteWords` param:
	err = encoder.Encode(obj.ReportContextByteWords)
	if err != nil {
		return err
	}
	// Serialize `RawReport` param:
	err = encoder.Encode(obj.RawReport)
	if err != nil {
		return err
	}
	// Serialize `Rs` param:
	err = encoder.Encode(obj.Rs)
	if err != nil {
		return err
	}
	// Serialize `Ss` param:
	err = encoder.Encode(obj.Ss)
	if err != nil {
		return err
	}
	// Serialize `RawVs` param:
	err = encoder.Encode(obj.RawVs)
	if err != nil {
		return err
	}
	return nil
}
func (obj *CommitPriceOnlyInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `ReportContextByteWords`:
	err = decoder.Decode(&obj.ReportContextByteWords)
	if err != nil {
		return err
	}
	// Deserialize `RawReport`:
	err = decoder.Decode(&obj.RawReport)
	if err != nil {
		return err
	}
	// Deserialize `Rs`:
	err = decoder.Decode(&obj.Rs)
	if err != nil {
		return err
	}
	// Deserialize `Ss`:
	err = decoder.Decode(&obj.Ss)
	if err != nil {
		return err
	}
	// Deserialize `RawVs`:
	err = decoder.Decode(&obj.RawVs)
	if err != nil {
		return err
	}
	return nil
}

// NewCommitPriceOnlyInstruction declares a new CommitPriceOnly instruction with the provided parameters and accounts.
func NewCommitPriceOnlyInstruction(
	// Parameters:
	report_context_byte_words [2][32]uint8,
	raw_report []byte,
	rs [][32]uint8,
	ss [][32]uint8,
	raw_vs [32]uint8,
	// Accounts:
	config ag_solanago.PublicKey,
	referenceAddresses ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	sysvarInstructions ag_solanago.PublicKey,
	feeBillingSigner ag_solanago.PublicKey,
	feeQuoter ag_solanago.PublicKey,
	feeQuoterAllowedPriceUpdater ag_solanago.PublicKey,
	feeQuoterConfig ag_solanago.PublicKey,
	rmnRemote ag_solanago.PublicKey,
	rmnRemoteCurses ag_solanago.PublicKey,
	rmnRemoteConfig ag_solanago.PublicKey) *CommitPriceOnlyInstruction {
	return NewCommitPriceOnlyInstructionBuilder().
		SetReportContextByteWords(report_context_byte_words).
		SetRawReport(raw_report).
		SetRs(rs).
		SetSs(ss).
		SetRawVs(raw_vs).
		SetConfigAccount(config).
		SetReferenceAddressesAccount(referenceAddresses).
		SetAuthorityAccount(authority).
		SetSystemProgramAccount(systemProgram).
		SetSysvarInstructionsAccount(sysvarInstructions).
		SetFeeBillingSignerAccount(feeBillingSigner).
		SetFeeQuoterAccount(feeQuoter).
		SetFeeQuoterAllowedPriceUpdaterAccount(feeQuoterAllowedPriceUpdater).
		SetFeeQuoterConfigAccount(feeQuoterConfig).
		SetRmnRemoteAccount(rmnRemote).
		SetRmnRemoteCursesAccount(rmnRemoteCurses).
		SetRmnRemoteConfigAccount(rmnRemoteConfig)
}
