---
version: v2beta1
name: geth

vars:
  LOCAL_TEMPLATES_DIR:
    source: env
    default: ./templates
  # Optional property useful for generating n number of additional chains
  ADDITIONAL_CHAINS_COUNT:
    source: env
    default: 2

pipelines:
  kind:
    run: |-
      ensure_pull_secrets --all
      run_pipelines deploy
  deploy:
    run: |-
      create_deployments geth

hooks:
  - wait:
      running: true
      terminatedWithCode: 0
      timeout: 600
    container:
      labelSelector:
        # vars don't work here, = releaseName
        release: "geth"
    events: ["after:deploy:geth"]

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  geth:
    updateImageTags: false
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      releaseName: "geth"
      chart:
        name: "${CHAINLINK_HELM_REGISTRY_URI}/crib-geth"
        version: "1.0.0"
      # for simplicity, we define all the values here
      # they can be defined the same way in values.yml
      # devspace merges these "values" with the "values.yaml" before deploy
      values:
        securityContext:
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 999
          runAsGroup: 999
        version: v1.12.0
        wsRpcPort: 8546
        httpRpcPort: 8544
        chains:
          - networkId: 1337
          - networkId: 2337

        # These ingresses create Route 53 Records.
        ingress:
          enabled: true
          hosts:
            - host: ${DEVSPACE_NAMESPACE}-geth-1337-http.${DEVSPACE_INGRESS_BASE_DOMAIN}
              http:
                paths:
                  - path: /
                    backend:
                      service:
                        name: geth-1337
                        port:
                          number: 8544
            - host: ${DEVSPACE_NAMESPACE}-geth-1337-ws.${DEVSPACE_INGRESS_BASE_DOMAIN}
              http:
                paths:
                  - path: /
                    backend:
                      service:
                        name: geth-1337
                        port:
                          number: 8546
            - host: ${DEVSPACE_NAMESPACE}-geth-2337-http.${DEVSPACE_INGRESS_BASE_DOMAIN}
              http:
                paths:
                  - path: /
                    backend:
                      service:
                        name: geth-2337
                        port:
                          number: 8544
            - host: ${DEVSPACE_NAMESPACE}-geth-2337-ws.${DEVSPACE_INGRESS_BASE_DOMAIN}
              http:
                paths:
                  - path: /
                    backend:
                      service:
                        name: geth-2337
                        port:
                          number: 8546
        networkPolicyDefault:
          ingress:
            allowCustomCidrs: true
            # Should be a comma separated list of CIDR blocks. To include
            # AWS ALB private CIDRs and optionally other custom CIDRs.
            # Example format: 10.0.0.0/16,192.168.0.1/24
            customCidrs: ${DEVSPACE_INGRESS_CIDRS}
        networkPolicy:
          enabled: true
          extraIngressSelectors:
            # whitelist chainlink-don deployment from donut dependency
            - podSelector:
                matchLabels:
                  app.kubernetes.io/name: chainlink-don
            # whitelist blockscout
            - podSelector:
                matchLabels:
                  app.kubernetes.io/name: blockscout-stack

profiles:
  - name: local-charts
    merge:
      deployments:
        geth:
          helm:
            chart:
              name: crib-geth
              path: ${CHAINLINK_CODE_DIR}/infra-charts/crib-geth
              version: null
  - name: ccip
    merge:
      deployments:
        geth:
          helm:
            values:
              networkPolicy:
                # Allow additional services to access geth
                extraIngressSelectors:
                  - podSelector:
                      matchLabels:
                        app: atlas
                  - podSelector:
                      matchLabels:
                        app: ccip-scripts-deployer
                  - podSelector:
                      matchLabels:
                        app.kubernetes.io/name: chainlink-don
              chains:
                - networkId: 1337
                  customEVMConfigToml: |
                    [EVM.GasEstimator]
                    PriceMax = '200 gwei'
                    LimitDefault = 6000000
                    FeeCapDefault = '200 gwei'
                - networkId: 2337
                  customEVMConfigToml: |
                    [EVM.GasEstimator]
                    PriceMax = '200 gwei'
                    LimitDefault = 6000000
                    FeeCapDefault = '200 gwei'

  - name: additional-chains
    merge: |-
      $(
        DEVSPACE_NAMESPACE=${DEVSPACE_NAMESPACE} \
        ADDITIONAL_CHAINS_COUNT=${ADDITIONAL_CHAINS_COUNT} \
        gomplate \
          --config ${LOCAL_TEMPLATES_DIR}/additional-chains.yaml
      )
  - name: aws
    activation:
      - vars:
          PROVIDER: "aws"
    merge:
      deployments:
        geth:
          helm:
            values:
              statefulSet:
                enabled: true
              nodeSelector:
                node-role: crib
              tolerations:
                - key: "node-role"
                  operator: "Equal"
                  value: "crib"
                  effect: "NoSchedule"
              ingress:
                ingressClassName: nginx-internal
                extra_annotations:
                  nginx.ingress.kubernetes.io/backend-protocol: HTTP
                  external-dns.alpha.kubernetes.io/ttl: "30"
  - name: ccip-v2-load-tests
    merge:
      deployments:
        geth:
          helm:
            values:
              resources:
                requests:
                  cpu: 1000m
                  memory: 256Mi
                limit:
                  cpu: 4000m
                  memory: 6Gi
  # Use the profile to customize individual networks settings. For example blockTime property
  # For selected networks. You will need to list all the networks to match the ADDITIONAL_CHAINS_COUNT
  # property
  - name: ccip-v2-load-tests-customized-networks
    merge: |-
      $(
        DEVSPACE_NAMESPACE=${DEVSPACE_NAMESPACE} \
        ADDITIONAL_CHAINS_COUNT=${ADDITIONAL_CHAINS_COUNT} \
        gomplate \
          --config ${LOCAL_TEMPLATES_DIR}/ccip-v2-load-tests.yaml
      )
  - name: kind
    activation:
      - vars:
          PROVIDER: "kind"
    merge:
      deployments:
        geth:
          helm:
            values:
              networkPolicies:
                enabled: true
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
              statefulSet:
                enabled: false
              ingress:
                ingressClassName: nginx
                extra_annotations:
                  cert-manager.io/cluster-issuer: mkcert-issuer
                  nginx.ingress.kubernetes.io/ssl-redirect: "true"
                certProvisioning:
                  enabled: true
  - name: local-dev-simulated-core-ocr1
    merge:
      deployments:
        geth:
          helm:
            values:
              statefulSet:
                enabled: true
                storageClassName: gp3
                capacity: 4Gi
  - name: git-charts
    merge:
      deployments:
        geth:
          helm:
            chart:
              git: https://github.com/smartcontractkit/infra-charts
              subPath: crib-geth
              revision: 9c1de84e27f668e0d220f8050a3705f2dfa2e655
