---
version: v2beta1
name: geth

pipelines:
  kind:
    run: |-
      ensure_pull_secrets --all
      run_pipelines deploy
  deploy:
    run: |-
      create_deployments geth

pullSecrets:
  regcred-don:
    registry: 323150190480.dkr.ecr.us-west-2.amazonaws.com
    secret: regcred-don
    serviceAccounts:
      - default

hooks:
  - wait:
      running: true
      terminatedWithCode: 0
      timeout: 600
    container:
      labelSelector:
        # vars don't work here, = releaseName
        release: "geth"
    events: ["after:deploy:geth"]

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  geth:
    updateImageTags: false
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      releaseName: "geth"
      chart:
        name: "${CHAINLINK_HELM_REGISTRY_URI}/crib-geth"
        version: "0.1.0-preview-1636-2782c69"
      # for simplicity, we define all the values here
      # they can be defined the same way in values.yml
      # devspace merges these "values" with the "values.yaml" before deploy
      values:
        securityContext:
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 999
          runAsGroup: 999
        version: v1.12.0
        wsRpcPort: 8546
        httpRpcPort: 8544
        chains:
          - networkId: 1337
          - networkId: 2337
        blocktime: 1

        # These ingresses create AWS ALB resources and Route 53 Records.
        ingress:
          enabled: true
          annotation_certificate_arn: ${DEVSPACE_INGRESS_CERT_ARN}
          annotation_group_name: ${DEVSPACE_NAMESPACE}
          hosts:
            - host: ${DEVSPACE_NAMESPACE}-geth-1337-http.${DEVSPACE_INGRESS_BASE_DOMAIN}
              http:
                paths:
                  - path: /
                    backend:
                      service:
                        name: geth-1337
                        port:
                          number: 8544
            - host: ${DEVSPACE_NAMESPACE}-geth-1337-ws.${DEVSPACE_INGRESS_BASE_DOMAIN}
              http:
                paths:
                  - path: /
                    backend:
                      service:
                        name: geth-1337
                        port:
                          number: 8546
            - host: ${DEVSPACE_NAMESPACE}-geth-2337-http.${DEVSPACE_INGRESS_BASE_DOMAIN}
              http:
                paths:
                  - path: /
                    backend:
                      service:
                        name: geth-2337
                        port:
                          number: 8544
            - host: ${DEVSPACE_NAMESPACE}-geth-2337-ws.${DEVSPACE_INGRESS_BASE_DOMAIN}
              http:
                paths:
                  - path: /
                    backend:
                      service:
                        name: geth-2337
                        port:
                          number: 8546
        networkPolicyDefault:
          ingress:
            allowCustomCidrs: true
            # Should be a comma separated list of CIDR blocks. To include
            # AWS ALB private CIDRs and optionally other custom CIDRs.
            # Example format: 10.0.0.0/16,192.168.0.1/24
            customCidrs: ${DEVSPACE_INGRESS_CIDRS}

profiles:
  - name: local-charts
    merge:
      deployments:
        geth:
          helm:
            chart:
              name: crib-geth
              path: ${CHAINLINK_CODE_DIR}/infra-charts/crib-geth
              version: null
  - name: ccip
    merge:
      deployments:
        geth:
          helm:
            values:
              statefulSet:
                # Set to true to use StatefulSet instead of Deployment.
                enabled: true
              networkPolicy:
                # Allow additional services to access geth
                extraIngressSelectors:
                  - podSelector:
                      matchLabels:
                        app: atlas
                  - podSelector:
                      matchLabels:
                        app: ccip-scripts-deployer
              chains:
                - networkId: 1337
                  customEVMConfigToml: |
                    [EVM.GasEstimator]
                    PriceMax = '200 gwei'
                    LimitDefault = 6000000
                    FeeCapDefault = '200 gwei'
                - networkId: 2337
                  customEVMConfigToml: |
                    [EVM.GasEstimator]
                    PriceMax = '200 gwei'
                    LimitDefault = 6000000
                    FeeCapDefault = '200 gwei'
  - name: kind
    merge:
      deployments:
        geth:
          helm:
            values:
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
              statefulSet:
                enabled: false
              ingress:
                ingressClassName: nginx
  - name: local-dev-simulated-core-ocr1
    merge:
      deployments:
        geth:
          helm:
            values:
              statefulSet:
                enabled: true
                storageClassName: gp3
                capacity: 4Gi
