---
version: v2beta1

vars:
  DEPENDENCIES_DIR:
    source: env
    default: "../"
  # Env vars required for Atlas Monitoring
  # Enables or disables Atlas components/pipeline
  MONITORING_SCRIPT:
    source: env
    default: "./${DEPENDENCIES_DIR}/atlas/init"
  MONITORING_NETWORK_2_VALUES_PATH:
    source: env
    default: "${MONITORING_SCRIPT}/output/values-network-2.yaml"
  MONITORING_NETWORK_1_VALUES_PATH:
    source: env
    default: "${MONITORING_SCRIPT}/output/values-network-1.yaml"
  NETWORK_1:
    source: env
    default: simulated-network-1
  NETWORK_1_CHAINID:
    source: env
    default: 1337
  NETWORK_1_RPC:
    source: env
    default: http://geth-1337:8544
  NETWORK_2:
    source: env
    default: simulated-network-2
  NETWORK_2_CHAINID:
    source: env
    default: 2337
  NETWORK_2_RPC:
    source: env
    default: http://geth-2337:8544

pullSecrets:
  regcred-atlas:
    registry: 804282218731.dkr.ecr.us-west-2.amazonaws.com
    secret: regcred-atlas

pipelines:
  atlas:
    run: |-
      run_pipelines atlas-infra
      run_pipelines atlas-network-1 atlas-network-2
      kubectl rollout status deployment -l app=atlas

  atlas-infra:
    run: |-
      ensure_pull_secrets --all
      create_deployments atlas-infra

  atlas-network-1:
    run: |-
      (
        cd ${MONITORING_SCRIPT}
        go run main.go ${NETWORK_1} ${NETWORK_1_CHAINID} ${NETWORK_1_RPC} values-network-1.yaml
      )
      create_deployments atlas-network-1

  atlas-network-2:
    run: |-
      (
        cd ${MONITORING_SCRIPT}
        go run main.go ${NETWORK_2} ${NETWORK_2_CHAINID} ${NETWORK_2_RPC} values-network-2.yaml
      )
      create_deployments atlas-network-2

deployments:
  atlas-network-1:
    updateImageTags: false
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      releaseName: atlas-network-1
      upgradeArgs: ["--timeout", "10m"]
      displayOutput: true
      chart:
        name: ${CHAINLINK_HELM_REGISTRY_URI}/crib-atlas-core
        version: "0.1.0"
      valuesFiles:
        - ${MONITORING_NETWORK_1_VALUES_PATH}
      values:
        podSecurityContext:
          fsGroup: 999
  atlas-network-2:
    updateImageTags: false
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      releaseName: atlas-network-2
      upgradeArgs: ["--timeout", "10m"]
      displayOutput: true
      chart:
        name: ${CHAINLINK_HELM_REGISTRY_URI}/crib-atlas-core
        version: "0.0.4"
      valuesFiles:
        - ${MONITORING_NETWORK_2_VALUES_PATH}
      values:
        podSecurityContext:
          fsGroup: 999
  atlas-infra:
    updateImageTags: false
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      upgradeArgs: ["--timeout", "10m"]
      displayOutput: true
      chart:
        name: ${CHAINLINK_HELM_REGISTRY_URI}/crib-atlas-infra
        version: "0.2.0"
      values:
        postgres-migration:
          envVars:
            NETWORKS: "${NETWORK_1},${NETWORK_2}"
        atlas-setup:
          envVars:
            NETWORKS: "${NETWORK_1},${NETWORK_2}"

profiles:
  - name: local-charts
    merge:
      deployments:
        atlas-infra:
          helm:
            chart:
              name: atlas-infra
              path: ${CHAINLINK_CODE_DIR}/infra-charts/crib-atlas-infra
              version: null
        atlas-network-1:
          helm:
            chart:
              name: network-1
              path: ${CHAINLINK_CODE_DIR}/infra-charts/crib-atlas-core
              version: null
        atlas-network-2:
          helm:
            chart:
              name: network-2
              path: ${CHAINLINK_CODE_DIR}/infra-charts/crib-atlas-core
              version: null
  - name: git-charts
    merge:
      deployments:
        atlas-infra:
          helm:
            chart:
              git: https://github.com/smartcontractkit/infra-charts
              subPath: crib-atlas-infra
              revision: 9c1de84e27f668e0d220f8050a3705f2dfa2e655
        atlas-network-1:
          helm:
            chart:
              git: https://github.com/smartcontractkit/infra-charts
              subPath: crib-atlas-core
              revision: 292a560b02d326deb356b77561588206cdf88ef3
        atlas-network-2:
          helm:
            chart:
              git: https://github.com/smartcontractkit/infra-charts
              subPath: crib-atlas-core
              revision: fdd2426888f483956e11968f3355e27d24e6e571

  - name: kind
    merge:
      deployments:
        atlas-infra:
          helm:
            values:
              atlas-postgraphile:
                imagePullSecrets:
                  - name: regcred-atlas
                topologySpreadConstraints: []
                image:
                  tag: "qa-latest"
                  pullPolicy: IfNotPresent
              atlas-setup:
                imagePullSecrets:
                  - name: regcred-atlas
                image:
                  tag: "qa-latest"
                  pullPolicy: IfNotPresent
                initContainers:
                  - name: wait-for-services
                    image: "804282218731.dkr.ecr.us-west-2.amazonaws.com/atlas-setup:qa-latest"
                    command: ["/bin/sh", "-c"]
                    args:
                      - -c
                      - |
                        /bin/sh /scripts/wait_for_endpoint.sh
                    volumeMounts:
                      - name: script-volume
                        mountPath: /scripts
                    securityContext:
                      capabilities:
                        drop:
                          - ALL
                      runAsUser: 999
                      runAsGroup: 999
                      runAsNonRoot: true
                    envFrom:
                      - secretRef:
                          name: kafka-urls
                      - secretRef:
                          name: schema-registry-url

        atlas-network-1:
          helm:
            values:
              atlas-evm-ccip-exporter:
                imagePullSecrets:
                  - name: regcred-atlas
                image:
                  tag: "qa-latest"
                  pullPolicy: IfNotPresent
              atlas-evm-ccip:
                imagePullSecrets:
                  - name: regcred-atlas
                image:
                  tag: "qa-latest"
                  pullPolicy: IfNotPresent
              atlas-core:
                imagePullSecrets:
                  - name: regcred-atlas
                dataCoverage:
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-blocks:
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-events:
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-events-retry:
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-logs:
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-logs-retry:
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-receipts:
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-receipts-retry:
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-txn-rdd-filter:
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-logs-abi-decoder:
                  enabled: false
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent

        atlas-network-2:
          helm:
            values:
              atlas-evm-ccip-exporter:
                imagePullSecrets:
                  - name: regcred-atlas
                image:
                  tag: "qa-latest"
                  pullPolicy: IfNotPresent
              atlas-evm-ccip:
                imagePullSecrets:
                  - name: regcred-atlas
                image:
                  tag: "qa-latest"
                  pullPolicy: IfNotPresent
              atlas-core:
                imagePullSecrets:
                  - name: regcred-atlas
                dataCoverage:
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-blocks:
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-events:
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-events-retry:
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-logs:
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-logs-retry:
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-receipts:
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-receipts-retry:
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-txn-rdd-filter:
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
                evm-logs-abi-decoder:
                  enabled: false
                  imagePullSecrets:
                    - name: regcred-atlas
                  image:
                    tag: "qa-latest"
                    pullPolicy: IfNotPresent
