config:
  clients:
    - url: http://loki:3100/loki/api/v1/push
      tenant_id: 1
# In order to disable logs from the control plane node, uncomment the following affinity.
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: NotIn
#               values:
#                 - crib-cluster-control-plane
