# Make sure to check the documentation at https://goreleaser.com
version: 2

project_name: crib

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

# See https://goreleaser.com/customization/build/
builds:
  - id: "cli"
    binary: crib
    env:
      - CGO_ENABLED=0
    main: .
    goarch:
      - arm64
      - amd64
    goos:
      - linux
      - darwin
    # Add custom naming for snapshots
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version=snapshot-{{.ShortCommit}}
      - -X main.commit={{.FullCommit}}
      - -X main.date={{.CommitDate}}

checksum:
  name_template: checksums.txt

release:
  github:
    owner: smartcontractkit
    name: crib
  prerelease: auto

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
