dir: "{{ .InterfaceDir }}/mocks"
mockname: "{{ .InterfaceName }}"
outpkg: mocks
filename: "{{ .InterfaceName | snakecase }}.go"
with-expecter: true

packages:
  github.com/smartcontractkit/crib/cli/wrappers:
    config:
      all: true

  k8s.io/client-go/kubernetes/typed/core/v1:
    config:
      dir: "mocks/external/kubernetes"
      outpkg: "kubernetes"
    interfaces:
      CoreV1Interface:
      NamespaceInterface:

  k8s.io/client-go/dynamic:
    config:
      dir: "mocks/external/kubernetes"
      outpkg: "kubernetes"
    interfaces:
      ResourceInterface: