dir: "{{ .InterfaceDir }}/mocks"
mockname: "{{ .InterfaceName }}"
outpkg: mocks
filename: "{{ .InterfaceName | snakecase }}.go"
with-expecter: true

packages:
  github.com/smartcontractkit/crib/cli/wrappers:
    config:
      all: true

  k8s.io/client-go/kubernetes/typed/core/v1:
    config:
      dir: "mocks/external/kubernetes"
      outpkg: "kubernetes"
    interfaces:
      CoreV1Interface:
      NamespaceInterface:
      ConfigMapInterface:

  k8s.io/client-go/dynamic:
    config:
      dir: "mocks/external/kubernetes"
      outpkg: "kubernetes"
    interfaces:
      ResourceInterface:

  github.com/docker/cli/cli/command:
    config:
      dir: "mocks/external/docker"
      outpkg: "docker"
    interfaces:
      Cli:
        config:
          mockname: "DockerCli"
          filename: "docker_cli.go"

  github.com/docker/docker/client:
    config:
      dir: "mocks/external/docker"
      outpkg: "docker"
    interfaces:
      APIClient:

  sigs.k8s.io/controller-runtime/pkg/client:
    config:
      dir: "mocks/external/kubernetes"
      outpkg: "kubernetes"
    interfaces:
      Client:
        config:
          mockname: "ControllerRuntimeClient"
          filename: "controller_runtime_client.go"

  sigs.k8s.io/kind/pkg/cluster/nodes:
    config:
      dir: "mocks/external/kind"
      outpkg: "kind"
    interfaces:
      Node:
        config:
          mockname: "KindNode"
          filename: "kind_node.go"

  sigs.k8s.io/kind/pkg/exec:
    config:
      dir: "mocks/external/kind"
      outpkg: "kind"
    interfaces:
      Cmd:
        config:
          mockname: "KindExecCmd"
          filename: "kind_exec_cmd.go"