dir: "{{ .InterfaceDir }}/mocks"
mockname: "{{ .InterfaceName }}"
outpkg: mocks
filename: "{{ .InterfaceName | snakecase }}.go"
with-expecter: true
packages:
    github.com/smartcontractkit/crib/cli/wrappers:
        interfaces:
            DockerAPI:
            DockerCLI:
            ECRAPI:
            EKSAPI: