[Capabilities]
[Capabilities.ExternalRegistry]
Address = '0x49fd2BE640DB2910c2fAb69bB8531Ab6E76127ff'
ChainID = '1337'
NetworkID = 'evm'

[Capabilities.Peering]
[Capabilities.Peering.V2]
DefaultBootstrappers = ['12D3KooWKBJLXVRh4nRMm6tmMzaYHNiX1iVwYMFFiPr83VJSWCgV@localhost:6690']
Enabled = true
ListenAddresses = ['0.0.0.0:6690']

[[EVM]]
ChainID = '1337'

[[EVM.Nodes]]
HTTPURL = 'https://crib-local-geth-1337-http.main.stage.cldev.sh'
Name = 'anvil'
WSURL = 'wss://crib-local-geth-1337-ws.main.stage.cldev.sh'

[Feature]
LogPoller = true

[OCR2]
ContractPollInterval = '1s'
DatabaseTimeout = '1s'
Enabled = true

[P2P]
[P2P.V2]
DefaultBootstrappers = ['12D3KooWKBJLXVRh4nRMm6tmMzaYHNiX1iVwYMFFiPr83VJSWCgV@localhost:5001']
Enabled = true
ListenAddresses = ['0.0.0.0:5001']