{
 "title": "One Click",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "msg_id", "query": "info" }
  ]
 },
 "panels": [
  {
   "title": "All \"error\" msgs for DON nodes",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{pod=~\"app-node[2-5]-[a-z0-9]+-[a-z0-9]+\"} |= `\"level\":\"error\"`",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "Logs for msg_id",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{pod=~\"app-node[2-5]-[a-z0-9]+-[a-z0-9]+\"} |= `\"$msg_id\"`"
    }
   ]
  },
  {
   "title": "All \"info\" msgs for DON nodes",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{pod=~\"app-node[2-5]-[a-z0-9]+-[a-z0-9]+\"} |= `\"level\":\"info\"`",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "All \"debug\" msgs for DON nodes",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{pod=~\"app-node[2-5]-[a-z0-9]+-[a-z0-9]+\"} |= `\"level\":\"debug\"`"
    }
   ]
  },
  {
   "title": "Bootstrap logs (info and error)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{pod=~\"app-node1-bootstrap-[a-z0-9]+-[a-z0-9]+\"} |= `\"level\":\"info\"` or `\"level\":\"error\"`",
     "maxLines": 1000
    }
   ]
  }
 ]
}