version: v2beta1
name: chainlink

vars:
  CRIB_DIR: $(git rev-parse --show-toplevel 2>/dev/null)
  SCRIPTS_DIR:
    source: env
    default: "${CRIB_DIR}/scripts"
  DEVSPACE_ENV_FILE: .env
  DEPENDENCIES_DIR:
    source: env
    default: "${CRIB_DIR}/dependencies"
  IMPORTS_DIR:
    source: env
    default: "${CRIB_DIR}/imports"
  TMP_DIR:
    source: env
    default: "${CRIB_DIR}/deployments/ccip-v2/.tmp"
  # "The provider being used to deploy CRIB"
  PROVIDER:
    source: all
    default: "aws"
  CHAINLINK_CODE_DIR:
    source: env
    default: "../../.."
  CHAINLINK_HELM_REGISTRY_URI:
    source: env
    default: "oci://804282218731.dkr.ecr.us-west-2.amazonaws.com/infra-charts"
  DON_TYPE:
    source: env
    default: ccip
  DON_VERSION:
    source: env
    default: ccip-dev
  CCIP_TOOLING_VERSION:
    source: env
    default: v2
  DON_NODE_COUNT:
    source: env
    default: 4
  DON_BOOT_NODE_COUNT:
    source: env
    default: 1
  GETH_CHAINS_COUNT:
    source: env
    default: 2
  SOLANA_CHAINS_COUNT:
    source: env
    default: 0
  ENABLE_MONITORING:
    source: env
    default: false
  CHAINLINK_PRODUCT:
    source: env
    default: ccip

imports:
  - path: ${IMPORTS_DIR}/lib-common
  - path: ${IMPORTS_DIR}/lib-aws
  - path: ${IMPORTS_DIR}/lib-kind

pipelines:
  maybe-kind:
    run: |-
      if [ "$PROVIDER" == "kind" ]; then
        run_dependency_pipelines kind-core
        if [ "$ENABLE_MONITORING" == "true" ]; then
          run_dependency_pipelines kind-monitoring
        fi
      fi
  ccip-v2:
    run: |-
      run_pipelines maybe-kind

      run_dependency_pipelines geth-chains
      run_dependency_pipelines solana-chains
      crib devspace ingress-check --nsTimeout=2m --timeout=4m

      # Deploy CCIP enabled fully configured DON
      run_dependency_pipelines ccip-don
      crib devspace ingress-check --nsTimeout=2m --timeout=4m
  ccip-v2-redeploy-don:
    run: |-
      # Deploy CCIP enabled fully configured DON
      run_dependency_pipelines ccip-don --set-flag redeployDONOnly="true"
      crib devspace ingress-check --nsTimeout=2m --timeout=4m
  ccip-v2-infra-only:
    run: |-
      run_pipelines maybe-kind

      run_dependency_pipelines geth-chains
      run_dependency_pipelines solana-chains
      crib devspace ingress-check --nsTimeout=2m --timeout=4m

      # Deploy CCIP enabled fully configured DON
      run_dependency_pipelines ccip-don --set-flag infraOnly="true"
      crib devspace ingress-check --nsTimeout=2m --timeout=4m
  # Pipeline without any steps that would break --render flag
  ccip-v2-infra-only-render:
    run: |-
      run_pipelines maybe-kind
      run_dependency_pipelines geth-chains
      run_dependency_pipelines solana-chains
      run_dependency_pipelines ccip-don --set-flag infraOnly="true"
  geth:
    run: |-
      if [ "$PROVIDER" == "kind" ]; then
        run_dependency_pipelines kind-core
      fi

      run_dependency_pipelines geth-chains
      run_dependency_pipelines solana-chains
  debug-gap:
    run: |-
      run_dependency_pipelines geth-chains
      run_dependency_pipelines solana-chains
      task ccip-v2-scripts:build
      run_dependency_pipelines ccip-v2-scripts --pipeline deploy-home-chain-contracts
  ccip-v2-scripts-home-chain:
    run: |-
      run_dependency_pipelines ccip-v2-scripts --pipeline deploy-home-chain-contracts
  ccip-v2-scripts-deploy-ccip:
    run: |-
      run_dependency_pipelines ccip-v2-scripts --pipeline deploy-ccip
  job-distributor:
    run: |-
      run_dependency_pipelines job-distributor
profiles:
  - name: kind
    activation:
      - vars:
          PROVIDER: "kind"
    patches:
      - op: add
        path: dependencies
        value:
          kind-core:
            path: ${DEPENDENCIES_DIR}/kind-core
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
          kind-monitoring:
            path: ${DEPENDENCIES_DIR}/kind-monitoring
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
  - name: ccip-v2-scripts
    patches:
      - op: add
        path: dependencies
        value:
          ccip-v2-scripts:
            path: ${DEPENDENCIES_DIR}/ccip-v2-scripts
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
  - name: debug-gap
    patches:
      - op: add
        path: dependencies
        value:
          ccip-v2-scripts:
            path: ${DEPENDENCIES_DIR}/ccip-v2-scripts
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
          geth:
            path: ${DEPENDENCIES_DIR}/geth
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            profiles:
              - ccip
  - name: job-distributor
    patches:
      - op: add
        path: dependencies
        value:
          job-distributor:
            path: ${DEPENDENCIES_DIR}/job-distributor
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
  - name: default
    patches:
      - op: add
        path: dependencies
        value:
          geth-chains:
            path: ${DEPENDENCIES_DIR}/geth-v2
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            vars:
              CHAINS_COUNT: ${GETH_CHAINS_COUNT}
          solana-chains:
            path: ${DEPENDENCIES_DIR}/solana-validator
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            vars:
              CHAINS_COUNT: ${SOLANA_CHAINS_COUNT}
          ccip-don:
            path: ${DEPENDENCIES_DIR}/donut/chainlink-don.yaml
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            pipeline: deploy-ccip-v2
            profiles:
              - version-from-env
              - network-generated
              # Uncomment this to enable overrides from overrides.ccip-v2.yaml file
              # - overrides-ccip-v2
  - name: load-tests
    patches:
      - op: add
        path: vars
        value:
          USE_CASE:
            source: env
            default: ccip-load-tests
      - op: add
        path: dependencies
        value:
          geth-chains:
            path: ${DEPENDENCIES_DIR}/geth-v2
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
          ccip-don:
            path: ${DEPENDENCIES_DIR}/donut/chainlink-don.yaml
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            pipeline: deploy-ccip-v2
            profiles:
              - version-from-env
              - network-generated

  - name: default-aws
    parents:
      - profile: default
    patches:
      - op: add
        path: dependencies.ccip-don.profiles
        value: monitoring-service-monitor
  - name: load-tests-aws
    parents:
      - profile: load-tests
    patches:
      - op: add
        path: dependencies.ccip-don.profiles
        value: monitoring-service-monitor
      - op: add
        path: dependencies.ccip-don.profiles
        value: ccip-load-testing-aws-staging

commands:
  ccip-v2-kind:
    command: devspace run-pipeline ccip-v2 -p default
    description: Deploy full ccip-v2 setup to kind
    appendArgs: true
  ccip-v2-kind-redeploy-don:
    command: devspace run-pipeline ccip-v2-redeploy-don -p default
    description: Redeploy DON without updating contracts
    appendArgs: true
  ccip-v2-aws:
    command: devspace run-pipeline ccip-v2 -p default-aws
    description: Deploy full ccip-v2 setup to AWS
    appendArgs: true
  ccip-v2-aws-redeploy-don:
    command: devspace run-pipeline ccip-v2-redeploy-don -p default-aws
    description: Redeploy DON without updating contracts
    appendArgs: true
  ccip-v2-load-tests-aws:
    command: devspace run-pipeline ccip-v2 -p load-tests-aws
    description: Deploy full ccip-v2 setup to AWS with heavy load test profile
    appendArgs: true
  ccip-v2-load-tests-aws-redeploy-don:
    command: devspace run-pipeline ccip-v2-redeploy-don -p load-tests-aws
    description: Redeploy DON without updating contracts
    appendArgs: true
  ccip-v2-infra:
    command: devspace run-pipeline ccip-v2-infra-only -p default
    description: Run the ccip v2 pipeline without onchain deployment, just infra.
    appendArgs: true
  ccip-v2-infra-render:
    command: devspace run-pipeline ccip-v2-infra-only-render --render
    description: Render infra components, pass desired profile via -p flag
    appendArgs: true
  deploy-dashboard:
    command: crib dashboard deploy --product=ccip
    description: Deploy Grafana Dashboards (outdated)
    appendArgs: true
  geth:
    command: devspace run-pipeline geth -p default
    description: Deploy geth chains only
    appendArgs: true
  debug-gap:
    command: devspace run-pipeline debug-gap -p debug-gap
    description: Debugging command for gap
    appendArgs: true
  job-distributor:
    command: devspace run-pipeline job-distributor -p job-distributor
    description: Deploy job-distributor
    appendArgs: true
 # todo: remove these 2 and just rely on the ccip-v2-scripts
  deploy-home-chain:
    command: devspace -p ccip-v2-scripts run-pipeline ccip-v2-scripts-home-chain
    description: Deploy home chain
    appendArgs: true
  deploy-ccip-contracts:
    command: devspace -p ccip-v2-scripts run-pipeline ccip-v2-scripts-deploy-ccip
    description: Deploy CCIP Contracts and Add lanes.
    appendArgs: true
  ccip-v2-scripts:
    command: ccip-v2-scripts
    description: run ccip-v2-scripts cli command within devspace context
    appendArgs: true
  purge:
    command: |
      rm -f ${TMP_DIR}/*
      devspace purge
    description: Cleanup temp files and purge devspace env
