// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package cctp_token_pool

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("CCiTPESGEevd7TBU8EGBKrcxuRq7jx3YtW6tPidnscaZ")
