// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package cctp_token_pool

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetRateLimitAdmin is the `setRateLimitAdmin` instruction.
type SetRateLimitAdmin struct {
	Mint              *ag_solanago.PublicKey
	NewRateLimitAdmin *ag_solanago.PublicKey

	// [0] = [WRITE] state
	//
	// [1] = [WRITE, SIGNER] authority
	ag_solanago.AccountMetaSlice `bin:"-" borsh_skip:"true"`
}

// NewSetRateLimitAdminInstructionBuilder creates a new `SetRateLimitAdmin` instruction builder.
func NewSetRateLimitAdminInstructionBuilder() *SetRateLimitAdmin {
	nd := &SetRateLimitAdmin{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetMint sets the "mint" parameter.
func (inst *SetRateLimitAdmin) SetMint(mint ag_solanago.PublicKey) *SetRateLimitAdmin {
	inst.Mint = &mint
	return inst
}

// SetNewRateLimitAdmin sets the "newRateLimitAdmin" parameter.
func (inst *SetRateLimitAdmin) SetNewRateLimitAdmin(newRateLimitAdmin ag_solanago.PublicKey) *SetRateLimitAdmin {
	inst.NewRateLimitAdmin = &newRateLimitAdmin
	return inst
}

// SetStateAccount sets the "state" account.
func (inst *SetRateLimitAdmin) SetStateAccount(state ag_solanago.PublicKey) *SetRateLimitAdmin {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(state).WRITE()
	return inst
}

// GetStateAccount gets the "state" account.
func (inst *SetRateLimitAdmin) GetStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[0]
}

// SetAuthorityAccount sets the "authority" account.
func (inst *SetRateLimitAdmin) SetAuthorityAccount(authority ag_solanago.PublicKey) *SetRateLimitAdmin {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).WRITE().SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *SetRateLimitAdmin) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[1]
}

func (inst SetRateLimitAdmin) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetRateLimitAdmin,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetRateLimitAdmin) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetRateLimitAdmin) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Mint == nil {
			return errors.New("Mint parameter is not set")
		}
		if inst.NewRateLimitAdmin == nil {
			return errors.New("NewRateLimitAdmin parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.State is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
	}
	return nil
}

func (inst *SetRateLimitAdmin) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetRateLimitAdmin")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("             Mint", *inst.Mint))
						paramsBranch.Child(ag_format.Param("NewRateLimitAdmin", *inst.NewRateLimitAdmin))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("    state", inst.AccountMetaSlice[0]))
						accountsBranch.Child(ag_format.Meta("authority", inst.AccountMetaSlice[1]))
					})
				})
		})
}

func (obj SetRateLimitAdmin) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Mint` param:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return err
	}
	// Serialize `NewRateLimitAdmin` param:
	err = encoder.Encode(obj.NewRateLimitAdmin)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SetRateLimitAdmin) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return err
	}
	// Deserialize `NewRateLimitAdmin`:
	err = decoder.Decode(&obj.NewRateLimitAdmin)
	if err != nil {
		return err
	}
	return nil
}

// NewSetRateLimitAdminInstruction declares a new SetRateLimitAdmin instruction with the provided parameters and accounts.
func NewSetRateLimitAdminInstruction(
	// Parameters:
	mint ag_solanago.PublicKey,
	newRateLimitAdmin ag_solanago.PublicKey,
	// Accounts:
	state ag_solanago.PublicKey,
	authority ag_solanago.PublicKey) *SetRateLimitAdmin {
	return NewSetRateLimitAdminInstructionBuilder().
		SetMint(mint).
		SetNewRateLimitAdmin(newRateLimitAdmin).
		SetStateAccount(state).
		SetAuthorityAccount(authority)
}
