---
version: v2beta1
name: solana

vars:
  LOCAL_TEMPLATES_DIR:
    source: env
    default: ./templates
  LOCAL_VALUES_DIR:
    source: env
    default: ./values
  # Product can be chainlink or ccip. Based on the chosen profile it will activate specific mutations
  CHAINLINK_PRODUCT:
    source: env
    default: "chainlink"
  # Use this to activate patches specific to your use case, for example ccip-load-tests
  USE_CASE:
    source: env
    default: "default"
  # This is just a hack to always enable the profile
  ENABLE_BASE_PROFILE:
    source: env
    default: true
  # Use chain overrides to override configuration for individual chains
  # Useful for load testing
  CHAIN_OVERRIDES_FILENAME:
    source: env
    default: default.yaml
  # How many blockchain networks should it deploy
  # If set to 0, it won't deploy any chains
  CHAINS_COUNT:
    source: env
    default: 1

pipelines:
  kind:
    run: |-
      ensure_pull_secrets --all
      run_pipelines deploy
  deploy:
    run: |-
      if [ "${CHAINS_COUNT}" -gt 0 ]; then
        create_deployments --all
      fi

pullSecrets:
  regcred-prod-ecr:
    registry: 804282218731.dkr.ecr.us-west-2.amazonaws.com
    secret: regcred-prod-ecr

hooks:
  - wait:
      running: true
      terminatedWithCode: 0
      timeout: 600
    container:
      labelSelector:
        # vars don't work here, = releaseName
        release: "solana"
    events: ["after:deploy:solana"]

# The list of deployments is generated from the template
profiles:
  - name: base
    activation:
      - vars:
          ENABLE_BASE_PROFILE: "true"
    merge: |-
      $(
        if [ "${CHAINS_COUNT}" -gt 0 ]; then
          pushd ./scripts/generate_base_profile > /dev/null
          go run main.go -chain-overrides-dir="./../../values/chain-overrides/" \
            -chain-overrides-file="${CHAIN_OVERRIDES_FILENAME}" \
            -chains-count="${CHAINS_COUNT}" -provider="${PROVIDER}" \
            -product="${CHAINLINK_PRODUCT}" -use-case="${USE_CASE}"
        else
          echo "deployments:"
        fi
      )
  - name: local-charts
    merge: |-
      $(
        if [ "${CHAINS_COUNT}" -gt 0 ]; then
          pushd ./scripts/generate_base_profile > /dev/null
          go run main.go -chain-overrides-dir="./../../values/chain-overrides/" \
           -chains-count="${CHAINS_COUNT}" -provider="${PROVIDER}" \
            -template="local-charts.yaml.tmpl"
        else
          echo "deployments:"
        fi
      )
