// Code generated by operations-gen. DO NOT EDIT.

package lombard_token_pool

import (
	"github.com/Masterminds/semver/v3"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"

	gobindings "github.com/smartcontractkit/chainlink-ccip/chains/evm/gobindings/generated/v2_0_0/lombard_token_pool"
	cldf_evm "github.com/smartcontractkit/chainlink-deployments-framework/chain/evm"
	"github.com/smartcontractkit/chainlink-deployments-framework/chain/evm/operations2/contract"
	cldf_deployment "github.com/smartcontractkit/chainlink-deployments-framework/deployment"
	cld_ops "github.com/smartcontractkit/chainlink-deployments-framework/operations"
)

var ContractType cldf_deployment.ContractType = "LombardTokenPool"
var Version = semver.MustParse("2.0.0")
var TypeAndVersion = cldf_deployment.NewTypeAndVersion(ContractType, *Version)

type SetPathArgs struct {
	RemoteChainSelector uint64   `json:"remoteChainSelector"`
	LChainId            [32]byte `json:"lChainId"`
	AllowedCaller       []byte   `json:"allowedCaller"`
	RemoteAdapter       [32]byte `json:"remoteAdapter"`
}

type ConstructorArgs struct {
	Token             common.Address `json:"token"`
	Verifier          common.Address `json:"verifier"`
	Bridge            common.Address `json:"bridge"`
	Adapter           common.Address `json:"adapter"`
	AdvancedPoolHooks common.Address `json:"advancedPoolHooks"`
	RmnProxy          common.Address `json:"rmnProxy"`
	Router            common.Address `json:"router"`
	FallbackDecimals  uint8          `json:"fallbackDecimals"`
}

var Deploy = contract.NewDeploy(contract.DeployParams[ConstructorArgs]{
	Name:             "lombard-token-pool:deploy",
	Version:          Version,
	Description:      "Deploys the LombardTokenPool contract",
	ContractMetadata: gobindings.LombardTokenPoolMetaData,
	BytecodeByTypeAndVersion: map[string]contract.Bytecode{
		cldf_deployment.NewTypeAndVersion(ContractType, *Version).String(): {
			EVM: common.FromHex(gobindings.LombardTokenPoolMetaData.Bin),
		},
	},
})

func NewWriteSetPath(c gobindings.LombardTokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[SetPathArgs], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[SetPathArgs, gobindings.LombardTokenPoolInterface]{
		Name:         "lombard-token-pool:set-path",
		Version:      Version,
		Description:  "Calls setPath on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.LombardTokenPoolMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.LombardTokenPoolInterface, opts *bind.CallOpts, caller common.Address, args SetPathArgs) (bool, error) {
			return contract.OnlyOwner(c, opts, caller, args)
		},
		CallContract: func(
			c gobindings.LombardTokenPoolInterface,
			opts *bind.TransactOpts,
			args SetPathArgs,
		) (*types.Transaction, error) {
			return c.SetPath(opts, args.RemoteChainSelector, args.LChainId, args.AllowedCaller, args.RemoteAdapter)
		},
	})
}

func NewReadGetPath(c gobindings.LombardTokenPoolInterface) *cld_ops.Operation[contract.FunctionInput[uint64], gobindings.LombardTokenPoolPath, cldf_evm.Chain] {
	return contract.NewRead(contract.ReadParams[uint64, gobindings.LombardTokenPoolPath, gobindings.LombardTokenPoolInterface]{
		Name:         "lombard-token-pool:get-path",
		Version:      Version,
		Description:  "Calls getPath on the contract",
		ContractType: ContractType,
		Contract:     c,
		CallContract: func(c gobindings.LombardTokenPoolInterface, opts *bind.CallOpts, args uint64) (gobindings.LombardTokenPoolPath, error) {
			return c.GetPath(opts, args)
		},
	})
}
