version: v2beta1
name: chainlink

vars:
  CRIB_DIR: $(git rev-parse --show-toplevel 2>/dev/null)
  SCRIPTS_DIR:
    source: env
    default: "${CRIB_DIR}/scripts"
  DEVSPACE_ENV_FILE: .env
  DEPENDENCIES_DIR:
    source: env
    default: "${CRIB_DIR}/dependencies"
  IMPORTS_DIR:
    source: env
    default: "${CRIB_DIR}/imports"
  TMP_DIR:
    source: env
    default: "${CRIB_DIR}/deployments/cre/.tmp"
  # "The provider being used to deploy CRIB"
  PROVIDER:
    source: all
    default: "aws"
  CHAINLINK_CODE_DIR:
    source: env
    default: "../../.."
  CHAINLINK_HELM_REGISTRY_URI:
    source: env
    default: "oci://804282218731.dkr.ecr.us-west-2.amazonaws.com/infra-charts"
  DON_TYPE:
    source: env
    default: base
  DON_VERSION:
    source: env
    default: latest
  DON_NODE_COUNT:
    source: env
    default: 4
  DON_BOOT_NODE_COUNT:
    source: env
    default: 1
  GETH_CHAINS_COUNT:
    source: env
    default: 1
  CHAINLINK_PRODUCT:
    source: env
    default: chainlink
  CRE_CONFIG_DIR:
    source: env
    default: "${CRIB_DIR}/deployments/cre/.tmp/config"
  JOB_DISTRIBUTOR_IMAGE_TAG:
    source: env
    default: 0.9.0
  CHAIN_ID:
    source: env
    default: 2337

imports:
  - path: ${IMPORTS_DIR}/lib-common
  - path: ${IMPORTS_DIR}/lib-aws
  - path: ${IMPORTS_DIR}/lib-kind

pipelines:
  maybe-kind:
    run: |-
      if [ "$PROVIDER" == "kind" ]; then
        run_dependency_pipelines kind-core
        if [ "$ENABLE_MONITORING" == "true" ]; then
          run_dependency_pipelines kind-monitoring
        fi
      fi
  chain:
    run: |-
      run_pipelines maybe-kind

      run_dependency_pipelines geth-chain
      crib devspace ingress-check --nsTimeout=2m --timeout=4m
  custom-chain:
    run: |-
      run_pipelines maybe-kind

      run_dependency_pipelines custom-geth-chain
      crib devspace ingress-check --nsTimeout=2m --timeout=4m
  don:
    run: |-
      run_pipelines maybe-kind

      run_dependency_pipelines don
      # add a check for the ingress
      crib devspace ingress-check --nsTimeout=2m --timeout=4m
  jd:
    run: |-
      run_pipelines maybe-kind

      run_dependency_pipelines job-distributor
       # add a check for the ingress
       crib devspace ingress-check --nsTimeout=2m --timeout=4m

profiles:
  - name: chains
    patches:
      - op: add
        path: dependencies
        value:
          geth-chain:
            path: ${DEPENDENCIES_DIR}/geth-v2
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            vars:
              CHAINS_COUNT: 1
              ENABLE_DON_BASE: "false"

  - name: custom_geth
    patches:
      - op: add
        path: dependencies
        value:
          custom-geth-chain:
            path: ${DEPENDENCIES_DIR}/geth-v2
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            vars:
              ENABLE_DON_BASE: "false"
              ENABLE_BASE_PROFILE: "false"
              ENABLE_CUSTOM_PROFILE: "true"
              CHAIN_ID: ${CHAIN_ID}

  - name: dons
    patches:
      - op: add
        path: dependencies
        value:
          don:
            path: ${DEPENDENCIES_DIR}/donut/chainlink-don.yaml
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            pipeline: deploy
            profiles:
              - version-from-env
            vars:
              DON_TYPE: ${DON_TYPE}
          job-distributor:
            path: ${DEPENDENCIES_DIR}/job-distributor
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            vars:
              JOB_DISTRIBUTOR_IMAGE_TAG: ${JOB_DISTRIBUTOR_IMAGE_TAG}

  - name: aws

  - name: kind
    patches:
      - op: add
        path: dependencies
        value:
          kind-core:
            path: ${DEPENDENCIES_DIR}/kind-core
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
          kind-monitoring:
            path: ${DEPENDENCIES_DIR}/kind-monitoring
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}

commands:
  deploy-geth-chain:
    command: devspace run-pipeline chain -p chains -p ${PROVIDER}
    description: Deploy a single Geth chain
    appendArgs: true
  deploy-custom-geth-chain:
    command: devspace run-pipeline custom-chain -p custom_geth -p ${PROVIDER}
    description: Deploy a single Geth chain
    appendArgs: true
  deploy-jd:
    command: devspace run-pipeline jd -p dons -p ${PROVIDER}
    description: Deploy JD
    appendArgs: true
  deploy-don:
    command: devspace run-pipeline don -p dons -p ${PROVIDER}
    description: Deploy a single DONs
    appendArgs: true
