---
version: v2beta1
name: daas

vars:
  DEVSPACE_ENV_FILE:
    source: env
    default: .env
  # switches / activation
  ENV: # options=[local|stage|prod]
    source: env
    default: prod
  PROVIDER: # options=[kind|aws]
    source: all
    default: aws
  REGISTRY: # options=[localhost|aws]
    source: env
    default: prod
  CHARTS: # options=[local|aws]
    source: env
    default: aws
  CLUSTER_SERVICES: # options=[ingress-controller-nginx|cert-manager|minio-operator]
    source: env
    default: ("ingress-controller-nginx" "cert-manager")
  BLOCKCHAIN: # options=[anvil]
    source: env
    default: ("anvil")
  ## local directories
  CRIB_DIR: $(git rev-parse --show-toplevel 2>/dev/null)
  SCRIPTS_DIR:
    source: env
    default: "${CRIB_DIR}/scripts"
  DEPENDENCIES_DIR:
    source: env
    default: "${CRIB_DIR}/dependencies"
  IMPORTS_DIR:
    source: env
    default: "${CRIB_DIR}/imports"
  CHARTS_DIR:
    source: env
    default: "${CRIB_DIR}/../infra-charts"
  # specific (consolidate from used dependencies)
  CHAINLINK_HELM_REGISTRY_URI:
    source: env
    default: "oci://804282218731.dkr.ecr.us-west-2.amazonaws.com/infra-charts"
  HOST_NAME:
    source: env
    default: main.stage.cldev.sh
  AWS_ACM_CERT_ARN:
    source: env
    default: ""

imports:
  - path: ${IMPORTS_DIR}/lib-common
  - path: ${IMPORTS_DIR}/lib-aws
  - path: ${IMPORTS_DIR}/lib-kind

pullSecrets:
  regcred-prod:
    registry: 804282218731.dkr.ecr.us-west-2.amazonaws.com
    secret: regcred-prod
  regcred-sdlc:
    registry: 795953128386.dkr.ecr.us-west-2.amazonaws.com
    secret: regcred-sdlc

pipelines:
  ## dependency pipelines

  deps-kind:
    run: |-
      [[ "${CLUSTER_SERVICES[@]}" =~ "ingress-controller-nginx" ]] && run_dependency_pipelines ingress-controller-nginx
      [[ "${CLUSTER_SERVICES[@]}" =~ "cert-manager" ]] && run_dependency_pipelines cert-manager
      [[ "${CLUSTER_SERVICES[@]}" =~ "minio-operator" ]] && run_dependency_pipelines minio-operator
      echo "done"

  deps-daas:
    run: |-
      run_dependency_pipelines daas-operator

  deps-vcluster-daas:
    run: |-
      run_dependency_pipelines vcluster-daas

  deps-vcluster-daas-alt:
    run: |-
      run_dependency_pipelines vcluster-daas-alt

  deps-blockchain:
    run: |-
      [[ "${BLOCKCHAIN[@]}" =~ "anvil" ]] && run_dependency_pipelines anvil
      # moar blockchains

  deps-minio-tenant: # todo
    run: |-
      run_dependency_pipelines minio-tenant

  deps-daas-api:
    run: |-
      run_dependency_pipelines daas-api

  ## top level pipelines

  daas-kind:
    run: |-
      [[ "$ENV" == "local" && "$REGISTRY" == "aws" ]] && ensure_pull_secrets --all
      run_pipelines deps-kind
      run_pipelines deps-blockchain
      run_pipelines deps-daas
      run_pipelines deps-daas-api

  daas-aws:
    run: |-
      run_pipelines deps-vcluster-daas

  daas-aws-alt:
    run: |-
      run_pipelines deps-vcluster-daas-alt

  daas-blockchain:
    run: |-
      run_pipelines deps-blockchain

  daas-minio-tenant: # todo
    run: |-
      run_pipelines deps-minio-tenant

  daas-api:
    run: |-
      run_pipelines deps-daas-api

profiles:
  ## dependency profiles

  - name: deps-kind
    patches:
      - op: add
        path: dependencies
        value:
          ingress-controller-nginx:
            path: ${DEPENDENCIES_DIR}/ingress-controller
            namespace: ingress-nginx
            overwriteVars: true
            profiles: []
          cert-manager:
            path: ${DEPENDENCIES_DIR}/cert-manager
            namespace: cert-manager
            overwriteVars: true
            profiles: []
          minio-operator:
            path: ${DEPENDENCIES_DIR}/daas/cluster-services-minio-operator.yaml
            namespace: minio
            overwriteVars: true
            profiles: []

  - name: deps-daas
    patches:
      - op: add
        path: dependencies
        value:
          daas-operator:
            path: ${DEPENDENCIES_DIR}/daas/chainlink-daas-operator.yaml
            namespace: ${DEVSPACE_NAMESPACE}
            overwriteVars: true
            profiles: []

  - name: deps-vcluster-daas
    patches:
      - op: add
        path: dependencies
        value:
          vcluster-daas:
            path: ${DEPENDENCIES_DIR}/daas/vcluster-daas.yaml
            namespace: ${DEVSPACE_NAMESPACE}
            overwriteVars: true
            profiles:
              - vcluster-crib-aws
              - deploy-cluster-services-console
              - deploy-blockchain-anvil
              - deploy-chainlink-daas-operator
              - deploy-chainlink-daas-api

  - name: deps-vcluster-daas-alt
    patches:
      - op: add
        path: dependencies
        value:
          vcluster-daas-alt:
            path: ${DEPENDENCIES_DIR}/daas/vcluster-daas.yaml
            namespace: ${DEVSPACE_NAMESPACE}
            overwriteVars: true
            profiles:
              - vcluster-crib-aws
              - deploy-cluster-services-console
              - deploy-cluster-services-olm
              - deploy-blockchain-anvil

  - name: deps-blockchain
    patches:
      - op: add
        path: dependencies
        value:
          anvil:
            path: ${DEPENDENCIES_DIR}/daas/blockchain-anvil.yaml
            namespace: ${DEVSPACE_NAMESPACE}
            overwriteVars: true
            profiles: []

  - name: deps-minio-tenant # todo
    patches:
      - op: add
        path: dependencies
        value:
          minio-tenant:
            path: ${DEPENDENCIES_DIR}/daas/cluster-services-minio-tenant.yaml
            namespace: minio
            overwriteVars: true
            profiles: []

  - name: deps-daas-api
    patches:
      - op: add
        path: dependencies
        value:
          daas-api:
            path: ${DEPENDENCIES_DIR}/daas/chainlink-daas-operator-resources.yaml
            namespace: daas
            overwriteVars: true
            profiles: []

  ## top level profiles

  - name: daas-aws
    parents:
      - profile: deps-vcluster-daas

  - name: daas-aws-alt
    parents:
      - profile: deps-vcluster-daas-alt

  - name: daas-kind
    parents:
      - profile: deps-kind
      - profile: deps-blockchain
      - profile: deps-daas
      - profile: deps-daas-api

  - name: daas-blockchain
    parents:
      - profile: deps-blockchain

  - name: daas-minio-tenant
    parents:
      - profile: deps-minio-tenant

  - name: daas-api
    parents:
      - profile: deps-daas-api

commands:
  # todo: consolidate based off switches (ENV|PROVIDER|REGISTRY)
  daas-aws:
    command: devspace run-pipeline daas-aws -p daas-aws
    description: Run the daas aws pipeline.
    appendArgs: true
  daas-aws-alt:
    command: devspace run-pipeline daas-aws-alt -p daas-aws-alt
    description: Run the daas aws alt pipeline.
    appendArgs: true
  daas-kind:
    command: devspace run-pipeline daas-kind -p daas-kind
    description: Run the daas kind pipeline.
    appendArgs: true
  # extras
  daas-blockchain:
    command: devspace run-pipeline daas-blockchain -p daas-blockchain
    description: Run the daas blockchain pipeline.
    appendArgs: true
  daas-minio-tenant:
    command: devspace run-pipeline daas-minio-tenant -p daas-minio-tenant
    description: Run the daas minio-tenant pipeline.
    appendArgs: true
  daas-api:
    command: devspace run-pipeline daas-api -p daas-api
    description: Run the daas api pipeline.
    appendArgs: true
  bypass:
    command: |-
      echo bloop
