---
version: v2beta1
name: daas

vars:
  CRIB_DIR: $(git rev-parse --show-toplevel 2>/dev/null)
  DEVSPACE_ENV_FILE:
    source: env
    default: .env
  ## Local directories
  SCRIPTS_DIR:
    source: env
    default: "${CRIB_DIR}/scripts"
  DEPENDENCIES_DIR:
    source: env
    default: "${CRIB_DIR}/dependencies"
  IMPORTS_DIR:
    source: env
    default: "${CRIB_DIR}/imports"
  ##
  PROVIDER:
    source: all
    default: "aws"
  CHAINLINK_HELM_REGISTRY_URI:
    source: env
    default: "oci://804282218731.dkr.ecr.us-west-2.amazonaws.com/infra-charts"

imports:
  - path: ${IMPORTS_DIR}/lib-common
  - path: ${IMPORTS_DIR}/lib-aws
  - path: ${IMPORTS_DIR}/lib-kind

pipelines:
  daas:
    run: |-
      run_dependency_pipelines vcluster-daas

profiles:
  - name: default
    patches:
      - op: add
        path: dependencies
        value:
          vcluster-daas:
            path: ${DEPENDENCIES_DIR}/daas/vcluster-daas.yaml
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            profiles: [crib-stage]

commands:
  daas:
    command: devspace run-pipeline daas -p default
    description: Run the daas pipeline.
    appendArgs: true
