version: v2beta1

pipelines:
  deploy:
    run: |-
      create_deployments grafana

deployments:
  grafana:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: grafana
        repo: https://grafana.github.io/helm-charts
        version: 8.5.1
      values:
        downloadDashboardsImage:
          # -- The Docker registry
          registry: curlimages
          repository: curl
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          fsGroup: 999

        ingress:
          enabled: true
          ingressClassName: nginx
          labels: {}
          path: /
          pathType: Prefix
          hosts:
            - ${DEVSPACE_NAMESPACE}-grafana.${DEVSPACE_INGRESS_BASE_DOMAIN}
profiles:
  - name: add-beholder-config
    patches:
      - op: add
        path: deployments.grafana.helm.valuesFiles
        value: ["./values/beholder.yaml"]

  - name: kind
    patches:
      - op: add
        path: deployments.grafana.helm.valuesFiles
        value: ["./values/default.yaml"]
