// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package rmn_remote

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

type CodeVersion binary.BorshEnum

const (
	CodeVersion_Default CodeVersion = iota
	CodeVersion_V1
)

func (value CodeVersion) String() string {
	switch value {
	case CodeVersion_Default:
		return "Default"
	case CodeVersion_V1:
		return "V1"
	default:
		return ""
	}
}

type Config struct {
	Version            uint8              `json:"version"`
	Owner              solanago.PublicKey `json:"owner"`
	ProposedOwner      solanago.PublicKey `json:"proposedOwner"`
	DefaultCodeVersion CodeVersion        `json:"defaultCodeVersion"`
}

func (obj Config) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Version`:
	err = encoder.Encode(obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Serialize `Owner`:
	err = encoder.Encode(obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Serialize `ProposedOwner`:
	err = encoder.Encode(obj.ProposedOwner)
	if err != nil {
		return errors.NewField("ProposedOwner", err)
	}
	// Serialize `DefaultCodeVersion`:
	err = encoder.Encode(obj.DefaultCodeVersion)
	if err != nil {
		return errors.NewField("DefaultCodeVersion", err)
	}
	return nil
}

func (obj Config) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Config: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Config) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Version`:
	err = decoder.Decode(&obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Deserialize `Owner`:
	err = decoder.Decode(&obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Deserialize `ProposedOwner`:
	err = decoder.Decode(&obj.ProposedOwner)
	if err != nil {
		return errors.NewField("ProposedOwner", err)
	}
	// Deserialize `DefaultCodeVersion`:
	err = decoder.Decode(&obj.DefaultCodeVersion)
	if err != nil {
		return errors.NewField("DefaultCodeVersion", err)
	}
	return nil
}

func (obj *Config) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Config: %w", err)
	}
	return nil
}

func UnmarshalConfig(buf []byte) (*Config, error) {
	obj := new(Config)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type ConfigSet struct {
	DefaultCodeVersion CodeVersion `json:"defaultCodeVersion"`
}

func (obj ConfigSet) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `DefaultCodeVersion`:
	err = encoder.Encode(obj.DefaultCodeVersion)
	if err != nil {
		return errors.NewField("DefaultCodeVersion", err)
	}
	return nil
}

func (obj ConfigSet) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ConfigSet: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ConfigSet) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `DefaultCodeVersion`:
	err = decoder.Decode(&obj.DefaultCodeVersion)
	if err != nil {
		return errors.NewField("DefaultCodeVersion", err)
	}
	return nil
}

func (obj *ConfigSet) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ConfigSet: %w", err)
	}
	return nil
}

func UnmarshalConfigSet(buf []byte) (*ConfigSet, error) {
	obj := new(ConfigSet)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Abstract curse subject.
//
// In particular, a curse subject can be constructed from a chain
// selector to signify that any lane involving that chain as `destination` or `source` is
// cursed.
//
// The above is not exhaustive: there may be other ways to define subjects.
type CurseSubject struct {
	Value [16]uint8 `json:"value"`
}

func (obj CurseSubject) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Value`:
	err = encoder.Encode(obj.Value)
	if err != nil {
		return errors.NewField("Value", err)
	}
	return nil
}

func (obj CurseSubject) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CurseSubject: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CurseSubject) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Value`:
	err = decoder.Decode(&obj.Value)
	if err != nil {
		return errors.NewField("Value", err)
	}
	return nil
}

func (obj *CurseSubject) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CurseSubject: %w", err)
	}
	return nil
}

func UnmarshalCurseSubject(buf []byte) (*CurseSubject, error) {
	obj := new(CurseSubject)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Curses struct {
	Version        uint8          `json:"version"`
	CursedSubjects []CurseSubject `json:"cursedSubjects"`
}

func (obj Curses) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Version`:
	err = encoder.Encode(obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Serialize `CursedSubjects`:
	err = encoder.Encode(obj.CursedSubjects)
	if err != nil {
		return errors.NewField("CursedSubjects", err)
	}
	return nil
}

func (obj Curses) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Curses: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Curses) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Version`:
	err = decoder.Decode(&obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Deserialize `CursedSubjects`:
	err = decoder.Decode(&obj.CursedSubjects)
	if err != nil {
		return errors.NewField("CursedSubjects", err)
	}
	return nil
}

func (obj *Curses) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Curses: %w", err)
	}
	return nil
}

func UnmarshalCurses(buf []byte) (*Curses, error) {
	obj := new(Curses)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type OwnershipTransferRequested struct {
	From solanago.PublicKey `json:"from"`
	To   solanago.PublicKey `json:"to"`
}

func (obj OwnershipTransferRequested) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `From`:
	err = encoder.Encode(obj.From)
	if err != nil {
		return errors.NewField("From", err)
	}
	// Serialize `To`:
	err = encoder.Encode(obj.To)
	if err != nil {
		return errors.NewField("To", err)
	}
	return nil
}

func (obj OwnershipTransferRequested) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding OwnershipTransferRequested: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *OwnershipTransferRequested) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `From`:
	err = decoder.Decode(&obj.From)
	if err != nil {
		return errors.NewField("From", err)
	}
	// Deserialize `To`:
	err = decoder.Decode(&obj.To)
	if err != nil {
		return errors.NewField("To", err)
	}
	return nil
}

func (obj *OwnershipTransferRequested) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling OwnershipTransferRequested: %w", err)
	}
	return nil
}

func UnmarshalOwnershipTransferRequested(buf []byte) (*OwnershipTransferRequested, error) {
	obj := new(OwnershipTransferRequested)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type OwnershipTransferred struct {
	From solanago.PublicKey `json:"from"`
	To   solanago.PublicKey `json:"to"`
}

func (obj OwnershipTransferred) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `From`:
	err = encoder.Encode(obj.From)
	if err != nil {
		return errors.NewField("From", err)
	}
	// Serialize `To`:
	err = encoder.Encode(obj.To)
	if err != nil {
		return errors.NewField("To", err)
	}
	return nil
}

func (obj OwnershipTransferred) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding OwnershipTransferred: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *OwnershipTransferred) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `From`:
	err = decoder.Decode(&obj.From)
	if err != nil {
		return errors.NewField("From", err)
	}
	// Deserialize `To`:
	err = decoder.Decode(&obj.To)
	if err != nil {
		return errors.NewField("To", err)
	}
	return nil
}

func (obj *OwnershipTransferred) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling OwnershipTransferred: %w", err)
	}
	return nil
}

func UnmarshalOwnershipTransferred(buf []byte) (*OwnershipTransferred, error) {
	obj := new(OwnershipTransferred)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type SubjectCursed struct {
	Subject CurseSubject `json:"subject"`
}

func (obj SubjectCursed) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Subject`:
	err = encoder.Encode(obj.Subject)
	if err != nil {
		return errors.NewField("Subject", err)
	}
	return nil
}

func (obj SubjectCursed) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SubjectCursed: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SubjectCursed) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Subject`:
	err = decoder.Decode(&obj.Subject)
	if err != nil {
		return errors.NewField("Subject", err)
	}
	return nil
}

func (obj *SubjectCursed) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SubjectCursed: %w", err)
	}
	return nil
}

func UnmarshalSubjectCursed(buf []byte) (*SubjectCursed, error) {
	obj := new(SubjectCursed)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type SubjectUncursed struct {
	Subject CurseSubject `json:"subject"`
}

func (obj SubjectUncursed) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Subject`:
	err = encoder.Encode(obj.Subject)
	if err != nil {
		return errors.NewField("Subject", err)
	}
	return nil
}

func (obj SubjectUncursed) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SubjectUncursed: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SubjectUncursed) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Subject`:
	err = decoder.Decode(&obj.Subject)
	if err != nil {
		return errors.NewField("Subject", err)
	}
	return nil
}

func (obj *SubjectUncursed) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SubjectUncursed: %w", err)
	}
	return nil
}

func UnmarshalSubjectUncursed(buf []byte) (*SubjectUncursed, error) {
	obj := new(SubjectUncursed)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
