// Code generated by https://github.com/Unheilbar/anchor-go. DO NOT EDIT.
// This file contains documentation and example usage for the generated code.

package example_ccip_receiver

// Documentation from the IDL:
// This program an example of a CCIP Receiver Program.
// Used to test CCIP Router execute.
