name: 'AWS ECR Authentication'
description: 'Configure AWS credentials and authenticate to ECR Public'
inputs:
  role-to-assume:
    description: 'IAM role to assume'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
    default: 'us-west-2'
  registry-type:
    description: 'ECR registry type'
    required: false
    default: 'private'
  registries:
    description: 'ECR registry to login'
    required: false

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
    - name: Authenticate to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      with:
        registry-type: ${{ inputs.registry-type }}
        registries: ${{ inputs.registries }}