// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package test_ccip_receiver

// Account discriminators
var (
	Account_Counter                 = [8]byte{255, 176, 4, 245, 188, 253, 124, 25}
	Account_ExternalExecutionConfig = [8]byte{159, 157, 150, 212, 168, 103, 117, 39}
)

// Event discriminators
var ()

// Instruction discriminators
var (
	Instruction_CcipReceive          = [8]byte{11, 244, 9, 249, 44, 83, 47, 245}
	Instruction_CcipTokenLockBurn    = [8]byte{200, 14, 50, 9, 44, 91, 121, 37}
	Instruction_CcipTokenReleaseMint = [8]byte{20, 148, 113, 198, 229, 170, 71, 48}
	Instruction_Initialize           = [8]byte{175, 175, 109, 31, 13, 152, 155, 237}
	Instruction_SetRejectAll         = [8]byte{42, 90, 30, 32, 7, 99, 130, 151}
)
