---
version: v2beta1

vars:
  CCIP_ENV_STATE_DIR:
    source: env
  LOCAL_TEMPLATES_DIR:
    source: env
    default: ./templates
  LOCAL_VALUES_DIR:
    source: env
    default: ./values
  NODES_COUNT:
    source: env
    default: 3
  # This is just a hack to always enable the profile
  ENABLE_BASE_PROFILE:
    source: env
    default: true
  ENABLE_RMN:
    source: env
    default: true
  RAGE_PROXY_IMAGE_SHA:
    source: env
    default: "16f5d86"
  RMN_IMAGE_SHA:
    source: env
    default: "10b42b2"
pipelines:
  deploy:
    run: |-
      if [ "$PROVIDER" == "kind" ]; then
        ensure_pull_secrets --all
      fi

      if [ "${NODES_COUNT}" -gt 0 ]; then
        create_deployments --all
      fi

profiles:
  - name: base
    activation:
      - vars:
          ENABLE_RMN: "true"
    merge: |-
      $(
        if [ "${NODES_COUNT}" -gt 0 ]; then
          pushd ./scripts/render_template > /dev/null
          go run main.go \
            -nodes-count="${NODES_COUNT}" -provider="${PROVIDER}" \
            -ccip-env-state-dir="${CCIP_ENV_STATE_DIR}"
        else
          echo "deployments:"
        fi
      )
  - name: local-charts
    merge: |-
      $(
        if [ "${NODES_COUNT}" -gt 0 ]; then
          pushd ./scripts/render_template > /dev/null
          go run main.go -provider="${PROVIDER}" \
            -nodes-count="${NODES_COUNT}" \
            -ccip-env-state-dir="${CCIP_ENV_STATE_DIR}" \
            -template="local-charts.yaml.tmpl"
        else
          echo "deployments:"
        fi
      )
  - name: kind
    activation:
      - vars:
          ENABLE_RMN: "true"
          PROVIDER: "kind"
    merge: |-
      $(
        if [ "${NODES_COUNT}" -gt 0 ]; then
          pushd ./scripts/render_template > /dev/null
          go run main.go -provider="${PROVIDER}" \
            -nodes-count="${NODES_COUNT}" \
            -ccip-env-state-dir="${CCIP_ENV_STATE_DIR}" \
            -template="env.kind.yaml.tmpl"
        else
          echo "deployments:"
        fi
      )
