version: v2beta1

dependencies:
  prometheus:
    path: ${DEPENDENCIES_DIR}/prometheus
    overwriteVars: true
    namespace: ${DEVSPACE_NAMESPACE}
    profiles:
      - add-beholder-config
  grafana:
    path: ${DEPENDENCIES_DIR}/grafana
    overwriteVars: true
    namespace: ${DEVSPACE_NAMESPACE}
    profiles:
      - add-beholder-config
  loki:
    path: ${DEPENDENCIES_DIR}/loki
    overwriteVars: true
    namespace: ${DEVSPACE_NAMESPACE}
    profiles:
      - add-beholder-config
  tempo:
    path: ${DEPENDENCIES_DIR}/tempo
    overwriteVars: true
    namespace: ${DEVSPACE_NAMESPACE}
    profiles:
      - add-beholder-config
  redpanda:
    path: ${DEPENDENCIES_DIR}/redpanda
    overwriteVars: true
    namespace: ${DEVSPACE_NAMESPACE}

pullSecrets:
  regcred-beholder:
    registry: 804282218731.dkr.ecr.us-west-2.amazonaws.com
    secret: regcred-beholder

pipelines:
  ci-e2e-test:
    run: |-
      run_dependency_pipelines prometheus grafana loki tempo redpanda
      create_deployments beholder-otel-collector-agent beholder-otel-collector-gateway
  load-test:
    run: |-
      run_dependency_pipelines redpanda
      create_deployments beholder-otel-collector-agent beholder-otel-collector-gateway
      wait_pod --namespace ${DEVSPACE_NAMESPACE} --label-selector app.kubernetes.io/instance=beholder-otel-collector-agent
      wait_pod --namespace ${DEVSPACE_NAMESPACE} --label-selector app.kubernetes.io/instance=beholder-otel-collector-gateway
      create_deployments beholder-load-tester
  kind:
    run: |-
      run_dependency_pipelines prometheus grafana loki tempo redpanda
      ensure_pull_secrets regcred-beholder
      create_deployments beholder-test-client beholder-otel-collector-agent beholder-otel-collector-gateway
  deploy:
    run: |-
      run_dependency_pipelines prometheus grafana loki tempo redpanda
      create_deployments beholder-test-client beholder-otel-collector-agent beholder-otel-collector-gateway

deployments:
  beholder-test-client:
    updateImageTags: false
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      releaseName: beholder-test-client
      displayOutput: true
      chart:
        name: ${CHAINLINK_HELM_REGISTRY_URI}/beholder-test-client
        version: "0.0.4"
      values:
        podSecurityContext:
          fsGroup: 999

        beholder-test-client:
          args:
            - -otel-exporter-grpc-enpoint
            - beholder-otel-collector-agent:4317

  beholder-load-tester:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - image: 804282218731.dkr.ecr.us-west-2.amazonaws.com/atlas-beholder-load-tester:014083bba4a7a47de8658bceb1428e6df1781161
            env:
              - name: OTEL_COLLECTOR_GRPC_ENDPOINT
                value: "beholder-otel-collector-agent:4317"
              - name: OTEL_METRICS_READER_INTERVAL
                value: "${OTEL_METRICS_READER_INTERVAL}"
              - name: OTEL_TRACE_SAMPLE_RATIO
                value: "${OTEL_TRACE_SAMPLE_RATIO}"
              - name: METRICS_ENABLED
                value: "${METRICS_ENABLED}"
              - name: METRICS_GAUGE_ATTRIBUTES_COUNT
                value: "${METRICS_GAUGE_ATTRIBUTES_COUNT}"
              - name: METRICS_BYTES_PER_ATTRIBUTE
                value: "${METRICS_BYTES_PER_ATTRIBUTE}"
              - name: TRACES_ENABLED
                value: "${TRACES_ENABLED}"
              - name: TRACES_TRACE_DEPTH
                value: "${TRACES_TRACE_DEPTH}"
              - name: TRACES_ATTRIBUTES_COUNT
                value: "${TRACES_ATTRIBUTES_COUNT}"
              - name: TRACES_BYTES_PER_ATTRIBUTE
                value: "${TRACES_BYTES_PER_ATTRIBUTE}"
              - name: CUSTOM_MESSAGES_ENABLED
                value: "${CUSTOM_MESSAGES_ENABLED}"
              - name: CUSTOM_MESSAGES_PAYLOAD_BYTES
                value: "${CUSTOM_MESSAGES_PAYLOAD_BYTES}"
              - name: SCHEDULE_FROM
                value: "${SCHEDULE_FROM}"
              - name: SCHEDULE_INCREASE
                value: "${SCHEDULE_INCREASE}"
              - name: SCHEDULE_STEPS
                value: "${SCHEDULE_STEPS}"
              - name: SCHEDULE_STEPS_DURATION
                value: "${SCHEDULE_STEPS_DURATION}"
              - name: SCHEDULE_PLAIN_DURATION
                value: "${SCHEDULE_PLAIN_DURATION}"
              - name: LOKI_TENANT_ID
                value: "${LOKI_TENANT_ID}"
              - name: LOKI_URL
                value: "${LOKI_URL}"
        podSecurityContext:
          fsGroup: 65534
        securityContext:
          runAsUser: 65534
          runAsGroup: 65534
          fsGroup: 65534
        service:
          name: beholder-load-tester
          selector:
            app: beholder-load-tester

  beholder-otel-collector-agent:
    updateImageTags: false
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      releaseName: beholder-otel-collector-agent
      displayOutput: true
      chart:
        name: opentelemetry-collector
        repo: https://open-telemetry.github.io/opentelemetry-helm-charts
        version: "0.101.2"
      values:
        fullnameOverride: beholder-otel-collector-agent
        mode: deployment
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1001
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        image:
          repository: otel/opentelemetry-collector
          tag: 0.106.1
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
          exporters:
            debug:
              verbosity: detailed
            otlp:
              endpoint: beholder-otel-collector-gateway:4317
              tls:
                insecure: true
          service:
            telemetry:
              logs:
                level: "debug"
            pipelines:
              traces:
                receivers: [otlp]
                exporters: [debug, otlp]
              metrics:
                receivers: [otlp]
                exporters: [debug, otlp]
              logs:
                receivers: [otlp]
                exporters: [debug, otlp]
        ingress:
          enabled: true
          ingressClassName: "alb"
          annotations:
            alb.ingress.kubernetes.io/backend-protocol: HTTP
            alb.ingress.kubernetes.io/certificate-arn: "${DEVSPACE_INGRESS_CERT_ARN}"
            alb.ingress.kubernetes.io/group.name: "${DEVSPACE_NAMESPACE}"
            alb.ingress.kubernetes.io/scheme: internal
            alb.ingress.kubernetes.io/target-type: ip
            external-dns.alpha.kubernetes.io/ttl: "120"
          hosts:
            - host: ${DEVSPACE_NAMESPACE}-beholder-otel-collector-agent-http.${DEVSPACE_INGRESS_BASE_DOMAIN}
              paths:
                - path: /
                  port: 4318
                  pathType: Prefix
        ports:
          metrics:
            enabled: true
        serviceMonitor:
          enabled: true
          metricsEndpoints:
            - port: metrics
              interval: 1s
          extraLabels:
            release: prometheus

  beholder-otel-collector-gateway:
    updateImageTags: false
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      releaseName: beholder-otel-collector-gateway
      displayOutput: true
      chart:
        name: opentelemetry-collector
        repo: https://open-telemetry.github.io/opentelemetry-helm-charts
        version: "0.101.2"
      values:
        fullnameOverride: beholder-otel-collector-gateway
        mode: deployment
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1001
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        image:
          repository: otel/opentelemetry-collector
          tag: 0.106.1
        ports:
          prometheus:
            enabled: true
            containerPort: 8889
            servicePort: 8889
            hostPort: 8889
            protocol: TCP
          metrics:
            enabled: true
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
            prometheus:
              config:
                scrape_configs:
                  - job_name: "otel-collector"
                    scrape_interval: 5s
                    static_configs:
                      - targets: ["127.0.0.1:8888"]
                  - job_name: "beholder-demo"
                    scrape_interval: 5s
                    static_configs:
                      - targets: ["beholder-test-client:9091"]
          exporters:
            debug:
              verbosity: detailed
            kafka:
              brokers:
                - redpanda:9093
              topic: beholder-test-client
              encoding: otlp_json
            prometheus:
              endpoint: "0.0.0.0:8889"
          service:
            telemetry:
              logs:
                level: "debug"
            pipelines:
              traces:
                receivers: [otlp]
                exporters: [debug, kafka]
              metrics:
                receivers: [otlp, prometheus]
                exporters: [debug, kafka, prometheus]
              logs:
                receivers: [otlp]
                exporters: [debug, kafka]
        serviceMonitor:
          enabled: true
          metricsEndpoints:
            - port: metrics
              interval: 1s
          extraLabels:
            release: prometheus

profiles:
  - name: kind
    merge:
      deployments:
        beholder-test-client:
          helm:
            values:
              beholder-test-client:
                affinity: []
                topologySpreadConstraints: []
                imagePullSecrets:
                  - name: regcred-beholder
  - name: local-charts
    merge:
      deployments:
        beholder-test-client:
          helm:
            chart:
              name: beholder-test-client
              path: ${CHAINLINK_CODE_DIR}/infra-charts/beholder-test-client
              version: null
  - name: ci-e2e-test
    patches:
      - op: remove
        path: deployments.beholder-otel-collector-gateway.helm.values.config.receivers.prometheus
      - op: remove
        path: deployments.beholder-otel-collector-gateway.helm.values.config.exporters.prometheus
    merge:
      deployments:
        beholder-otel-collector-gateway:
          helm:
            values:
              config:
                exporters:
                  debug:
                    verbosity: detailed
                  kafka:
                    brokers:
                      - redpanda:9093
                    topic: beholder_otlp_logs
                    encoding: otlp_json
                service:
                  telemetry:
                    logs:
                      level: "debug"
                  pipelines:
                    traces:
                      receivers: [otlp]
                      exporters: [debug, kafka]
                    metrics:
                      receivers: [otlp]
                      exporters: [debug, kafka]
                    logs:
                      receivers: [otlp]
                      exporters: [debug, kafka]
  - name: load-test
    patches:
      - op: add
        path: vars
        value:
          OTEL_METRICS_READER_INTERVAL:
            default: "1s"
          OTEL_TRACE_SAMPLE_RATIO:
            default: "1.0"
          METRICS_ENABLED:
            default: "true"
          METRICS_GAUGE_ATTRIBUTES_COUNT:
            default: "5"
          METRICS_BYTES_PER_ATTRIBUTE:
            default: "15"
          TRACES_ENABLED:
            default: "true"
          TRACES_TRACE_DEPTH:
            default: "5"
          TRACES_ATTRIBUTES_COUNT:
            default: "5"
          TRACES_BYTES_PER_ATTRIBUTE:
            default: "15"
          CUSTOM_MESSAGES_ENABLED:
            default: "true"
          CUSTOM_MESSAGES_PAYLOAD_BYTES:
            default: "100"
          SCHEDULE_FROM:
            default: "1"
          SCHEDULE_INCREASE:
            default: "5"
          SCHEDULE_STEPS:
            default: "100"
          SCHEDULE_STEPS_DURATION:
            default: "4m"
          SCHEDULE_PLAIN_DURATION:
            default: "3m"
          LOKI_TENANT_ID:
            default: ""
          LOKI_URL:
            default: ""
