version: v2beta1

pipelines:
  beholder:
    run: |-
      create_deployments crib-beholder-infra
      create_deployments beholder-test-client

deployments:
  beholder-test-client:
    updateImageTags: false
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      releaseName: beholder-test-client
      displayOutput: true
      chart:
        name: ${CHAINLINK_HELM_REGISTRY_URI}/beholder-test-client
        version: "0.0.3"
      values:
        podSecurityContext:
          fsGroup: 999

        beholder-test-client:
          args:
            - -otel-exporter-grpc-enpoint
            - crib-beholder-infra-otel-collector-agent:4317

  crib-beholder-infra:
    updateImageTags: false
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      releaseName: crib-beholder-infra
      displayOutput: true
      chart:
        name: ${CHAINLINK_HELM_REGISTRY_URI}/crib-beholder-infra
        version: "0.0.4"
      values:
        podSecurityContext:
          fsGroup: 999

        otel-collector-agent:
          config:
            exporters:
              otlp:
                endpoint: crib-beholder-infra-otel-collector-gateway:4317

        otel-collector-gateway:
          config:
            exporters:
              kafka:
                brokers:
                  - crib-beholder-infra-kafka:9092


profiles:
  - name: local-charts
    merge:
      deployments:
        beholder-test-client:
          helm:
            chart:
              name: beholder-test-client
              path: ${CHAINLINK_CODE_DIR}/infra-charts/beholder-test-client
              version: null
        crib-beholder-infra:
          helm:
            chart:
              name: crib-beholder-infra
              path: ${CHAINLINK_CODE_DIR}/infra-charts/crib-beholder-infra
              version: null
