version: v2beta1

pipelines:
  beholder:
    run: |-
      run_pipelines beholder-test-client

  beholder-test-client:
    run: |-
      create_deployments beholder-test-client

deployments:
  beholder-test-client:
    updateImageTags: false 
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      releaseName: beholder-test-client
      displayOutput: true
      chart:
        name: ${CHAINLINK_HELM_REGISTRY_URI}/crib-beholder
        version: "0.0.1"
      values:
        podSecurityContext:
          fsGroup: 999

profiles:
  - name: local-charts
    merge:
      deployments:
        beholder-test-client:
          helm:
            chart:
              name: beholder-test-client
              path: ${CHAINLINK_CODE_DIR}/infra-charts/crib-beholder
              version: null
