version: v2beta1

pipelines:
  beholder:
    run: |-
      create_deployments configs
      create_deployments beholder-prometheus
      create_deployments beholder-grafana
      create_deployments beholder-loki
      create_deployments beholder-tempo
      create_deployments crib-beholder-infra
      create_deployments beholder-test-client

deployments:
  configs:
    kubectl:
      manifests:
        - ${COMPONENTS_DIR}/beholder/configmaps/prometheus.yaml
        - ${COMPONENTS_DIR}/beholder/configmaps/grafana.yaml
        - ${COMPONENTS_DIR}/beholder/configmaps/loki.yaml
        - ${COMPONENTS_DIR}/beholder/configmaps/tempo.yaml

  beholder-test-client:
    updateImageTags: false
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      releaseName: beholder-test-client
      displayOutput: true
      chart:
        name: ${CHAINLINK_HELM_REGISTRY_URI}/beholder-test-client
        version: "0.0.3"
      values:
        podSecurityContext:
          fsGroup: 999

        beholder-test-client:
          args:
            - -otel-exporter-grpc-enpoint
            - crib-beholder-infra-otel-collector-agent:4317

  beholder-prometheus:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - image: prom/prometheus
            args:
              - "--config.file=/etc/prometheus/config/prometheus.yml"
            volumeMounts:
              - containerPath: /etc/prometheus/config
                volume:
                  name: config-volume
        podSecurityContext:
          fsGroup: 65534
        securityContext:
          runAsUser: 65534
          runAsGroup: 65534
          fsGroup: 65534
        service:
          name: beholder-prometheus
          selector:
            app: beholder-prometheus
          ports:
            - port: 9090
        volumes:
          - name: config-volume
            configMap:
              name: prometheus-config

  beholder-grafana:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - image: grafana/grafana
            volumeMounts:
              - containerPath: /etc/grafana/provisioning
                volume:
                  name: config-volume
            env:
              - name: GF_AUTH_ANONYMOUS_ENABLED
                value: "true"
              - name: GF_AUTH_ANONYMOUS_ORG_ROLE
                value: "Admin"
              - name: GF_AUTH_DISABLE_LOGIN_FORM
                value: "true"
              - name: GF_FEATURE_TOGGLES_ENABLE
                value: "traceqlEditor traceQLStreaming metricsSummary"
        volumes:
          - name: config-volume
            configMap:
              name: grafana-config
              items:
                - key: datasources.yml
                  path: datasources/datasources.yml
                - key: main.yml
                  path: dashboards/main.yml
                - key: beholder-demo-dashboard.json
                  path: dashboards/beholder-demo-dashboard.json
        service:
          name: beholder-grafana
          ports:
            - port: 3000
        podSecurityContext:
          fsGroup: 999
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          fsGroup: 999

  beholder-loki:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - image: grafana/loki:3.1.0
            args:
              - "--config.file=/etc/loki/config/loki.yml"
            volumeMounts:
              - containerPath: /etc/loki/config
                volume:
                  name: config-volume
        volumes:
          - name: config-volume
            configMap:
              name: loki-config

        service:
          name: beholder-loki
          ports:
            - port: 3100
        podSecurityContext:
          fsGroup: 999
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          fsGroup: 999

  beholder-tempo:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - image: grafana/tempo:2.5.0
            args:
              - "-config.file=/etc/tempo/config/tempo.yml"

            volumeMounts:
              - containerPath: /etc/tempo/config
                volume:
                  name: config-volume
        volumes:
          - name: config-volume
            configMap:
              name: tempo-config

        service:
          name: beholder-tempo
          ports:
            - port: 4317
            - port: 3200
        podSecurityContext:
          fsGroup: 10001
        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
          fsGroup: 10001

  crib-beholder-infra:
    updateImageTags: false
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      releaseName: crib-beholder-infra
      displayOutput: true
      chart:
        name: ${CHAINLINK_HELM_REGISTRY_URI}/crib-beholder-infra
        version: "0.0.4"
      values:
        podSecurityContext:
          fsGroup: 999

        otel-collector-agent:
          config:
            exporters:
              otlp:
                endpoint: crib-beholder-infra-otel-collector-gateway:4317

        otel-collector-gateway:
          config:
            exporters:
              kafka:
                brokers:
                  - crib-beholder-infra-kafka:9092


profiles:
  - name: local-charts
    merge:
      deployments:
        beholder-test-client:
          helm:
            chart:
              name: beholder-test-client
              path: ${CHAINLINK_CODE_DIR}/infra-charts/beholder-test-client
              version: null
        crib-beholder-infra:
          helm:
            chart:
              name: crib-beholder-infra
              path: ${CHAINLINK_CODE_DIR}/infra-charts/crib-beholder-infra
              version: null
