[Load.CCIP.Load]
CribEnvDirectory = "/data/crib-env-state"
TestLabel = "CribTest"

# 0 - no chaos, 1 - rpc latency, 2 - full chaos suite
ChaosMode = 1
# works only with Load.CCIP.ChaosMode = 1
RPCLatency = "400ms"
RPCJitter = "0ms"
# We have 3 types of messages: TokenTransfer, ProgrammableTokenTransfer, Messaging
# Each message type has a ratio and a destination gas limit
# The sum of all ratios should be 100
# Messages that include data MUST have a `DataLengthBytes` field
MessageDetails = [
 # {Ratio = 100, MsgType = "TokenTransfer"},
 {Ratio = 3, MsgType = "TokenTransfer"},
 {Ratio = 82, MsgType = "ProgrammableTokenTransfer", DataLengthBytes = 5000, DestGasLimit=650_000},
 {Ratio = 10,  MsgType = "Messaging", DataLengthBytes = 10_000, DestGasLimit=800_000},
 {Ratio = 5,  MsgType = "Messaging", DataLengthBytes = 10_000, DestGasLimit=2_500_000},
]
# each destination chain will receive 1 incoming request per RequestFrequency for the duration of LoadDuration
RequestFrequency = "5s"
LoadDuration = "1h"
# destination chain selectors to send messages to
NumDestinationChains = 6
TimeoutDuration = "30m"