[Load.CCIP.Load]
CribEnvDirectory = "/data/crib-env-state"
TestLabel = "aw-remote-1"

# 0 - no chaos, 1 - rpc latency, 2 - full chaos suite
ChaosMode = 1
# works only with Load.CCIP.ChaosMode = 1
RPCLatency = "400ms"
RPCJitter = "0ms"
# We have 3 types of messages: TokenTransfer, ProgrammableTokenTransfer, Messaging
# Each message type has a ratio and a destination gas limit
# The sum of all ratios should be 100
# Messages that include data MUST have a `DataLengthBytes` field
MessageDetails = [
 {Ratio = 3, MsgType = "TokenTransfer"},
 {Ratio = 82, MsgType = "ProgrammableTokenTransfer", DataLengthBytes = 5000, DestGasLimit=650_000},
 {Ratio = 10,  MsgType = "Messaging", DataLengthBytes = 10_000, DestGasLimit=800_000},
 {Ratio = 5,  MsgType = "Messaging", DataLengthBytes = 10_000, DestGasLimit=2_500_000},
]
# each destination chain will receive 1 incoming request per RequestFrequency for the duration of LoadDuration
RequestFrequency = "5s"
LoadDuration = "8h"
# destination chain selectors to send messages to
NumDestinationChains = 15
TimeoutDuration = "1h"
OOOExecution = false



[CCIP.Chaos]
# works only with Load.CCIP.ChaosMode = 2
Namespace = "crib-aw-remote"
# RPC, commit, exec dashboards, can be found here: https://grafana.ops.prod.cldev.sh/d/dde396ff-5d22-42fb-9e92-00845c17688c/load-ccipv2-exec-plugin-v2?orgId=1&editview=dashboard_json
DashboardUIDs = []
WaitBeforeStart = "0s"
# Chaos experiment total duration (chaos + recovery)
ExperimentFullInterval = "9h"
# Chaos time
ExperimentInjectionInterval = "5m"
# Src and Dst chain URLs, change it according to your namespace name
SrcChainURL = "https://crib-ccip-chaos-tests-geth-1337-http.main.stage.cldev.sh"
DstChainURL = "https://crib-ccip-chaos-tests-geth-2337-http.main.stage.cldev.sh"