version: v2beta1

pipelines:
  deploy:
    run: |-
      create_deployments configs
      create_deployments loki

deployments:
  configs:
    kubectl:
      manifests:
        - ${COMPONENTS_DIR}/loki/configmaps/default.yaml

  loki:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - image: grafana/loki:3.1.0
            args:
              - "--config.file=/etc/loki/config/loki.yml"
            volumeMounts:
              - containerPath: /etc/loki/config
                volume:
                  name: config-volume
        volumes:
          - name: config-volume
            configMap:
              name: loki-config

        service:
          name: loki
          ports:
            - port: 3100
        podSecurityContext:
          fsGroup: 999
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          fsGroup: 999

profiles:
  - name: add-beholder-config
    patches:
      - op: replace
        path: deployments.configs.kubectl.manifests[0]
        value: ${COMPONENTS_DIR}/loki/configmaps/beholder.yaml
