version: v2beta1
name: blockscout

vars:
  # Check image versions against compatibility matrix
  #  https://docs.blockscout.com/setup/requirements/back-front-compatibility-matrix
  BLOCKSCOUT_BACKEND_IMAGE_TAG:
    source: env
    value: "6.10.2"
  BLOCKSCOUT_FRONTEND_IMAGE_TAG:
    source: env
    value: "v1.37.5"
  LOCAL_TEMPLATES_DIR:
    source: env
    default: ./templates
  ETHEREUM_VARIANT:
    source: env
    default: besu # or geth
  CHAIN_NAME:
    source: env
    default: ""
  CHAIN_ID:
    source: env
    default: ""
  CHAIN_TYPE:
    source: env
    default: "EVM"
  ENABLE_BASE:
    source: env
    default: true
  ENVIRONMENT:
    source: env
    default: sandbox
  NAMESPACE:
    source: env
    default: ${DEVSPACE_NAMESPACE}

pipelines:
  deploy:
    run: |-
      echo "DEVSPACE_INGRESS_BASE_DOMAIN: ${DEVSPACE_INGRESS_BASE_DOMAIN}"
      create_deployments blockscout-postgres-${ETHEREUM_VARIANT}-chain-${CHAIN_NAME}-${CHAIN_ID}
      create_deployments blockscout-${ETHEREUM_VARIANT}-chain-${CHAIN_NAME}-${CHAIN_ID}

hooks:
  - name: set-devspace-namespace
    command: |-
      devspace use namespace ${NAMESPACE}
    events: ["before:deploy:blockscout-postgres-${ETHEREUM_VARIANT}-chain-${CHAIN_NAME}-${CHAIN_ID}"]

profiles:
  - name: base
    activation:
      - vars:
          ENABLE_BASE: "true"
    merge: |-
      $(
        CHAIN_ID=${CHAIN_ID} \
        CHAIN_NAME=${CHAIN_NAME} \
        DEVSPACE_INGRESS_BASE_DOMAIN=${DEVSPACE_INGRESS_BASE_DOMAIN} \
        ETHEREUM_VARIANT=${ETHEREUM_VARIANT} \
        gomplate \
          --config ${LOCAL_TEMPLATES_DIR}/blockscout.base.yaml
      )

  - name: kind
    activation:
      - vars:
          PROVIDER: "kind"
    merge: |-
      $(
        CHAIN_ID=${CHAIN_ID} \
        CHAIN_NAME=${CHAIN_NAME} \
        ETHEREUM_VARIANT=${ETHEREUM_VARIANT} \
        gomplate \
          --config ${LOCAL_TEMPLATES_DIR}/blockscout.env.crib-kind.yaml
      )

  - name: aws
    activation:
      - vars:
          PROVIDER: "aws"
          ENVIROMENT: "stage"
    merge: |-
      $(
        CHAIN_ID=${CHAIN_ID} \
        CHAIN_NAME=${CHAIN_NAME} \
        ETHEREUM_VARIANT=${ETHEREUM_VARIANT} \
        gomplate \
          --config ${LOCAL_TEMPLATES_DIR}/blockscout.env.crib-staging.yaml
      )

  - name: aws-sandbox
    activation:
      - vars:
          ENVIRONMENT: "sandbox"
    merge: |-
      $(
        CHAIN_ID=${CHAIN_ID} \
        CHAIN_NAME=${CHAIN_NAME} \
        DEVSPACE_INGRESS_BASE_DOMAIN=${DEVSPACE_INGRESS_BASE_DOMAIN} \
        ETHEREUM_VARIANT=${ETHEREUM_VARIANT} \
        gomplate \
          --config ${LOCAL_TEMPLATES_DIR}/blockscout.env.crib-sandbox.yaml
      )
