version: v2beta1
name: chainlink

vars:
  SCRIPTS_DIR:
    source: env
    default: "../../scripts"
  DEVSPACE_ENV_FILE: .env
  DEPENDENCIES_DIR:
    source: env
    default: "../../dependencies"
  IMPORTS_DIR:
    source: env
    default: "../../imports"
  # "The provider being used to deploy CRIB"
  PROVIDER:
    source: all
    default: "aws"
  CHAINLINK_CODE_DIR:
    source: env
    default: "../../.."
  CHAINLINK_HELM_REGISTRY_URI:
    source: env
    default: "oci://804282218731.dkr.ecr.us-west-2.amazonaws.com/infra-charts"


imports:
  - path: ${IMPORTS_DIR}/lib-common
  - path: ${IMPORTS_DIR}/lib-aws
  - path: ${IMPORTS_DIR}/lib-kind

pipelines:
  core:
    run: |-
      run_dependency_pipelines crib-chainlink-cluster geth mockserver
      run_pipelines ingress-check

  core-no-geth:
    run: |-
      run_dependency_pipelines crib-chainlink-cluster mockserver
      run_pipelines ingress-check

  ccip:
    run: |-
      run_dependency_pipelines crib-chainlink-cluster geth mockserver
      run_dependency_pipelines crib-ccip-scripts
      run_pipelines ingress-check

  ccip-no-geth:
    run: |-
      run_dependency_pipelines crib-chainlink-cluster mockserver
      run_dependency_pipelines crib-ccip-scripts
      run_pipelines ingress-check

  ccip-don:
    run: |-
      run_dependency_pipelines crib-chainlink-cluster geth mockserver
      run_pipelines ingress-check

  ccip-scripts:
    run: |-
      run_dependency_pipelines crib-ccip-scripts

  ccip-v2:
    run: |-
      run_dependency_pipelines geth
      # Deploy CCIP enabled fully configured DON
      run_dependency_pipelines donut-cluster
      run_pipelines ingress-check

  keystone:
    run: |-
      run_dependency_pipelines crib-chainlink-cluster geth mock-external-adapter
      run_pipelines ingress-check

  kind-dependencies:
    run: |-
      run_dependency_pipelines prometheus-crds
      run_dependency_pipelines ingress-controller
      run_dependency_pipelines cert-manager
      run_dependency_pipelines loki
      run_dependency_pipelines promtail
      run_dependency_pipelines grafana

  core-kind:
    run: |-
      run_pipelines kind-dependencies
      run_pipelines core

  ccip-kind:
    run: |-
      run_pipelines kind-dependencies
      run_pipelines ccip

  keystone-kind:
    flags:
      - name: skip_provision
    run: |-
      run_pipelines kind-dependencies
      run_pipelines keystone

  ccip-atlas:
    run: |-
      run_pipelines ccip
      run_dependency_pipelines atlas

  ccip-atlas-kind:
    run: |-
      run_pipelines kind-dependencies
      run_pipelines ccip
      run_dependency_pipelines atlas

  ccip-atlas-ui:
    run: |-
      run_pipelines ccip-atlas
      run_dependency_pipelines ccip-ui

  beholder:
    run: |-
      run_dependency_pipelines beholder

  blockscout:
    run: |-
      run_dependency_pipelines blockscout
      run_pipelines ingress-check

profiles:
  - name: core
    patches:
      - op: add
        path: vars
        value:
          CHAINLINK_REPO_DIR:
            source: env
            default: "${CHAINLINK_CODE_DIR}/chainlink"
      - op: add
        path: dependencies
        value:
          crib-chainlink-cluster:
            path: ${DEPENDENCIES_DIR}/crib-chainlink-cluster
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            profiles:
              - core
          geth:
            path: ${DEPENDENCIES_DIR}/geth
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
          mockserver:
            path: ${DEPENDENCIES_DIR}/mockserver
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
  - name: core-no-geth
    patches:
      - op: add
        path: vars
        value:
          CHAINLINK_REPO_DIR:
            source: env
            default: "${CHAINLINK_CODE_DIR}/chainlink"
      - op: add
        path: dependencies
        value:
          crib-chainlink-cluster:
            path: ${DEPENDENCIES_DIR}/crib-chainlink-cluster
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            profiles:
              - core
          mockserver:
            path: ${DEPENDENCIES_DIR}/mockserver
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
  - name: core-dev-ocr2-external-network
    parents:
      - profile: core-no-geth
    patches:
      - op: replace
        path: dependencies.crib-chainlink-cluster.profiles
        value:
          - local-dev
  - name: core-dev-simulated-core-ocr1-stateless
    parents:
      - profile: core
    patches:
      - op: replace
        path: dependencies.crib-chainlink-cluster.profiles
        value:
          - local-dev-simulated-core-ocr1-stateless
  - name: core-dev-simulated-core-ocr1
    parents:
      - profile: core
    patches:
      - op: replace
        path: dependencies.crib-chainlink-cluster.profiles
        value:
          - local-dev-simulated-core-ocr1
      - op: replace
        path: dependencies.geth.profiles
        value:
          - local-dev-simulated-core-ocr1

  - name: keystone-kind
    parents:
      - profile: keystone
      - profile: kind-dependencies
    patches:
      - op: add
        path: dependencies.crib-chainlink-cluster.profiles
        value: kind
      - op: replace
        path: dependencies.crib-chainlink-cluster.pipeline
        value: keystone-kind
      - op: replace
        path: dependencies.geth.profiles
        value:
          - kind
      - op: replace
        path: dependencies.mockserver.profiles
        value:
          - kind

  - name: keystone-kind-git-charts
    parents:
      - profile: keystone-kind
    patches:
      - op: add
        path: dependencies.crib-chainlink-cluster.profiles
        value: git-charts
      - op: add
        path: dependencies.geth.profiles
        value: git-charts

  - name: keystone
    parents:
      - profile: core
    patches:
      - op: add
        path: vars
        value:
          # A private key that contains sepolia ETH to use for contract deployment and funding transmitters.
          KEYSTONE_ACCOUNT_KEY:
            source: env
      - op: add
        path: dependencies
        value:
          mock-external-adapter:
            path: ${DEPENDENCIES_DIR}/mock-external-adapter
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
      - op: replace
        path: dependencies.crib-chainlink-cluster.profiles
        value:
          - keystone
      - op: add
        path: dependencies.crib-chainlink-cluster.pipeline
        value: keystone
  - name: ccip
    patches:
      - op: add
        path: vars
        value:
          CHAINLINK_REPO_DIR:
            source: env
            default: "${CHAINLINK_CODE_DIR}/ccip"
      - op: add
        path: dependencies
        value:
          crib-chainlink-cluster:
            path: ${DEPENDENCIES_DIR}/crib-chainlink-cluster
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            profiles:
              - ccip
          crib-ccip-scripts:
            path: ${DEPENDENCIES_DIR}/crib-ccip-scripts
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
          geth:
            path: ${DEPENDENCIES_DIR}/geth
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            profiles:
              - ccip
          mockserver:
            path: ${DEPENDENCIES_DIR}/mockserver
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
  - name: ccip-no-geth
    patches:
      - op: add
        path: vars
        value:
          CHAINLINK_REPO_DIR:
            source: env
            default: "${CHAINLINK_CODE_DIR}/ccip"
      - op: add
        path: dependencies
        value:
          crib-chainlink-cluster:
            path: ${DEPENDENCIES_DIR}/crib-chainlink-cluster
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            profiles:
              - ccip
          crib-ccip-scripts:
            path: ${DEPENDENCIES_DIR}/crib-ccip-scripts
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
          mockserver:
            path: ${DEPENDENCIES_DIR}/mockserver
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
  - name: ccip-local
    parents:
      - profile: ccip
    patches:
      - op: replace
        path: dependencies.crib-chainlink-cluster.profiles
        value:
          - ccip
          - local-charts
      - op: add
        path: dependencies.crib-ccip-scripts.profiles
        value:
          - local-charts
      - op: add
        path: dependencies.geth.profiles
        value:
          - local-charts
  - name: ccip-eks-bix-ship
    parents:
      - profile: ccip
    patches:
      - op: add
        path: dependencies.crib-chainlink-cluster.profiles
        value: ccip-eks-bix-ship
      - op: add
        path: dependencies.crib-ccip-scripts.profiles
        value: ccip-eks-bix-ship
  - name: ccip-kind-bix-ship
    parents:
      - profile: ccip-no-geth
    patches:
      - op: add
        path: dependencies.crib-chainlink-cluster.profiles
        value: ccip-kind-bix-ship
      - op: add
        path: dependencies.crib-chainlink-cluster.profiles
        value: kind
      - op: replace
        path: dependencies.crib-ccip-scripts.profiles
        value:
          - ccip-eks-bix-ship
  - name: ccip-v2
    patches:
      - op: add
        path: vars
        value:
          DON_TYPE:
            source: env
            default: ccip
          DON_NODE_COUNT:
            source: env
            default: 4
          DON_BOOT_NODE_COUNT:
            source: env
            default: 1
          DON_VERSION:
            source: env
            default: ccip-dev
          CCIP_TOOLING_VERSION:
            source: env
            default: v2
          INGRESS_CERT_ARN:
            source: env
            default: ${DEVSPACE_INGRESS_CERT_ARN}
      - op: add
        path: dependencies
        value:
          geth:
            path: ${DEPENDENCIES_DIR}/geth
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            profiles:
              - ccip
          donut-cluster:
            path: ${DEPENDENCIES_DIR}/donut/chainlink-don.yaml
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
            profiles:
              - network-geth-chain-1337
              - network-geth-chain-2337
  - name: kind-dependencies
    patches:
      - op: add
        path: dependencies
        value:
          prometheus-crds:
            path: ${DEPENDENCIES_DIR}/prometheus-crds
            namespace: prometheus-crds
            overwriteVars: true
          ingress-controller:
            path: ${DEPENDENCIES_DIR}/ingress-controller
            namespace: ingress-nginx
            overwriteVars: true
          cert-manager:
            path: ${DEPENDENCIES_DIR}/cert-manager
            namespace: cert-manager
            overwriteVars: true
          grafana:
            path: ${DEPENDENCIES_DIR}/grafana
            namespace: ${DEVSPACE_NAMESPACE}
            overwriteVars: true
            profiles:
              - kind
          loki:
            path: ${DEPENDENCIES_DIR}/loki
            namespace: ${DEVSPACE_NAMESPACE}
            overwriteVars: true
            profiles:
              - kind
          promtail:
            path: ${DEPENDENCIES_DIR}/promtail
            namespace: ${DEVSPACE_NAMESPACE}
            overwriteVars: true
            profiles:
              - default
  - name: core-kind
    parents:
      - profile: core
      - profile: kind-dependencies
    patches:
      - op: replace
        path: dependencies.crib-chainlink-cluster.profiles
        value:
          - core
          - kind
      - op: add
        path: dependencies.crib-chainlink-cluster.pipeline
        value: kind
      - op: replace
        path: dependencies.geth.profiles
        value:
          - kind
      - op: replace
        path: dependencies.mockserver.profiles
        value:
          - kind
  - name: ccip-kind
    parents:
      - profile: ccip
      - profile: kind-dependencies
    patches:
      - op: replace
        path: dependencies.crib-chainlink-cluster.profiles
        value:
          - ccip
          - kind
      - op: add
        path: dependencies.crib-chainlink-cluster.pipeline
        value: kind
      - op: add
        path: dependencies.crib-ccip-scripts.profiles
        value:
          - kind
      - op: add
        path: dependencies.crib-ccip-scripts.pipeline
        value: kind
      - op: replace
        path: dependencies.geth.profiles
        value:
          - ccip
          - kind
      - op: replace
        path: dependencies.mockserver.profiles
        value:
          - kind
  - name: atlas
    patches:
      - op: add
        path: dependencies
        value:
          atlas:
            path: ${DEPENDENCIES_DIR}/atlas/atlas.yaml
            namespace: ${DEVSPACE_NAMESPACE}
            overwriteVars: true
            pipeline: atlas
  - name: ccip-atlas
    parents:
      - profile: ccip
      - profile: atlas
  - name: ccip-atlas-ui
    parents:
      - profile: ccip
      - profile: atlas
  - name: ccip-atlas-kind
    parents:
      - profile: ccip-kind
      - profile: atlas
    patches:
      - op: replace
        path: dependencies.crib-chainlink-cluster.profiles
        value:
          - ccip
          - ccip-ui-ingress
      - op: add
        path: dependencies.atlas.profiles
        value:
          - kind
      - op: add
        path: dependencies
        value:
          ccip-ui:
            path: ${DEPENDENCIES_DIR}/ccip-ui
            namespace: ${DEVSPACE_NAMESPACE}
            overwriteVars: true
            pipeline: ccip-ui
  - name: beholder
    patches:
      - op: add
        path: dependencies
        value:
          beholder:
            path: ${DEPENDENCIES_DIR}/beholder
            #            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
  - name: beholder-load-test
    parents:
      - profile: beholder
    patches:
      - op: add
        path: dependencies.beholder.pipeline
        value: load-test
      - op: replace
        path: dependencies.beholder.profiles
        value:
          - load-test
  - name: beholder-kind
    parents:
      - profile: beholder
    patches:
      - op: replace
        path: dependencies.beholder.profiles
        value:
          - kind
      - op: add
        path: dependencies.beholder.pipeline
        value: kind
  - name: blockscout
    patches:
      - op: add
        path: dependencies
        value:
          blockscout:
            path: ${DEPENDENCIES_DIR}/blockscout
            overwriteVars: true
            namespace: ${DEVSPACE_NAMESPACE}
commands:
  core:
    command: devspace run-pipeline core -p core
    description: Run the Core pipeline.
    appendArgs: true
  core-kind:
    command: devspace run-pipeline core-kind -p core-kind
    description: Run the Core pipeline for Kind.
    appendArgs: true
  core-dev-ocr2-external-network:
    command: devspace run-pipeline core-no-geth -p core-dev-ocr2-external-network
    description: Run the Core pipeline with external network.
    appendArgs: true
  core-dev-simulated-core-ocr1-stateless:
    command: devspace run-pipeline core -p core-dev-simulated-core-ocr1-stateless
    description: Run the Core pipeline with external network.
    appendArgs: true
  core-dev-simulated-core-ocr1:
    command: devspace run-pipeline core -p core-dev-simulated-core-ocr1
    description: Run the Core pipeline with external network.
    appendArgs: true
  keystone:
    command: devspace run-pipeline keystone -p keystone
    description: Run the Core pipeline with Keystone.
    appendArgs: true
  keystone-kind-git-charts:
    command: devspace run-pipeline keystone-kind -p keystone-kind-git-charts
    description: Run the Core pipeline with Keystone for Kind using git charts
    appendArgs: true
  keystone-kind:
    command: devspace run-pipeline keystone-kind -p keystone-kind
    description: Run the Core pipeline with Keystone for Kind.
    appendArgs: true
  ccip:
    command: devspace run-pipeline ccip -p ccip
    description: Run the CCIP pipeline.
    appendArgs: true
  ccip-kind:
    command: devspace run-pipeline ccip-kind -p ccip-kind
    description: Run the Core pipeline for Kind.
    appendArgs: true
  ccip-atlas-kind:
    command: devspace run-pipeline ccip-atlas-kind -p ccip-atlas-kind
    description: Run the Atlas pipeline for Kind.
    appendArgs: true
  ccip-local-charts:
    command: devspace run-pipeline ccip -p ccip-local
    description: Run the CCIP pipeline with local charts.
    appendArgs: true
  ccip-don-eks-bix-ship:
    command: devspace run-pipeline ccip-don -p ccip-eks-bix-ship
    description: Run the CCIP pipeline with EKS Bix Ship.
    appendArgs: true
  ccip-scripts-eks-bix-ship:
    command: devspace run-pipeline ccip-scripts -p ccip-eks-bix-ship
    description: Run the CCIP pipeline with EKS Bix Ship.
    appendArgs: true
  ccip-kind-bix-ship:
    command: devspace run-pipeline ccip-no-geth -p ccip-kind-bix-ship
    description: Run the CCIP pipeline with Kind Bix Ship.
    appendArgs: true
  ccip-atlas:
    command: devspace run-pipeline ccip-atlas -p ccip-atlas
    description: Run the CCIP pipeline with Atlas.
    appendArgs: true
  ccip-atlas-ui:
    command: devspace run-pipeline ccip-atlas-ui -p ccip-atlas-ui
    description: Run the CCIP pipeline with Atlas and UI.
    appendArgs: true
  ccip-v2:
    command: devspace run-pipeline ccip-v2 -p ccip-v2
    description: Run the ccip v2 pipeline.
    appendArgs: true
  beholder:
    command: devspace run-pipeline beholder -p beholder
    description: Run the Beholder pipeline.
    appendArgs: true
  beholder-load-test:
    command: devspace run-pipeline beholder -p beholder-load-test
    description: Run the Beholder pipeline for load test.
    appendArgs: true
  beholder-kind:
    command: devspace run-pipeline beholder -p beholder-kind
    description: Run the Beholder pipeline for Kind.
    appendArgs: true
  blockscout:
    command: devspace run-pipeline blockscout -p blockscout
    description: Run blockscout pipeline
    appendArgs: true
