version: v2beta1

pipelines:
  deploy:
    run: |-
      create_deployments ingress-controller

deployments:
  ingress-controller:
    helm:
      chart:
        name: ingress-nginx
        repo: https://kubernetes.github.io/ingress-nginx