version: v2beta1
name: lib-common

vars:
  SCRIPTS_DIR:
    source: env
    default: "../../scripts"
  DEVSPACE_ENV_FILE: .env
  # The list of default ENV Vars for CRIB, you can override any of them in the .env file
  # AWS Account ID used for deploying CRIB environment
  AWS_ACCOUNT_ID:
    source: env
    default: 323150190480
  # Time to wait for pods to be in `Ready` condition
  DEVSPACE_K8S_POD_WAIT_TIMEOUT:
    source: env
    default: 1200s
  # Helm repo URI for the crib-ccip helm chart
  CHAINLINK_HELM_REGISTRY_URI:
    source: env
    default: "oci://804282218731.dkr.ecr.us-west-2.amazonaws.com/infra-charts"

pipelines:
  purge:
    run: |-
      kubectl delete ns ${DEVSPACE_NAMESPACE}
  ingress-check:
    run: |-
      crib devspace ingress-check

commands:
  show-pod-nodes:
    command: |
      kubectl get pods -n $DEVSPACE_NAMESPACE -o json | \
        jq -r '.items[] |
        "Pod: " + .metadata.name +
        " | Node: " + .spec.nodeName +
        " | NodeRole: " + (if .spec.nodeSelector."node-role" == "crib" then "crib" else "other" end)'
    description: |
      Show all pods and associated node with nodepool info. Useful to debug if the pod is scheduled on the desired NodePools
