version: v2beta1

pipelines:
  deploy:
    run: |-
      create_deployments redpanda

deployments:
  redpanda:
    updateImageTags: false
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      releaseName: redpanda
      displayOutput: true
      chart:
        name: redpanda
        repo: https://charts.redpanda.com
        version: "5.9.1"
      values:
        image:
          repository: docker.redpanda.com/redpandadata/redpanda
          tag: 'v24.1.15'
        statefulset:
          replicas: 1
          podTemplate:
            spec:
              securityContext:
                capabilities:
                  drop:
                    - ALL
                runAsUser: 999
                runAsGroup: 999
                runAsNonRoot: true
          sideCars:
            configWatcher:
              securityContext:
                capabilities:
                  drop:
                    - ALL
                runAsUser: 999
                runAsGroup: 999
                runAsNonRoot: true
            controllers:
              securityContext:
                capabilities:
                  drop:
                    - ALL
                runAsUser: 999
                runAsGroup: 999
                runAsNonRoot: true

        post_install_job:
          podTemplate:
            spec:
              securityContext:
                capabilities:
                  drop:
                    - ALL
                runAsUser: 999
                runAsGroup: 999
                runAsNonRoot: true
        post_upgrade_job:
          podTemplate:
            spec:
              securityContext:
                capabilities:
                  drop:
                    - ALL
                runAsUser: 999
                runAsGroup: 999
                runAsNonRoot: true
        tls:
          enabled: false
        config:
          cluster:
            auto_create_topics_enabled: true
        external:
          enabled: false
        tuning:
          tune_aio_events: false