name: CCIPv1.7 Soak Test

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode with tmate'
        type: boolean
        default: false

jobs:
  soak:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu24.04-16cores-64GB
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ secrets.PUBLIC_AWS_ECR_ROLE }}
          aws-region: us-east-1
      - name: Authenticate to ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registry-type: public
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
          cache: true
      - name: Run Observability Stack
        run: go run cmd/ccip.go obs u
      - name: Run CCIPv2 environment
        run: |
          cd cmd/ccip && go install . && cd -
          ccip u env-ci.toml
      - name: Run Soak Test
        working-directory: example/ccipv1_7/tests
        run: go test -timeout 2h -v -run TestSoak

defaults:
  run:
    working-directory: devenv/ccipv1_7
