---
name: CRIB Core Smoke Test

on:
  workflow_dispatch:
  push:
    paths:
      # Include common changes
      - "*"
      - "components/**"
      - "scripts/**"
      # Include crib core changes
      - "deployments/core/**"
      - "./github/workflows/crib-core-smoke-test.yml"
      # Exclude doc updates
      - '!**/*.md'  # Exclude doc updates

jobs:
  run-crib-core-smoke-test:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.2

      - name: Deploy and validate CRIB Environment for Core
        uses: smartcontractkit/.github/actions/setup-crib-environment@558c326193176424a00c2319cdaba49a0f4a547b
        with:
          api-gateway-host: ${{ secrets.AWS_API_GW_HOST_K8S_STAGE }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_OIDC_CRIB_ROLE_ARN_STAGE }}
          ecr-private-registry-stage: ${{ secrets.AWS_ACCOUNT_ID_STAGE }}
          ecr-private-registry: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
          ingress-base-domain: ${{ secrets.INGRESS_BASE_DOMAIN_STAGE }}
          k8s-cluster-name: ${{ secrets.AWS_K8S_CLUSTER_NAME_STAGE }}
          product: "core"
          working-directory: "deployments/core"
