---
name: CRIB Core Smoke Test

on:
  pull_request:
    branches:
      - "*" # Trigger on any branch in a PR
    paths:
      # Include common changes
      - "*"
      - "components/**"
      - "scripts/**"
      # Include crib core changes
      - "deployments/core/**"
      - ".github/workflows/crib-core-smoke-test.yml"
      # Exclude doc updates
      - "!**/*.md" # Exclude doc updates
      # Exclude .gitignore
      - "!.gitignore"
  push:
    branches:
      - main # Trigger only on pushes to the main branch
    paths:
      # Include common changes
      - "*"
      - "components/**"
      - "scripts/**"
      # Include crib core changes
      - "deployments/core/**"
      - ".github/workflows/crib-core-smoke-test.yml"
      # Exclude doc updates
      - "!**/*.md" # Exclude doc updates
      # Exclude .gitignore
      - "!.gitignore"
  workflow_dispatch:
    inputs:
      debug:
        description: |
          Enables debug mode to disable CRIB env teardown
        default: "false"
        required: false
jobs:
  run-crib-core-smoke-test:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout crib git repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Deploy and validate CRIB Environment for Core
        id: deploy
        uses: smartcontractkit/.github/actions/crib-deploy-environment@9a4954089045a765eca4bac68f396b2df5a5ea25 # crib-deploy-environment@0.7.1
        with:
          api-gateway-host: ${{ secrets.AWS_API_GW_HOST_K8S_STAGE }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_OIDC_CRIB_ROLE_ARN_STAGE }}
          ecr-private-registry-stage: ${{ secrets.AWS_ACCOUNT_ID_STAGE }}
          ecr-private-registry: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
          ingress-base-domain: ${{ secrets.INGRESS_BASE_DOMAIN_STAGE }}
          k8s-cluster-name: ${{ secrets.AWS_K8S_CLUSTER_NAME_STAGE }}
          product: "core"
          crib-alert-slack-webhook: ${{ secrets.CRIB_ALERT_SLACK_WEBHOOK }}

      - name: Destroy CRIB Environment
        id: destroy
        if: always() && steps.deploy.outputs.devspace-namespace != '' && inputs.debug != 'true'
        uses: smartcontractkit/.github/actions/crib-purge-environment@da1c0099f3bab236660ccc10328a29e06950c69f # crib-purge-environment@0.2.0
        with:
          namespace: ${{ steps.deploy.outputs.devspace-namespace }}
