name: CRIB Core Smoke Test

on:
  push:
    paths:
      - "deployments/core/**"
      - "!(deployments/ccip)/**" # Exclude changes in the ccip directory
      - "!*.md" # Exclude markdown files
      - "*" # Include any common changes

jobs:
  run-crib-core-smoke-test:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.2

      - name: Deploy and validate CRIB Environment for Core
        uses: smartcontractkit/.github/actions/setup-crib-environment@f4ad9dd6b47364c24302167c6ae8cc536096dde8
        with:
          api-gateway-host: ${{ secrets.AWS_API_GW_HOST_K8S_STAGE }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_OIDC_CRIB_ROLE_ARN_STAGE }}
          ecr-private-registry-stage: ${{ secrets.AWS_ACCOUNT_ID_STAGE }}
          ecr-private-registry: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
          ingress-base-domain: ${{ secrets.INGRESS_BASE_DOMAIN_STAGE }}
          k8s-cluster-name: ${{ secrets.AWS_K8S_CLUSTER_NAME_STAGE }}
          product: "core"
          working-directory: "deployments/core"
