---
name: CRIB Core Smoke Test

on:
  pull_request:
    branches:
      - "*" # Trigger on any branch in a PR
    paths:
      # Include common changes
      - "*"
      - "dependencies/crib-chainlink-cluster/**"
      - "scripts/**"
      # Include crib core changes
      - "deployments/chainlink/**"
      - ".github/workflows/crib-core-smoke-test.yml"
      # Exclude doc updates
      - "!**/*.md" # Exclude doc updates
      # Exclude .gitignore
      - "!.gitignore"
    types:
      - review_requested
      - ready_for_review
      - synchronize
  push:
    branches:
      - main # Trigger only on pushes to the main branch
    paths:
      # Include common changes
      - "*"
      - "dependencies/crib-chainlink-cluster/**"
      - "imports/**"
      - "scripts/**"
      # Include crib core changes
      - "deployments/chainlink/**"
      - ".github/workflows/crib-core-smoke-test.yml"
      # Exclude doc updates
      - "!**/*.md" # Exclude doc updates
      # Exclude .gitignore
      - "!.gitignore"
  workflow_dispatch:
    inputs:
      debug:
        description: |
          Enables debug mode to disable CRIB env teardown
        default: "false"
        required: false
jobs:
  run-crib-core-smoke-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Prevent running on draft PRs
        id: check-prereqs-for-running
        run: |
          should_run=true
          if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.pull_request.draft }}" == "true" ]; then
            should_run=false
          fi
          echo "should_run=$should_run" >> "$GITHUB_OUTPUT"
      - name: Deploy and validate CRIB Environment for Core
        if: steps.check-prereqs-for-running.outputs.should_run == 'true'
        id: deploy
        uses: smartcontractkit/.github/actions/crib-deploy-environment@fa63a0fb95039c4d89fec6a9a78b53c0cacf5457 # crib-deploy-environment@2.0.0
        with:
          api-gateway-host: ${{ secrets.AWS_API_GW_HOST_K8S_STAGE }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_OIDC_CRIB_ROLE_ARN_STAGE }}
          ecr-private-registry: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
          ingress-base-domain: ${{ secrets.INGRESS_BASE_DOMAIN_STAGE }}
          k8s-cluster-name: ${{ secrets.AWS_K8S_CLUSTER_NAME_STAGE }}
          command: "core"
          # Send alerts only for push to main
          send-alerts: ${{ github.event_name == 'push' && 'true' || 'false'}}
          crib-alert-slack-webhook: ${{ secrets.CRIB_ALERT_SLACK_WEBHOOK }}
          crib-repo-ref: ${{ github.ref }}

      - name: Destroy CRIB Environment
        id: destroy
        if: always() && steps.deploy.outputs.devspace-namespace != '' && inputs.debug != 'true' && steps.check-prereqs-for-running.outputs.should_run == 'true'
        uses: smartcontractkit/.github/actions/crib-purge-environment@da1c0099f3bab236660ccc10328a29e06950c69f # crib-purge-environment@0.2.0
        with:
          namespace: ${{ steps.deploy.outputs.devspace-namespace }}
