name: CRIB CCIP/Atlas Smoke Test

on:
  push:
    paths:
      - "deployments/ccip/**"
      - "!(deployments/core)/**" # Exclude changes in the core directory
      - "!*.md" # Exclude markdown files
      - "*" # Include any common changes

jobs:
  run-crib-ccip-atlas-smoke-test:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Deploy and validate CRIB Environment for CCIP and Atlas
        uses: smartcontractkit/.github/actions/setup-crib-environment@3c78a88c065000589cf52ec9a2b17c9db00fc66e
        with:
          api-gateway-host: ${{ secrets.AWS_API_GW_HOST_K8S_STAGE }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_OIDC_CRIB_ROLE_ARN_STAGE }}
          ecr-private-registry-stage: ${{ secrets.AWS_ACCOUNT_ID_STAGE }}
          ecr-private-registry: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
          ingress-base-domain: ${{ secrets.INGRESS_BASE_DOMAIN_STAGE }}
          k8s-cluster-name: ${{ secrets.AWS_K8S_CLUSTER_NAME_STAGE }}
          product: "ccip"
