---
name: CRIB Core Smoke Test

on:
  pull_request:
    branches:
      - "*" # Trigger on any branch in a PR
    paths:
      # Include common changes
      - "*"
      - "components/**"
      - "scripts/**"
      # Include crib core changes
      - "deployments/core/**"
      - ".github/workflows/crib-core-smoke-test.yml"
      # Exclude doc updates
      - "!**/*.md" # Exclude doc updates
  push:
    branches:
      - main # Trigger only on pushes to the main branch
    paths:
      # Include common changes
      - "*"
      - "components/**"
      - "scripts/**"
      # Include crib core changes
      - "deployments/core/**"
      - ".github/workflows/crib-core-smoke-test.yml"
      # Exclude doc updates
      - "!**/*.md" # Exclude doc updates
  workflow_dispatch:
    inputs:
      debug:
        description: |
          Enables debug mode to disable CRIB env teardown
        default: false
        required: false

jobs:
  run-crib-core-smoke-test:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout crib git repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Deploy and validate CRIB Environment for Core
        id: deploy
        uses: smartcontractkit/.github/actions/crib-deploy-environment@c0b38e6c40d72d01b8d2f24f92623a2538b3dedb # v0.5.0
        with:
          api-gateway-host: ${{ secrets.AWS_API_GW_HOST_K8S_STAGE }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_OIDC_CRIB_ROLE_ARN_STAGE }}
          ecr-private-registry-stage: ${{ secrets.AWS_ACCOUNT_ID_STAGE }}
          ecr-private-registry: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
          ingress-base-domain: ${{ secrets.INGRESS_BASE_DOMAIN_STAGE }}
          k8s-cluster-name: ${{ secrets.AWS_K8S_CLUSTER_NAME_STAGE }}
          product: "core"

      - name: Destroy CRIB Environment
        id: destroy
        if: always() && steps.deploy.outputs.devspace-namespace != '' && inputs.debug != 'true'
        uses: smartcontractkit/.github/actions/crib-purge-environment@c0b38e6c40d72d01b8d2f24f92623a2538b3dedb # v0.1.0
        with:
          namespace: ${{ steps.deploy.outputs.devspace-namespace }}
