---
name: CRIB Core Smoke Test

on:
  pull_request:
    branches:
      - "*" # Trigger on any branch in a PR
    paths:
      # Include common changes
      - "*"
      - "dependencies/crib-chainlink-cluster/**"
      - "imports/**"
      - "scripts/**"
      - "cli/**"
      # Include crib core changes
      - "deployments/chainlink/**"
      - ".github/workflows/crib-core-smoke-test.yml"
      # Exclude doc updates
      - "!**/*.md" # Exclude doc updates
      # Exclude .gitignore
      - "!.gitignore"
      # Exclude changesets version bumps
      - "!package.json"
      # Exclude CODEOWNERS
      - "CODEOWNERS"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main # Trigger only on pushes to the main branch
    paths:
      # Include common changes
      - "*"
      - "dependencies/crib-chainlink-cluster/**"
      - "imports/**"
      - "scripts/**"
      # Include crib core changes
      - "deployments/chainlink/**"
      - ".github/workflows/crib-core-smoke-test.yml"
      # Exclude doc updates
      - "!**/*.md" # Exclude doc updates
      # Exclude .gitignore
      - "!.gitignore"
      # Exclude changesets version bumps
      - "!package.json"
      # Exclude CODEOWNERS
      - "CODEOWNERS"
  workflow_dispatch:
    inputs:
      debug:
        description: |
          Enables debug mode to disable CRIB env teardown
        default: "false"
        required: false
jobs:
  run-crib-core-smoke-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      CHAINLINK_HELM_REGISTRY_URI: oci://${{secrets.AWS_ACCOUNT_ID_PROD}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/infra-charts
    permissions:
      id-token: write
      contents: read
      actions: read
      pull-requests: read
    steps:
      - name: Prevent running on draft or changesets PRs
        id: check-prereqs-for-running
        run: |
          should_run=true
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            if [ "${{ github.event.pull_request.draft }}" == "true" ]; then
              should_run=false
            elif [ "${{ github.event.pull_request.user.login }}" == "app-token-issuer-infra-releng[bot]" ] && [[ "${{ github.event.pull_request.title }}" == "Version Packages" ]]; then
              should_run=false
            fi
          fi
          echo "should_run=$should_run" >> "$GITHUB_OUTPUT"

      - name: Deploy and validate CRIB Environment for Core
        if: steps.check-prereqs-for-running.outputs.should_run == 'true'
        id: deploy
        uses: smartcontractkit/.github/actions/crib-deploy-environment@0fae2056faabf3cdb6c35ca02f031d878ff23db7 # crib-deploy-environment@8.0.0
        with:
          aws-ecr-private-registry: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_OIDC_CRIB_ROLE_ARN_STAGE }}
          ingress-base-domain: ${{ secrets.INGRESS_BASE_DOMAIN_STAGE }}
          k8s-cluster-name: ${{ secrets.AWS_K8S_CLUSTER_NAME_STAGE }}
          command: "core"
          # Send alerts only for push to main
          send-alerts: ${{ github.event_name == 'push' && 'true' || 'false'}}
          crib-alert-slack-webhook: ${{ secrets.CRIB_ALERT_SLACK_WEBHOOK }}
          crib-repo-ref: ${{ github.ref }}
          chainlink-team: releng
          chainlink-product: crib
          k8s-api-endpoint: ${{ secrets.K8S_API_ENDPOINT_STAGE }}

      - name: Destroy CRIB Environment
        id: destroy
        if: always() && steps.deploy.outputs.devspace-namespace != '' && inputs.debug != 'true' && steps.check-prereqs-for-running.outputs.should_run == 'true'
        uses: smartcontractkit/.github/actions/crib-purge-environment@142671bc21953c8cc3edbd21848c50b5ec201c2a # crib-purge-environment@0.3.0
        with:
          namespace: ${{ steps.deploy.outputs.devspace-namespace }}
