name: PR Description Generator
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    # Reply to an existing PR to generate description (commenter requires PR write access)
    # Requires `/gpt-create-pr` commands to invoke
    types: [created]

jobs:
  llm-pr-generator:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      repository-projects: read
    steps:
      - name: Generate PR Description if PR is not from a bot
        if: ${{ !endsWith(github.actor, '[bot]') }}
        uses: smartcontractkit/.github/actions/llm-pr-writer@0.4.1
        with:
          gh-token: ${{ github.token }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          openai-model: 'gpt-4-turbo-2024-04-09'