name: pull-request-main

on:
  merge_group:
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          # TODO: read from pnpm-workspace.yaml
          filters: |
            ./cli: './cli/**'
            ./dependencies/ccip-v2-scripts: './dependencies/ccip-v2-scripts/**'

  ci-lint:
    needs: changes
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.package }}
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: ci-lint
        uses: smartcontractkit/.github/actions/ci-lint-go@7a4d99cb349ea8f25195d2390d157942031f8a57 # ci-lint-go@0.2.4
        with:
          use-go-cache: 'true'
          go-directory: ${{ matrix.package }}
          go-version-file: ${{ matrix.package }}/go.mod
          go-cache-dep-path: ${{ matrix.package }}/go.sum
          golangci-lint-args: "--timeout 20m"

  ci-lint-misc:
    needs: changes
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.package }}
    steps:
      - name: ci-lint-misc
        uses: smartcontractkit/.github/actions/ci-lint-misc@7a4d99cb349ea8f25195d2390d157942031f8a57 # ci-lint-misc@0.1.2

  ci-test:
    needs: changes
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.package }}
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: ci-test
        uses: smartcontractkit/.github/actions/ci-test-go@ci-test-go/0.3.5
        with:
          use-go-cache: 'true'
          go-version-file: ${{ matrix.package }}/go.mod
          go-cache-dep-path: ${{ matrix.package }}/go.sum
          go-test-cmd: "go test -C ${{ matrix.package }} ./..."
