name: push-tag-release

on:
  push:
    tags:
      - v*

jobs:
  ci-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: ci-lint
        uses: smartcontractkit/.github/actions/ci-lint-go@7a4d99cb349ea8f25195d2390d157942031f8a57 # ci-lint-go@0.2.4
        with:
          go-directory: ./cli
          go-version-file: ./cli/go.mod

  ci-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: ci-test
        uses: smartcontractkit/.github/actions/ci-test-go@ci-test-go/0.3.5
        with:
          use-go-cache: 'true'
          go-version-file: ./cli/go.mod
          go-cache-dep-path: ./cli/go.sum
          go-test-cmd: "go test -C ./cli ./..."

  cicd-publish-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: read
    steps:
      - name: cicd-publish-release
        uses: smartcontractkit/.github/actions/cicd-build-publish-artifacts-go@8cdc7de89f2ef63669ab9494a5dd35fee544ed3c # cicd-build-publish-artifacts-go@0.3.0
        with:
          # general inputs
          app-name: crib # cli
          # goreleaser inputs
          goreleaser-version: '~> v2'
          goreleaser-workdir: ./cli
          go-version-file: ./cli/go.mod
          go-cache-dep-path: ./cli/go.sum
