name: Solana Verified Build

on:
  push:
    branches:
      - main
      - tt/verified
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest-8cores-32GB
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4 # v1
    - name: Install Solana Verify
      run: |
        cargo install solana-verify
    - name: Cache cargo target dir
      id: cache-target
      uses: actions/cache@v4 # v4
      with:
        path: chains/solana/contracts/target
        key: ${{ runner.os }}-solana-contract-verified-${{ hashFiles('**/Cargo.lock') }}
    - name: Build Verified Artifacts
      if: steps.cache-target.outputs.cache-hit != 'true'
      run: |
        cd chains/solana/contracts
        solana-verify build
    - name: Upload artifact
      continue-on-error: true # don't fail if the upload fails, it might conflict with another job
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: solana-ccip-${{ github.sha }}
        path: chains/solana/contracts/target/deploy/*.so
