name: Solana Verified Build

on:
  push:
    branches:
      - main
      - tt/verified
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest-8cores-32GB
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4 # v1
    - name: Install Solana Verify
      run: |
        cargo install solana-verify
    - name: Build Verified Artifacts
      run: |
        cd chains/solana/contracts
        solana-verify build
