name: "Test EVM Deployments"
permissions:
  contents: read

on:
  pull_request:
  merge_group:
  push:
    branches:
      - 'main'
    paths:
      - ./chains/evm/gobindings/generated/**
      - ./chains/evm/deployment/**

jobs:
  test-evm-deployments:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chains/evm/deployment
    steps:
      - uses: actions/checkout@v4
      - name: Determine Go version
        id: go_version
        run: echo "GO_VERSION=$(cat go.mod |grep "^go"|cut -d' ' -f 2)" >> $GITHUB_ENV
      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Display Go version
        run: go version
      - name: Run tests
        run: go test ./...
