name: Devenv Tidy
on:
  push:

defaults:
  run:
    working-directory: v2/build/devenv

permissions:
  contents: read

jobs:
  devenv-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: Set up Go with module caching
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: v2/build/devenv/go.mod
      - name: Verify go.mod and go.sum
        run: |
          go mod tidy
          if ! git diff --exit-code -- go.mod go.sum; then
            echo "❌ go.mod or go.sum has uncommitted changes after go mod tidy"
            echo "Please run: go mod tidy"
            git diff -- go.mod go.sum
            exit 1
          fi