name: Yaml Lint
on:
  pull_request:

jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            rules:
              new-line-at-end-of-file:
                level: warning
              line-length:
                max: 120
                level: warning
            yaml-files:
              - '*.yaml'
              - '*.yml'
              - '.yamllint'
              - '*.yaml.example'
